// Code generated by ent, DO NOT EDIT.

package dismissalorderheader

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the dismissalorderheader type in the database.
	Label = "dismissal_order_header"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// FieldPreparationDate holds the string denoting the preparation_date field in the database.
	FieldPreparationDate = "preparation_date"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeBodies holds the string denoting the bodies edge name in mutations.
	EdgeBodies = "bodies"
	// Table holds the table name of the dismissalorderheader in the database.
	Table = "dismissal_order_headers"
	// BodiesTable is the table that holds the bodies relation/edge.
	BodiesTable = "dismissal_order_bodies"
	// BodiesInverseTable is the table name for the DismissalOrderBody entity.
	// It exists in this package in order to avoid circular dependency with the "dismissalorderbody" package.
	BodiesInverseTable = "dismissal_order_bodies"
	// BodiesColumn is the table column denoting the bodies relation/edge.
	BodiesColumn = "dismissal_order_header_id"
)

// Columns holds all SQL columns for dismissalorderheader fields.
var Columns = []string{
	FieldID,
	FieldNumber,
	FieldPreparationDate,
	FieldOrganizationID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NumberValidator is a validator for the "number" field. It is called by the builders before save.
	NumberValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the DismissalOrderHeader queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNumber orders the results by the number field.
func ByNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumber, opts...).ToFunc()
}

// ByPreparationDate orders the results by the preparation_date field.
func ByPreparationDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreparationDate, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByBodiesCount orders the results by bodies count.
func ByBodiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBodiesStep(), opts...)
	}
}

// ByBodies orders the results by bodies terms.
func ByBodies(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBodiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newBodiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BodiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BodiesTable, BodiesColumn),
	)
}
