// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/example/micro/organizations/ent/organization"
	"github.com/example/micro/organizations/ent/predicate"
)

// OrganizationUpdate is the builder for updating Organization entities.
type OrganizationUpdate struct {
	config
	hooks    []Hook
	mutation *OrganizationMutation
}

// Where appends a list predicates to the OrganizationUpdate builder.
func (ou *OrganizationUpdate) Where(ps ...predicate.Organization) *OrganizationUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetTitle sets the "title" field.
func (ou *OrganizationUpdate) SetTitle(s string) *OrganizationUpdate {
	ou.mutation.SetTitle(s)
	return ou
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (ou *OrganizationUpdate) SetNillableTitle(s *string) *OrganizationUpdate {
	if s != nil {
		ou.SetTitle(*s)
	}
	return ou
}

// SetAddress sets the "address" field.
func (ou *OrganizationUpdate) SetAddress(s string) *OrganizationUpdate {
	ou.mutation.SetAddress(s)
	return ou
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (ou *OrganizationUpdate) SetNillableAddress(s *string) *OrganizationUpdate {
	if s != nil {
		ou.SetAddress(*s)
	}
	return ou
}

// SetOkpo sets the "okpo" field.
func (ou *OrganizationUpdate) SetOkpo(s string) *OrganizationUpdate {
	ou.mutation.SetOkpo(s)
	return ou
}

// SetNillableOkpo sets the "okpo" field if the given value is not nil.
func (ou *OrganizationUpdate) SetNillableOkpo(s *string) *OrganizationUpdate {
	if s != nil {
		ou.SetOkpo(*s)
	}
	return ou
}

// SetInn sets the "inn" field.
func (ou *OrganizationUpdate) SetInn(s string) *OrganizationUpdate {
	ou.mutation.SetInn(s)
	return ou
}

// SetNillableInn sets the "inn" field if the given value is not nil.
func (ou *OrganizationUpdate) SetNillableInn(s *string) *OrganizationUpdate {
	if s != nil {
		ou.SetInn(*s)
	}
	return ou
}

// SetKpp sets the "kpp" field.
func (ou *OrganizationUpdate) SetKpp(s string) *OrganizationUpdate {
	ou.mutation.SetKpp(s)
	return ou
}

// SetNillableKpp sets the "kpp" field if the given value is not nil.
func (ou *OrganizationUpdate) SetNillableKpp(s *string) *OrganizationUpdate {
	if s != nil {
		ou.SetKpp(*s)
	}
	return ou
}

// ClearKpp clears the value of the "kpp" field.
func (ou *OrganizationUpdate) ClearKpp() *OrganizationUpdate {
	ou.mutation.ClearKpp()
	return ou
}

// SetAccountID sets the "account_id" field.
func (ou *OrganizationUpdate) SetAccountID(i int64) *OrganizationUpdate {
	ou.mutation.ResetAccountID()
	ou.mutation.SetAccountID(i)
	return ou
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (ou *OrganizationUpdate) SetNillableAccountID(i *int64) *OrganizationUpdate {
	if i != nil {
		ou.SetAccountID(*i)
	}
	return ou
}

// AddAccountID adds i to the "account_id" field.
func (ou *OrganizationUpdate) AddAccountID(i int64) *OrganizationUpdate {
	ou.mutation.AddAccountID(i)
	return ou
}

// SetCreatedAt sets the "created_at" field.
func (ou *OrganizationUpdate) SetCreatedAt(t time.Time) *OrganizationUpdate {
	ou.mutation.SetCreatedAt(t)
	return ou
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ou *OrganizationUpdate) SetNillableCreatedAt(t *time.Time) *OrganizationUpdate {
	if t != nil {
		ou.SetCreatedAt(*t)
	}
	return ou
}

// SetUpdatedAt sets the "updated_at" field.
func (ou *OrganizationUpdate) SetUpdatedAt(t time.Time) *OrganizationUpdate {
	ou.mutation.SetUpdatedAt(t)
	return ou
}

// Mutation returns the OrganizationMutation object of the builder.
func (ou *OrganizationUpdate) Mutation() *OrganizationMutation {
	return ou.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OrganizationUpdate) Save(ctx context.Context) (int, error) {
	ou.defaults()
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OrganizationUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OrganizationUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OrganizationUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ou *OrganizationUpdate) defaults() {
	if _, ok := ou.mutation.UpdatedAt(); !ok {
		v := organization.UpdateDefaultUpdatedAt()
		ou.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ou *OrganizationUpdate) check() error {
	if v, ok := ou.mutation.Title(); ok {
		if err := organization.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Organization.title": %w`, err)}
		}
	}
	if v, ok := ou.mutation.Address(); ok {
		if err := organization.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Organization.address": %w`, err)}
		}
	}
	if v, ok := ou.mutation.Okpo(); ok {
		if err := organization.OkpoValidator(v); err != nil {
			return &ValidationError{Name: "okpo", err: fmt.Errorf(`ent: validator failed for field "Organization.okpo": %w`, err)}
		}
	}
	if v, ok := ou.mutation.Inn(); ok {
		if err := organization.InnValidator(v); err != nil {
			return &ValidationError{Name: "inn", err: fmt.Errorf(`ent: validator failed for field "Organization.inn": %w`, err)}
		}
	}
	if v, ok := ou.mutation.Kpp(); ok {
		if err := organization.KppValidator(v); err != nil {
			return &ValidationError{Name: "kpp", err: fmt.Errorf(`ent: validator failed for field "Organization.kpp": %w`, err)}
		}
	}
	return nil
}

func (ou *OrganizationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ou.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(organization.Table, organization.Columns, sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.Title(); ok {
		_spec.SetField(organization.FieldTitle, field.TypeString, value)
	}
	if value, ok := ou.mutation.Address(); ok {
		_spec.SetField(organization.FieldAddress, field.TypeString, value)
	}
	if value, ok := ou.mutation.Okpo(); ok {
		_spec.SetField(organization.FieldOkpo, field.TypeString, value)
	}
	if value, ok := ou.mutation.Inn(); ok {
		_spec.SetField(organization.FieldInn, field.TypeString, value)
	}
	if value, ok := ou.mutation.Kpp(); ok {
		_spec.SetField(organization.FieldKpp, field.TypeString, value)
	}
	if ou.mutation.KppCleared() {
		_spec.ClearField(organization.FieldKpp, field.TypeString)
	}
	if value, ok := ou.mutation.AccountID(); ok {
		_spec.SetField(organization.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := ou.mutation.AddedAccountID(); ok {
		_spec.AddField(organization.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := ou.mutation.CreatedAt(); ok {
		_spec.SetField(organization.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := ou.mutation.UpdatedAt(); ok {
		_spec.SetField(organization.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OrganizationUpdateOne is the builder for updating a single Organization entity.
type OrganizationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrganizationMutation
}

// SetTitle sets the "title" field.
func (ouo *OrganizationUpdateOne) SetTitle(s string) *OrganizationUpdateOne {
	ouo.mutation.SetTitle(s)
	return ouo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (ouo *OrganizationUpdateOne) SetNillableTitle(s *string) *OrganizationUpdateOne {
	if s != nil {
		ouo.SetTitle(*s)
	}
	return ouo
}

// SetAddress sets the "address" field.
func (ouo *OrganizationUpdateOne) SetAddress(s string) *OrganizationUpdateOne {
	ouo.mutation.SetAddress(s)
	return ouo
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (ouo *OrganizationUpdateOne) SetNillableAddress(s *string) *OrganizationUpdateOne {
	if s != nil {
		ouo.SetAddress(*s)
	}
	return ouo
}

// SetOkpo sets the "okpo" field.
func (ouo *OrganizationUpdateOne) SetOkpo(s string) *OrganizationUpdateOne {
	ouo.mutation.SetOkpo(s)
	return ouo
}

// SetNillableOkpo sets the "okpo" field if the given value is not nil.
func (ouo *OrganizationUpdateOne) SetNillableOkpo(s *string) *OrganizationUpdateOne {
	if s != nil {
		ouo.SetOkpo(*s)
	}
	return ouo
}

// SetInn sets the "inn" field.
func (ouo *OrganizationUpdateOne) SetInn(s string) *OrganizationUpdateOne {
	ouo.mutation.SetInn(s)
	return ouo
}

// SetNillableInn sets the "inn" field if the given value is not nil.
func (ouo *OrganizationUpdateOne) SetNillableInn(s *string) *OrganizationUpdateOne {
	if s != nil {
		ouo.SetInn(*s)
	}
	return ouo
}

// SetKpp sets the "kpp" field.
func (ouo *OrganizationUpdateOne) SetKpp(s string) *OrganizationUpdateOne {
	ouo.mutation.SetKpp(s)
	return ouo
}

// SetNillableKpp sets the "kpp" field if the given value is not nil.
func (ouo *OrganizationUpdateOne) SetNillableKpp(s *string) *OrganizationUpdateOne {
	if s != nil {
		ouo.SetKpp(*s)
	}
	return ouo
}

// ClearKpp clears the value of the "kpp" field.
func (ouo *OrganizationUpdateOne) ClearKpp() *OrganizationUpdateOne {
	ouo.mutation.ClearKpp()
	return ouo
}

// SetAccountID sets the "account_id" field.
func (ouo *OrganizationUpdateOne) SetAccountID(i int64) *OrganizationUpdateOne {
	ouo.mutation.ResetAccountID()
	ouo.mutation.SetAccountID(i)
	return ouo
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (ouo *OrganizationUpdateOne) SetNillableAccountID(i *int64) *OrganizationUpdateOne {
	if i != nil {
		ouo.SetAccountID(*i)
	}
	return ouo
}

// AddAccountID adds i to the "account_id" field.
func (ouo *OrganizationUpdateOne) AddAccountID(i int64) *OrganizationUpdateOne {
	ouo.mutation.AddAccountID(i)
	return ouo
}

// SetCreatedAt sets the "created_at" field.
func (ouo *OrganizationUpdateOne) SetCreatedAt(t time.Time) *OrganizationUpdateOne {
	ouo.mutation.SetCreatedAt(t)
	return ouo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ouo *OrganizationUpdateOne) SetNillableCreatedAt(t *time.Time) *OrganizationUpdateOne {
	if t != nil {
		ouo.SetCreatedAt(*t)
	}
	return ouo
}

// SetUpdatedAt sets the "updated_at" field.
func (ouo *OrganizationUpdateOne) SetUpdatedAt(t time.Time) *OrganizationUpdateOne {
	ouo.mutation.SetUpdatedAt(t)
	return ouo
}

// Mutation returns the OrganizationMutation object of the builder.
func (ouo *OrganizationUpdateOne) Mutation() *OrganizationMutation {
	return ouo.mutation
}

// Where appends a list predicates to the OrganizationUpdate builder.
func (ouo *OrganizationUpdateOne) Where(ps ...predicate.Organization) *OrganizationUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OrganizationUpdateOne) Select(field string, fields ...string) *OrganizationUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Organization entity.
func (ouo *OrganizationUpdateOne) Save(ctx context.Context) (*Organization, error) {
	ouo.defaults()
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OrganizationUpdateOne) SaveX(ctx context.Context) *Organization {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OrganizationUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OrganizationUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouo *OrganizationUpdateOne) defaults() {
	if _, ok := ouo.mutation.UpdatedAt(); !ok {
		v := organization.UpdateDefaultUpdatedAt()
		ouo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OrganizationUpdateOne) check() error {
	if v, ok := ouo.mutation.Title(); ok {
		if err := organization.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Organization.title": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.Address(); ok {
		if err := organization.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Organization.address": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.Okpo(); ok {
		if err := organization.OkpoValidator(v); err != nil {
			return &ValidationError{Name: "okpo", err: fmt.Errorf(`ent: validator failed for field "Organization.okpo": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.Inn(); ok {
		if err := organization.InnValidator(v); err != nil {
			return &ValidationError{Name: "inn", err: fmt.Errorf(`ent: validator failed for field "Organization.inn": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.Kpp(); ok {
		if err := organization.KppValidator(v); err != nil {
			return &ValidationError{Name: "kpp", err: fmt.Errorf(`ent: validator failed for field "Organization.kpp": %w`, err)}
		}
	}
	return nil
}

func (ouo *OrganizationUpdateOne) sqlSave(ctx context.Context) (_node *Organization, err error) {
	if err := ouo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organization.Table, organization.Columns, sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Organization.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organization.FieldID)
		for _, f := range fields {
			if !organization.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != organization.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.Title(); ok {
		_spec.SetField(organization.FieldTitle, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Address(); ok {
		_spec.SetField(organization.FieldAddress, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Okpo(); ok {
		_spec.SetField(organization.FieldOkpo, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Inn(); ok {
		_spec.SetField(organization.FieldInn, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Kpp(); ok {
		_spec.SetField(organization.FieldKpp, field.TypeString, value)
	}
	if ouo.mutation.KppCleared() {
		_spec.ClearField(organization.FieldKpp, field.TypeString)
	}
	if value, ok := ouo.mutation.AccountID(); ok {
		_spec.SetField(organization.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := ouo.mutation.AddedAccountID(); ok {
		_spec.AddField(organization.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := ouo.mutation.CreatedAt(); ok {
		_spec.SetField(organization.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := ouo.mutation.UpdatedAt(); ok {
		_spec.SetField(organization.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Organization{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
