// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/example/micro/employment-order/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/example/micro/employment-order/ent/employmentorderbody"
	"github.com/example/micro/employment-order/ent/employmentorderheader"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// EmploymentOrderBody is the client for interacting with the EmploymentOrderBody builders.
	EmploymentOrderBody *EmploymentOrderBodyClient
	// EmploymentOrderHeader is the client for interacting with the EmploymentOrderHeader builders.
	EmploymentOrderHeader *EmploymentOrderHeaderClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.EmploymentOrderBody = NewEmploymentOrderBodyClient(c.config)
	c.EmploymentOrderHeader = NewEmploymentOrderHeaderClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                   ctx,
		config:                cfg,
		EmploymentOrderBody:   NewEmploymentOrderBodyClient(cfg),
		EmploymentOrderHeader: NewEmploymentOrderHeaderClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                   ctx,
		config:                cfg,
		EmploymentOrderBody:   NewEmploymentOrderBodyClient(cfg),
		EmploymentOrderHeader: NewEmploymentOrderHeaderClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		EmploymentOrderBody.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.EmploymentOrderBody.Use(hooks...)
	c.EmploymentOrderHeader.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.EmploymentOrderBody.Intercept(interceptors...)
	c.EmploymentOrderHeader.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *EmploymentOrderBodyMutation:
		return c.EmploymentOrderBody.mutate(ctx, m)
	case *EmploymentOrderHeaderMutation:
		return c.EmploymentOrderHeader.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// EmploymentOrderBodyClient is a client for the EmploymentOrderBody schema.
type EmploymentOrderBodyClient struct {
	config
}

// NewEmploymentOrderBodyClient returns a client for the EmploymentOrderBody from the given config.
func NewEmploymentOrderBodyClient(c config) *EmploymentOrderBodyClient {
	return &EmploymentOrderBodyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `employmentorderbody.Hooks(f(g(h())))`.
func (c *EmploymentOrderBodyClient) Use(hooks ...Hook) {
	c.hooks.EmploymentOrderBody = append(c.hooks.EmploymentOrderBody, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `employmentorderbody.Intercept(f(g(h())))`.
func (c *EmploymentOrderBodyClient) Intercept(interceptors ...Interceptor) {
	c.inters.EmploymentOrderBody = append(c.inters.EmploymentOrderBody, interceptors...)
}

// Create returns a builder for creating a EmploymentOrderBody entity.
func (c *EmploymentOrderBodyClient) Create() *EmploymentOrderBodyCreate {
	mutation := newEmploymentOrderBodyMutation(c.config, OpCreate)
	return &EmploymentOrderBodyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EmploymentOrderBody entities.
func (c *EmploymentOrderBodyClient) CreateBulk(builders ...*EmploymentOrderBodyCreate) *EmploymentOrderBodyCreateBulk {
	return &EmploymentOrderBodyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EmploymentOrderBodyClient) MapCreateBulk(slice any, setFunc func(*EmploymentOrderBodyCreate, int)) *EmploymentOrderBodyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EmploymentOrderBodyCreateBulk{err: fmt.Errorf("calling to EmploymentOrderBodyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EmploymentOrderBodyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EmploymentOrderBodyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EmploymentOrderBody.
func (c *EmploymentOrderBodyClient) Update() *EmploymentOrderBodyUpdate {
	mutation := newEmploymentOrderBodyMutation(c.config, OpUpdate)
	return &EmploymentOrderBodyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EmploymentOrderBodyClient) UpdateOne(eob *EmploymentOrderBody) *EmploymentOrderBodyUpdateOne {
	mutation := newEmploymentOrderBodyMutation(c.config, OpUpdateOne, withEmploymentOrderBody(eob))
	return &EmploymentOrderBodyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EmploymentOrderBodyClient) UpdateOneID(id int64) *EmploymentOrderBodyUpdateOne {
	mutation := newEmploymentOrderBodyMutation(c.config, OpUpdateOne, withEmploymentOrderBodyID(id))
	return &EmploymentOrderBodyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EmploymentOrderBody.
func (c *EmploymentOrderBodyClient) Delete() *EmploymentOrderBodyDelete {
	mutation := newEmploymentOrderBodyMutation(c.config, OpDelete)
	return &EmploymentOrderBodyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EmploymentOrderBodyClient) DeleteOne(eob *EmploymentOrderBody) *EmploymentOrderBodyDeleteOne {
	return c.DeleteOneID(eob.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EmploymentOrderBodyClient) DeleteOneID(id int64) *EmploymentOrderBodyDeleteOne {
	builder := c.Delete().Where(employmentorderbody.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EmploymentOrderBodyDeleteOne{builder}
}

// Query returns a query builder for EmploymentOrderBody.
func (c *EmploymentOrderBodyClient) Query() *EmploymentOrderBodyQuery {
	return &EmploymentOrderBodyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEmploymentOrderBody},
		inters: c.Interceptors(),
	}
}

// Get returns a EmploymentOrderBody entity by its id.
func (c *EmploymentOrderBodyClient) Get(ctx context.Context, id int64) (*EmploymentOrderBody, error) {
	return c.Query().Where(employmentorderbody.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EmploymentOrderBodyClient) GetX(ctx context.Context, id int64) *EmploymentOrderBody {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryHeader queries the header edge of a EmploymentOrderBody.
func (c *EmploymentOrderBodyClient) QueryHeader(eob *EmploymentOrderBody) *EmploymentOrderHeaderQuery {
	query := (&EmploymentOrderHeaderClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := eob.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(employmentorderbody.Table, employmentorderbody.FieldID, id),
			sqlgraph.To(employmentorderheader.Table, employmentorderheader.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, employmentorderbody.HeaderTable, employmentorderbody.HeaderColumn),
		)
		fromV = sqlgraph.Neighbors(eob.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EmploymentOrderBodyClient) Hooks() []Hook {
	return c.hooks.EmploymentOrderBody
}

// Interceptors returns the client interceptors.
func (c *EmploymentOrderBodyClient) Interceptors() []Interceptor {
	return c.inters.EmploymentOrderBody
}

func (c *EmploymentOrderBodyClient) mutate(ctx context.Context, m *EmploymentOrderBodyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EmploymentOrderBodyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EmploymentOrderBodyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EmploymentOrderBodyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EmploymentOrderBodyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EmploymentOrderBody mutation op: %q", m.Op())
	}
}

// EmploymentOrderHeaderClient is a client for the EmploymentOrderHeader schema.
type EmploymentOrderHeaderClient struct {
	config
}

// NewEmploymentOrderHeaderClient returns a client for the EmploymentOrderHeader from the given config.
func NewEmploymentOrderHeaderClient(c config) *EmploymentOrderHeaderClient {
	return &EmploymentOrderHeaderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `employmentorderheader.Hooks(f(g(h())))`.
func (c *EmploymentOrderHeaderClient) Use(hooks ...Hook) {
	c.hooks.EmploymentOrderHeader = append(c.hooks.EmploymentOrderHeader, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `employmentorderheader.Intercept(f(g(h())))`.
func (c *EmploymentOrderHeaderClient) Intercept(interceptors ...Interceptor) {
	c.inters.EmploymentOrderHeader = append(c.inters.EmploymentOrderHeader, interceptors...)
}

// Create returns a builder for creating a EmploymentOrderHeader entity.
func (c *EmploymentOrderHeaderClient) Create() *EmploymentOrderHeaderCreate {
	mutation := newEmploymentOrderHeaderMutation(c.config, OpCreate)
	return &EmploymentOrderHeaderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EmploymentOrderHeader entities.
func (c *EmploymentOrderHeaderClient) CreateBulk(builders ...*EmploymentOrderHeaderCreate) *EmploymentOrderHeaderCreateBulk {
	return &EmploymentOrderHeaderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EmploymentOrderHeaderClient) MapCreateBulk(slice any, setFunc func(*EmploymentOrderHeaderCreate, int)) *EmploymentOrderHeaderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EmploymentOrderHeaderCreateBulk{err: fmt.Errorf("calling to EmploymentOrderHeaderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EmploymentOrderHeaderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EmploymentOrderHeaderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EmploymentOrderHeader.
func (c *EmploymentOrderHeaderClient) Update() *EmploymentOrderHeaderUpdate {
	mutation := newEmploymentOrderHeaderMutation(c.config, OpUpdate)
	return &EmploymentOrderHeaderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EmploymentOrderHeaderClient) UpdateOne(eoh *EmploymentOrderHeader) *EmploymentOrderHeaderUpdateOne {
	mutation := newEmploymentOrderHeaderMutation(c.config, OpUpdateOne, withEmploymentOrderHeader(eoh))
	return &EmploymentOrderHeaderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EmploymentOrderHeaderClient) UpdateOneID(id int64) *EmploymentOrderHeaderUpdateOne {
	mutation := newEmploymentOrderHeaderMutation(c.config, OpUpdateOne, withEmploymentOrderHeaderID(id))
	return &EmploymentOrderHeaderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EmploymentOrderHeader.
func (c *EmploymentOrderHeaderClient) Delete() *EmploymentOrderHeaderDelete {
	mutation := newEmploymentOrderHeaderMutation(c.config, OpDelete)
	return &EmploymentOrderHeaderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EmploymentOrderHeaderClient) DeleteOne(eoh *EmploymentOrderHeader) *EmploymentOrderHeaderDeleteOne {
	return c.DeleteOneID(eoh.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EmploymentOrderHeaderClient) DeleteOneID(id int64) *EmploymentOrderHeaderDeleteOne {
	builder := c.Delete().Where(employmentorderheader.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EmploymentOrderHeaderDeleteOne{builder}
}

// Query returns a query builder for EmploymentOrderHeader.
func (c *EmploymentOrderHeaderClient) Query() *EmploymentOrderHeaderQuery {
	return &EmploymentOrderHeaderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEmploymentOrderHeader},
		inters: c.Interceptors(),
	}
}

// Get returns a EmploymentOrderHeader entity by its id.
func (c *EmploymentOrderHeaderClient) Get(ctx context.Context, id int64) (*EmploymentOrderHeader, error) {
	return c.Query().Where(employmentorderheader.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EmploymentOrderHeaderClient) GetX(ctx context.Context, id int64) *EmploymentOrderHeader {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBodies queries the bodies edge of a EmploymentOrderHeader.
func (c *EmploymentOrderHeaderClient) QueryBodies(eoh *EmploymentOrderHeader) *EmploymentOrderBodyQuery {
	query := (&EmploymentOrderBodyClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := eoh.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(employmentorderheader.Table, employmentorderheader.FieldID, id),
			sqlgraph.To(employmentorderbody.Table, employmentorderbody.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, employmentorderheader.BodiesTable, employmentorderheader.BodiesColumn),
		)
		fromV = sqlgraph.Neighbors(eoh.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EmploymentOrderHeaderClient) Hooks() []Hook {
	return c.hooks.EmploymentOrderHeader
}

// Interceptors returns the client interceptors.
func (c *EmploymentOrderHeaderClient) Interceptors() []Interceptor {
	return c.inters.EmploymentOrderHeader
}

func (c *EmploymentOrderHeaderClient) mutate(ctx context.Context, m *EmploymentOrderHeaderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EmploymentOrderHeaderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EmploymentOrderHeaderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EmploymentOrderHeaderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EmploymentOrderHeaderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EmploymentOrderHeader mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		EmploymentOrderBody, EmploymentOrderHeader []ent.Hook
	}
	inters struct {
		EmploymentOrderBody, EmploymentOrderHeader []ent.Interceptor
	}
)
