// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/example/micro/employment-order/ent/employmentorderheader"
)

// EmploymentOrderHeader is the model entity for the EmploymentOrderHeader schema.
type EmploymentOrderHeader struct {
	config `json:"-"`
	// ID of the ent.
	// matches BIGSERIAL
	ID int64 `json:"id,omitempty"`
	// Number holds the value of the "number" field.
	Number string `json:"number,omitempty"`
	// PreparationDate holds the value of the "preparation_date" field.
	PreparationDate time.Time `json:"preparation_date,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID int64 `json:"organization_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EmploymentOrderHeaderQuery when eager-loading is set.
	Edges        EmploymentOrderHeaderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EmploymentOrderHeaderEdges holds the relations/edges for other nodes in the graph.
type EmploymentOrderHeaderEdges struct {
	// Bodies holds the value of the bodies edge.
	Bodies []*EmploymentOrderBody `json:"bodies,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// BodiesOrErr returns the Bodies value or an error if the edge
// was not loaded in eager-loading.
func (e EmploymentOrderHeaderEdges) BodiesOrErr() ([]*EmploymentOrderBody, error) {
	if e.loadedTypes[0] {
		return e.Bodies, nil
	}
	return nil, &NotLoadedError{edge: "bodies"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EmploymentOrderHeader) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case employmentorderheader.FieldID, employmentorderheader.FieldOrganizationID:
			values[i] = new(sql.NullInt64)
		case employmentorderheader.FieldNumber:
			values[i] = new(sql.NullString)
		case employmentorderheader.FieldPreparationDate, employmentorderheader.FieldCreatedAt, employmentorderheader.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EmploymentOrderHeader fields.
func (eoh *EmploymentOrderHeader) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case employmentorderheader.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			eoh.ID = int64(value.Int64)
		case employmentorderheader.FieldNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field number", values[i])
			} else if value.Valid {
				eoh.Number = value.String
			}
		case employmentorderheader.FieldPreparationDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field preparation_date", values[i])
			} else if value.Valid {
				eoh.PreparationDate = value.Time
			}
		case employmentorderheader.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				eoh.OrganizationID = value.Int64
			}
		case employmentorderheader.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				eoh.CreatedAt = value.Time
			}
		case employmentorderheader.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				eoh.UpdatedAt = value.Time
			}
		default:
			eoh.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EmploymentOrderHeader.
// This includes values selected through modifiers, order, etc.
func (eoh *EmploymentOrderHeader) Value(name string) (ent.Value, error) {
	return eoh.selectValues.Get(name)
}

// QueryBodies queries the "bodies" edge of the EmploymentOrderHeader entity.
func (eoh *EmploymentOrderHeader) QueryBodies() *EmploymentOrderBodyQuery {
	return NewEmploymentOrderHeaderClient(eoh.config).QueryBodies(eoh)
}

// Update returns a builder for updating this EmploymentOrderHeader.
// Note that you need to call EmploymentOrderHeader.Unwrap() before calling this method if this EmploymentOrderHeader
// was returned from a transaction, and the transaction was committed or rolled back.
func (eoh *EmploymentOrderHeader) Update() *EmploymentOrderHeaderUpdateOne {
	return NewEmploymentOrderHeaderClient(eoh.config).UpdateOne(eoh)
}

// Unwrap unwraps the EmploymentOrderHeader entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (eoh *EmploymentOrderHeader) Unwrap() *EmploymentOrderHeader {
	_tx, ok := eoh.config.driver.(*txDriver)
	if !ok {
		panic("ent: EmploymentOrderHeader is not a transactional entity")
	}
	eoh.config.driver = _tx.drv
	return eoh
}

// String implements the fmt.Stringer.
func (eoh *EmploymentOrderHeader) String() string {
	var builder strings.Builder
	builder.WriteString("EmploymentOrderHeader(")
	builder.WriteString(fmt.Sprintf("id=%v, ", eoh.ID))
	builder.WriteString("number=")
	builder.WriteString(eoh.Number)
	builder.WriteString(", ")
	builder.WriteString("preparation_date=")
	builder.WriteString(eoh.PreparationDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("organization_id=")
	builder.WriteString(fmt.Sprintf("%v", eoh.OrganizationID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(eoh.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(eoh.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EmploymentOrderHeaders is a parsable slice of EmploymentOrderHeader.
type EmploymentOrderHeaders []*EmploymentOrderHeader
