// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/example/micro/employment-order/ent/employmentorderbody"
	"github.com/example/micro/employment-order/ent/predicate"
)

// EmploymentOrderBodyDelete is the builder for deleting a EmploymentOrderBody entity.
type EmploymentOrderBodyDelete struct {
	config
	hooks    []Hook
	mutation *EmploymentOrderBodyMutation
}

// Where appends a list predicates to the EmploymentOrderBodyDelete builder.
func (eobd *EmploymentOrderBodyDelete) Where(ps ...predicate.EmploymentOrderBody) *EmploymentOrderBodyDelete {
	eobd.mutation.Where(ps...)
	return eobd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (eobd *EmploymentOrderBodyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, eobd.sqlExec, eobd.mutation, eobd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (eobd *EmploymentOrderBodyDelete) ExecX(ctx context.Context) int {
	n, err := eobd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (eobd *EmploymentOrderBodyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(employmentorderbody.Table, sqlgraph.NewFieldSpec(employmentorderbody.FieldID, field.TypeInt64))
	if ps := eobd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, eobd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	eobd.mutation.done = true
	return affected, err
}

// EmploymentOrderBodyDeleteOne is the builder for deleting a single EmploymentOrderBody entity.
type EmploymentOrderBodyDeleteOne struct {
	eobd *EmploymentOrderBodyDelete
}

// Where appends a list predicates to the EmploymentOrderBodyDelete builder.
func (eobdo *EmploymentOrderBodyDeleteOne) Where(ps ...predicate.EmploymentOrderBody) *EmploymentOrderBodyDeleteOne {
	eobdo.eobd.mutation.Where(ps...)
	return eobdo
}

// Exec executes the deletion query.
func (eobdo *EmploymentOrderBodyDeleteOne) Exec(ctx context.Context) error {
	n, err := eobdo.eobd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{employmentorderbody.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (eobdo *EmploymentOrderBodyDeleteOne) ExecX(ctx context.Context) {
	if err := eobdo.Exec(ctx); err != nil {
		panic(err)
	}
}
