// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/example/micro/employment-order/ent/employmentorderbody"
	"github.com/example/micro/employment-order/ent/employmentorderheader"
	"github.com/example/micro/employment-order/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	employmentorderbodyFields := schema.EmploymentOrderBody{}.Fields()
	_ = employmentorderbodyFields
	// employmentorderbodyDescCreatedAt is the schema descriptor for created_at field.
	employmentorderbodyDescCreatedAt := employmentorderbodyFields[9].Descriptor()
	// employmentorderbody.DefaultCreatedAt holds the default value on creation for the created_at field.
	employmentorderbody.DefaultCreatedAt = employmentorderbodyDescCreatedAt.Default.(func() time.Time)
	// employmentorderbodyDescUpdatedAt is the schema descriptor for updated_at field.
	employmentorderbodyDescUpdatedAt := employmentorderbodyFields[10].Descriptor()
	// employmentorderbody.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	employmentorderbody.DefaultUpdatedAt = employmentorderbodyDescUpdatedAt.Default.(func() time.Time)
	// employmentorderbody.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	employmentorderbody.UpdateDefaultUpdatedAt = employmentorderbodyDescUpdatedAt.UpdateDefault.(func() time.Time)
	employmentorderheaderFields := schema.EmploymentOrderHeader{}.Fields()
	_ = employmentorderheaderFields
	// employmentorderheaderDescNumber is the schema descriptor for number field.
	employmentorderheaderDescNumber := employmentorderheaderFields[1].Descriptor()
	// employmentorderheader.NumberValidator is a validator for the "number" field. It is called by the builders before save.
	employmentorderheader.NumberValidator = func() func(string) error {
		validators := employmentorderheaderDescNumber.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(number string) error {
			for _, fn := range fns {
				if err := fn(number); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// employmentorderheaderDescCreatedAt is the schema descriptor for created_at field.
	employmentorderheaderDescCreatedAt := employmentorderheaderFields[4].Descriptor()
	// employmentorderheader.DefaultCreatedAt holds the default value on creation for the created_at field.
	employmentorderheader.DefaultCreatedAt = employmentorderheaderDescCreatedAt.Default.(func() time.Time)
	// employmentorderheaderDescUpdatedAt is the schema descriptor for updated_at field.
	employmentorderheaderDescUpdatedAt := employmentorderheaderFields[5].Descriptor()
	// employmentorderheader.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	employmentorderheader.DefaultUpdatedAt = employmentorderheaderDescUpdatedAt.Default.(func() time.Time)
	// employmentorderheader.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	employmentorderheader.UpdateDefaultUpdatedAt = employmentorderheaderDescUpdatedAt.UpdateDefault.(func() time.Time)
}
