// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EmploymentOrderBody is the predicate function for employmentorderbody builders.
type EmploymentOrderBody func(*sql.Selector)

// EmploymentOrderHeader is the predicate function for employmentorderheader builders.
type EmploymentOrderHeader func(*sql.Selector)
