// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/example/micro/employment-contracts/ent/employmentcontract"
)

// EmploymentContract is the model entity for the EmploymentContract schema.
type EmploymentContract struct {
	config `json:"-"`
	// ID of the ent.
	// matches BIGSERIAL
	ID int64 `json:"id,omitempty"`
	// Number holds the value of the "number" field.
	Number string `json:"number,omitempty"`
	// PersonnelNumber holds the value of the "personnel_number" field.
	PersonnelNumber string `json:"personnel_number,omitempty"`
	// ConclusionDate holds the value of the "conclusion_date" field.
	ConclusionDate time.Time `json:"conclusion_date,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID int64 `json:"organization_id,omitempty"`
	// RepresentativeID holds the value of the "representative_id" field.
	RepresentativeID int64 `json:"representative_id,omitempty"`
	// EmployeeID holds the value of the "employee_id" field.
	EmployeeID int64 `json:"employee_id,omitempty"`
	// DepartmentID holds the value of the "department_id" field.
	DepartmentID int64 `json:"department_id,omitempty"`
	// PositionID holds the value of the "position_id" field.
	PositionID int64 `json:"position_id,omitempty"`
	// ConditionsClass holds the value of the "conditions_class" field.
	ConditionsClass int `json:"conditions_class,omitempty"`
	// WorkDateFrom holds the value of the "work_date_from" field.
	WorkDateFrom time.Time `json:"work_date_from,omitempty"`
	// WorkDateTo holds the value of the "work_date_to" field.
	WorkDateTo *time.Time `json:"work_date_to,omitempty"`
	// ProbationMonths holds the value of the "probation_months" field.
	ProbationMonths *int `json:"probation_months,omitempty"`
	// Salary holds the value of the "salary" field.
	Salary float64 `json:"salary,omitempty"`
	// WorkHoursFrom holds the value of the "work_hours_from" field.
	// WorkHoursFrom holds the value of the "work_hours_from" field.
	WorkHoursFrom time.Time `json:"work_hours_from,omitempty"`
	// WorkHoursTo holds the value of the "work_hours_to" field.
	WorkHoursTo time.Time `json:"work_hours_to,omitempty"`
	// BreakFrom holds the value of the "break_from" field.
	BreakFrom *time.Time `json:"break_from,omitempty"`
	// BreakTo holds the value of the "break_to" field.
	BreakTo *time.Time `json:"break_to,omitempty"`
	// PaidLeaveDays holds the value of the "paid_leave_days" field.
	PaidLeaveDays int `json:"paid_leave_days,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EmploymentContract) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case employmentcontract.FieldSalary:
			values[i] = new(sql.NullFloat64)
		case employmentcontract.FieldID, employmentcontract.FieldOrganizationID, employmentcontract.FieldRepresentativeID, employmentcontract.FieldEmployeeID, employmentcontract.FieldDepartmentID, employmentcontract.FieldPositionID, employmentcontract.FieldConditionsClass, employmentcontract.FieldProbationMonths, employmentcontract.FieldPaidLeaveDays:
			values[i] = new(sql.NullInt64)
		case employmentcontract.FieldNumber, employmentcontract.FieldPersonnelNumber:
			values[i] = new(sql.NullString)
			case employmentcontract.FieldConclusionDate, employmentcontract.FieldWorkDateFrom, employmentcontract.FieldWorkDateTo, employmentcontract.FieldWorkHoursFrom, employmentcontract.FieldWorkHoursTo, employmentcontract.FieldBreakFrom, employmentcontract.FieldBreakTo, employmentcontract.FieldCreatedAt, employmentcontract.FieldUpdatedAt:
				values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EmploymentContract fields.
func (ec *EmploymentContract) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case employmentcontract.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ec.ID = int64(value.Int64)
		case employmentcontract.FieldNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field number", values[i])
			} else if value.Valid {
				ec.Number = value.String
			}
		case employmentcontract.FieldPersonnelNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field personnel_number", values[i])
			} else if value.Valid {
				ec.PersonnelNumber = value.String
			}
		case employmentcontract.FieldConclusionDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field conclusion_date", values[i])
			} else if value.Valid {
				ec.ConclusionDate = value.Time
			}
		case employmentcontract.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				ec.OrganizationID = value.Int64
			}
		case employmentcontract.FieldRepresentativeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field representative_id", values[i])
			} else if value.Valid {
				ec.RepresentativeID = value.Int64
			}
		case employmentcontract.FieldEmployeeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field employee_id", values[i])
			} else if value.Valid {
				ec.EmployeeID = value.Int64
			}
		case employmentcontract.FieldDepartmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value.Valid {
				ec.DepartmentID = value.Int64
			}
		case employmentcontract.FieldPositionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position_id", values[i])
			} else if value.Valid {
				ec.PositionID = value.Int64
			}
		case employmentcontract.FieldConditionsClass:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field conditions_class", values[i])
			} else if value.Valid {
				ec.ConditionsClass = int(value.Int64)
			}
		case employmentcontract.FieldWorkDateFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field work_date_from", values[i])
			} else if value.Valid {
				ec.WorkDateFrom = value.Time
			}
		case employmentcontract.FieldWorkDateTo:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field work_date_to", values[i])
			} else if value.Valid {
				ec.WorkDateTo = new(time.Time)
				*ec.WorkDateTo = value.Time
			}
		case employmentcontract.FieldProbationMonths:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field probation_months", values[i])
			} else if value.Valid {
				ec.ProbationMonths = new(int)
				*ec.ProbationMonths = int(value.Int64)
			}
		case employmentcontract.FieldSalary:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field salary", values[i])
			} else if value.Valid {
				ec.Salary = value.Float64
			}
		case employmentcontract.FieldWorkHoursFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field work_hours_from", values[i])
			} else if value.Valid {
				ec.WorkHoursFrom = value.Time
			}
		case employmentcontract.FieldWorkHoursTo:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field work_hours_to", values[i])
			} else if value.Valid {
				ec.WorkHoursTo = value.Time
			}
		case employmentcontract.FieldBreakFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field break_from", values[i])
			} else if value.Valid {
				ec.BreakFrom = new(time.Time)
				*ec.BreakFrom = value.Time
			}
		case employmentcontract.FieldBreakTo:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field break_to", values[i])
			} else if value.Valid {
				ec.BreakTo = new(time.Time)
				*ec.BreakTo = value.Time
			}
		case employmentcontract.FieldPaidLeaveDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field paid_leave_days", values[i])
			} else if value.Valid {
				ec.PaidLeaveDays = int(value.Int64)
			}
		case employmentcontract.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ec.CreatedAt = value.Time
			}
		case employmentcontract.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ec.UpdatedAt = value.Time
			}
		default:
			ec.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EmploymentContract.
// This includes values selected through modifiers, order, etc.
func (ec *EmploymentContract) Value(name string) (ent.Value, error) {
	return ec.selectValues.Get(name)
}

// Update returns a builder for updating this EmploymentContract.
// Note that you need to call EmploymentContract.Unwrap() before calling this method if this EmploymentContract
// was returned from a transaction, and the transaction was committed or rolled back.
func (ec *EmploymentContract) Update() *EmploymentContractUpdateOne {
	return NewEmploymentContractClient(ec.config).UpdateOne(ec)
}

// Unwrap unwraps the EmploymentContract entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ec *EmploymentContract) Unwrap() *EmploymentContract {
	_tx, ok := ec.config.driver.(*txDriver)
	if !ok {
		panic("ent: EmploymentContract is not a transactional entity")
	}
	ec.config.driver = _tx.drv
	return ec
}

// String implements the fmt.Stringer.
func (ec *EmploymentContract) String() string {
	var builder strings.Builder
	builder.WriteString("EmploymentContract(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ec.ID))
	builder.WriteString("number=")
	builder.WriteString(ec.Number)
	builder.WriteString(", ")
	builder.WriteString("personnel_number=")
	builder.WriteString(ec.PersonnelNumber)
	builder.WriteString(", ")
	builder.WriteString("conclusion_date=")
	builder.WriteString(ec.ConclusionDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("organization_id=")
	builder.WriteString(fmt.Sprintf("%v", ec.OrganizationID))
	builder.WriteString(", ")
	builder.WriteString("representative_id=")
	builder.WriteString(fmt.Sprintf("%v", ec.RepresentativeID))
	builder.WriteString(", ")
	builder.WriteString("employee_id=")
	builder.WriteString(fmt.Sprintf("%v", ec.EmployeeID))
	builder.WriteString(", ")
	builder.WriteString("department_id=")
	builder.WriteString(fmt.Sprintf("%v", ec.DepartmentID))
	builder.WriteString(", ")
	builder.WriteString("position_id=")
	builder.WriteString(fmt.Sprintf("%v", ec.PositionID))
	builder.WriteString(", ")
	builder.WriteString("conditions_class=")
	builder.WriteString(fmt.Sprintf("%v", ec.ConditionsClass))
	builder.WriteString(", ")
	builder.WriteString("work_date_from=")
	builder.WriteString(ec.WorkDateFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ec.WorkDateTo; v != nil {
		builder.WriteString("work_date_to=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ec.ProbationMonths; v != nil {
		builder.WriteString("probation_months=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("salary=")
	builder.WriteString(fmt.Sprintf("%v", ec.Salary))
	builder.WriteString(", ")
	builder.WriteString("work_hours_from=")
	builder.WriteString(ec.WorkHoursFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("work_hours_to=")
	builder.WriteString(ec.WorkHoursTo.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ec.BreakFrom; v != nil {
		builder.WriteString("break_from=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ec.BreakTo; v != nil {
		builder.WriteString("break_to=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("paid_leave_days=")
	builder.WriteString(fmt.Sprintf("%v", ec.PaidLeaveDays))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ec.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ec.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EmploymentContracts is a parsable slice of EmploymentContract.
type EmploymentContracts []*EmploymentContract
