// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/example/micro/employment-contracts/ent/employmentcontract"
)

// EmploymentContractCreate is the builder for creating a EmploymentContract entity.
type EmploymentContractCreate struct {
	config
	mutation *EmploymentContractMutation
	hooks    []Hook
}

// SetNumber sets the "number" field.
func (ecc *EmploymentContractCreate) SetNumber(s string) *EmploymentContractCreate {
	ecc.mutation.SetNumber(s)
	return ecc
}

// SetPersonnelNumber sets the "personnel_number" field.
func (ecc *EmploymentContractCreate) SetPersonnelNumber(s string) *EmploymentContractCreate {
	ecc.mutation.SetPersonnelNumber(s)
	return ecc
}

// SetConclusionDate sets the "conclusion_date" field.
func (ecc *EmploymentContractCreate) SetConclusionDate(t time.Time) *EmploymentContractCreate {
	ecc.mutation.SetConclusionDate(t)
	return ecc
}

// SetOrganizationID sets the "organization_id" field.
func (ecc *EmploymentContractCreate) SetOrganizationID(i int64) *EmploymentContractCreate {
	ecc.mutation.SetOrganizationID(i)
	return ecc
}

// SetRepresentativeID sets the "representative_id" field.
func (ecc *EmploymentContractCreate) SetRepresentativeID(i int64) *EmploymentContractCreate {
	ecc.mutation.SetRepresentativeID(i)
	return ecc
}

// SetEmployeeID sets the "employee_id" field.
func (ecc *EmploymentContractCreate) SetEmployeeID(i int64) *EmploymentContractCreate {
	ecc.mutation.SetEmployeeID(i)
	return ecc
}

// SetDepartmentID sets the "department_id" field.
func (ecc *EmploymentContractCreate) SetDepartmentID(i int64) *EmploymentContractCreate {
	ecc.mutation.SetDepartmentID(i)
	return ecc
}

// SetPositionID sets the "position_id" field.
func (ecc *EmploymentContractCreate) SetPositionID(i int64) *EmploymentContractCreate {
	ecc.mutation.SetPositionID(i)
	return ecc
}

// SetConditionsClass sets the "conditions_class" field.
func (ecc *EmploymentContractCreate) SetConditionsClass(i int) *EmploymentContractCreate {
	ecc.mutation.SetConditionsClass(i)
	return ecc
}

// SetWorkDateFrom sets the "work_date_from" field.
func (ecc *EmploymentContractCreate) SetWorkDateFrom(t time.Time) *EmploymentContractCreate {
	ecc.mutation.SetWorkDateFrom(t)
	return ecc
}

// SetWorkDateTo sets the "work_date_to" field.
func (ecc *EmploymentContractCreate) SetWorkDateTo(t time.Time) *EmploymentContractCreate {
	ecc.mutation.SetWorkDateTo(t)
	return ecc
}

// SetNillableWorkDateTo sets the "work_date_to" field if the given value is not nil.
func (ecc *EmploymentContractCreate) SetNillableWorkDateTo(t *time.Time) *EmploymentContractCreate {
	if t != nil {
		ecc.SetWorkDateTo(*t)
	}
	return ecc
}

// SetProbationMonths sets the "probation_months" field.
func (ecc *EmploymentContractCreate) SetProbationMonths(i int) *EmploymentContractCreate {
	ecc.mutation.SetProbationMonths(i)
	return ecc
}

// SetNillableProbationMonths sets the "probation_months" field if the given value is not nil.
func (ecc *EmploymentContractCreate) SetNillableProbationMonths(i *int) *EmploymentContractCreate {
	if i != nil {
		ecc.SetProbationMonths(*i)
	}
	return ecc
}

// SetSalary sets the "salary" field.
func (ecc *EmploymentContractCreate) SetSalary(f float64) *EmploymentContractCreate {
	ecc.mutation.SetSalary(f)
	return ecc
}

// SetWorkHoursFrom sets the "work_hours_from" field.
func (ecc *EmploymentContractCreate) SetWorkHoursFrom(t time.Time) *EmploymentContractCreate {
	ecc.mutation.SetWorkHoursFrom(t)
	return ecc
}

// SetWorkHoursTo sets the "work_hours_to" field.
func (ecc *EmploymentContractCreate) SetWorkHoursTo(t time.Time) *EmploymentContractCreate {
	ecc.mutation.SetWorkHoursTo(t)
	return ecc
}

// SetBreakFrom sets the "break_from" field.
func (ecc *EmploymentContractCreate) SetBreakFrom(t time.Time) *EmploymentContractCreate {
	ecc.mutation.SetBreakFrom(t)
	return ecc
}

// SetNillableBreakFrom sets the "break_from" field if the given value is not nil.
func (ecc *EmploymentContractCreate) SetNillableBreakFrom(t *time.Time) *EmploymentContractCreate {
	if t != nil {
		ecc.SetBreakFrom(*t)
	}
	return ecc
}

// SetBreakTo sets the "break_to" field.
func (ecc *EmploymentContractCreate) SetBreakTo(t time.Time) *EmploymentContractCreate {
	ecc.mutation.SetBreakTo(t)
	return ecc
}

// SetNillableBreakTo sets the "break_to" field if the given value is not nil.
func (ecc *EmploymentContractCreate) SetNillableBreakTo(t *time.Time) *EmploymentContractCreate {
	if t != nil {
		ecc.SetBreakTo(*t)
	}
	return ecc
}

// SetPaidLeaveDays sets the "paid_leave_days" field.
func (ecc *EmploymentContractCreate) SetPaidLeaveDays(i int) *EmploymentContractCreate {
	ecc.mutation.SetPaidLeaveDays(i)
	return ecc
}

// SetCreatedAt sets the "created_at" field.
func (ecc *EmploymentContractCreate) SetCreatedAt(t time.Time) *EmploymentContractCreate {
	ecc.mutation.SetCreatedAt(t)
	return ecc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ecc *EmploymentContractCreate) SetNillableCreatedAt(t *time.Time) *EmploymentContractCreate {
	if t != nil {
		ecc.SetCreatedAt(*t)
	}
	return ecc
}

// SetUpdatedAt sets the "updated_at" field.
func (ecc *EmploymentContractCreate) SetUpdatedAt(t time.Time) *EmploymentContractCreate {
	ecc.mutation.SetUpdatedAt(t)
	return ecc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ecc *EmploymentContractCreate) SetNillableUpdatedAt(t *time.Time) *EmploymentContractCreate {
	if t != nil {
		ecc.SetUpdatedAt(*t)
	}
	return ecc
}

// SetID sets the "id" field.
func (ecc *EmploymentContractCreate) SetID(i int64) *EmploymentContractCreate {
	ecc.mutation.SetID(i)
	return ecc
}

// Mutation returns the EmploymentContractMutation object of the builder.
func (ecc *EmploymentContractCreate) Mutation() *EmploymentContractMutation {
	return ecc.mutation
}

// Save creates the EmploymentContract in the database.
func (ecc *EmploymentContractCreate) Save(ctx context.Context) (*EmploymentContract, error) {
	ecc.defaults()
	return withHooks(ctx, ecc.sqlSave, ecc.mutation, ecc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ecc *EmploymentContractCreate) SaveX(ctx context.Context) *EmploymentContract {
	v, err := ecc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecc *EmploymentContractCreate) Exec(ctx context.Context) error {
	_, err := ecc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecc *EmploymentContractCreate) ExecX(ctx context.Context) {
	if err := ecc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ecc *EmploymentContractCreate) defaults() {
	if _, ok := ecc.mutation.CreatedAt(); !ok {
		v := employmentcontract.DefaultCreatedAt()
		ecc.mutation.SetCreatedAt(v)
	}
	if _, ok := ecc.mutation.UpdatedAt(); !ok {
		v := employmentcontract.DefaultUpdatedAt()
		ecc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ecc *EmploymentContractCreate) check() error {
	if _, ok := ecc.mutation.Number(); !ok {
		return &ValidationError{Name: "number", err: errors.New(`ent: missing required field "EmploymentContract.number"`)}
	}
	if v, ok := ecc.mutation.Number(); ok {
		if err := employmentcontract.NumberValidator(v); err != nil {
			return &ValidationError{Name: "number", err: fmt.Errorf(`ent: validator failed for field "EmploymentContract.number": %w`, err)}
		}
	}
	if _, ok := ecc.mutation.PersonnelNumber(); !ok {
		return &ValidationError{Name: "personnel_number", err: errors.New(`ent: missing required field "EmploymentContract.personnel_number"`)}
	}
	if v, ok := ecc.mutation.PersonnelNumber(); ok {
		if err := employmentcontract.PersonnelNumberValidator(v); err != nil {
			return &ValidationError{Name: "personnel_number", err: fmt.Errorf(`ent: validator failed for field "EmploymentContract.personnel_number": %w`, err)}
		}
	}
	if _, ok := ecc.mutation.ConclusionDate(); !ok {
		return &ValidationError{Name: "conclusion_date", err: errors.New(`ent: missing required field "EmploymentContract.conclusion_date"`)}
	}
	if _, ok := ecc.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "EmploymentContract.organization_id"`)}
	}
	if _, ok := ecc.mutation.RepresentativeID(); !ok {
		return &ValidationError{Name: "representative_id", err: errors.New(`ent: missing required field "EmploymentContract.representative_id"`)}
	}
	if _, ok := ecc.mutation.EmployeeID(); !ok {
		return &ValidationError{Name: "employee_id", err: errors.New(`ent: missing required field "EmploymentContract.employee_id"`)}
	}
	if _, ok := ecc.mutation.DepartmentID(); !ok {
		return &ValidationError{Name: "department_id", err: errors.New(`ent: missing required field "EmploymentContract.department_id"`)}
	}
	if _, ok := ecc.mutation.PositionID(); !ok {
		return &ValidationError{Name: "position_id", err: errors.New(`ent: missing required field "EmploymentContract.position_id"`)}
	}
	if _, ok := ecc.mutation.ConditionsClass(); !ok {
		return &ValidationError{Name: "conditions_class", err: errors.New(`ent: missing required field "EmploymentContract.conditions_class"`)}
	}
	if _, ok := ecc.mutation.WorkDateFrom(); !ok {
		return &ValidationError{Name: "work_date_from", err: errors.New(`ent: missing required field "EmploymentContract.work_date_from"`)}
	}
	if _, ok := ecc.mutation.Salary(); !ok {
		return &ValidationError{Name: "salary", err: errors.New(`ent: missing required field "EmploymentContract.salary"`)}
	}
	if _, ok := ecc.mutation.WorkHoursFrom(); !ok {
		return &ValidationError{Name: "work_hours_from", err: errors.New(`ent: missing required field "EmploymentContract.work_hours_from"`)}
	}
	if _, ok := ecc.mutation.WorkHoursTo(); !ok {
		return &ValidationError{Name: "work_hours_to", err: errors.New(`ent: missing required field "EmploymentContract.work_hours_to"`)}
	}
	if _, ok := ecc.mutation.PaidLeaveDays(); !ok {
		return &ValidationError{Name: "paid_leave_days", err: errors.New(`ent: missing required field "EmploymentContract.paid_leave_days"`)}
	}
	if _, ok := ecc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EmploymentContract.created_at"`)}
	}
	if _, ok := ecc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EmploymentContract.updated_at"`)}
	}
	return nil
}

func (ecc *EmploymentContractCreate) sqlSave(ctx context.Context) (*EmploymentContract, error) {
	if err := ecc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ecc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ecc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	ecc.mutation.id = &_node.ID
	ecc.mutation.done = true
	return _node, nil
}

func (ecc *EmploymentContractCreate) createSpec() (*EmploymentContract, *sqlgraph.CreateSpec) {
	var (
		_node = &EmploymentContract{config: ecc.config}
		_spec = sqlgraph.NewCreateSpec(employmentcontract.Table, sqlgraph.NewFieldSpec(employmentcontract.FieldID, field.TypeInt64))
	)
	if id, ok := ecc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ecc.mutation.Number(); ok {
		_spec.SetField(employmentcontract.FieldNumber, field.TypeString, value)
		_node.Number = value
	}
	if value, ok := ecc.mutation.PersonnelNumber(); ok {
		_spec.SetField(employmentcontract.FieldPersonnelNumber, field.TypeString, value)
		_node.PersonnelNumber = value
	}
	if value, ok := ecc.mutation.ConclusionDate(); ok {
		_spec.SetField(employmentcontract.FieldConclusionDate, field.TypeTime, value)
		_node.ConclusionDate = value
	}
	if value, ok := ecc.mutation.OrganizationID(); ok {
		_spec.SetField(employmentcontract.FieldOrganizationID, field.TypeInt64, value)
		_node.OrganizationID = value
	}
	if value, ok := ecc.mutation.RepresentativeID(); ok {
		_spec.SetField(employmentcontract.FieldRepresentativeID, field.TypeInt64, value)
		_node.RepresentativeID = value
	}
	if value, ok := ecc.mutation.EmployeeID(); ok {
		_spec.SetField(employmentcontract.FieldEmployeeID, field.TypeInt64, value)
		_node.EmployeeID = value
	}
	if value, ok := ecc.mutation.DepartmentID(); ok {
		_spec.SetField(employmentcontract.FieldDepartmentID, field.TypeInt64, value)
		_node.DepartmentID = value
	}
	if value, ok := ecc.mutation.PositionID(); ok {
		_spec.SetField(employmentcontract.FieldPositionID, field.TypeInt64, value)
		_node.PositionID = value
	}
	if value, ok := ecc.mutation.ConditionsClass(); ok {
		_spec.SetField(employmentcontract.FieldConditionsClass, field.TypeInt, value)
		_node.ConditionsClass = value
	}
	if value, ok := ecc.mutation.WorkDateFrom(); ok {
		_spec.SetField(employmentcontract.FieldWorkDateFrom, field.TypeTime, value)
		_node.WorkDateFrom = value
	}
	if value, ok := ecc.mutation.WorkDateTo(); ok {
		_spec.SetField(employmentcontract.FieldWorkDateTo, field.TypeTime, value)
		_node.WorkDateTo = &value
	}
	if value, ok := ecc.mutation.ProbationMonths(); ok {
		_spec.SetField(employmentcontract.FieldProbationMonths, field.TypeInt, value)
		_node.ProbationMonths = &value
	}
	if value, ok := ecc.mutation.Salary(); ok {
		_spec.SetField(employmentcontract.FieldSalary, field.TypeFloat64, value)
		_node.Salary = value
	}
	if value, ok := ecc.mutation.WorkHoursFrom(); ok {
		_spec.SetField(employmentcontract.FieldWorkHoursFrom, field.TypeTime, value)
		_node.WorkHoursFrom = value
	}
	if value, ok := ecc.mutation.WorkHoursTo(); ok {
		_spec.SetField(employmentcontract.FieldWorkHoursTo, field.TypeTime, value)
		_node.WorkHoursTo = value
	}
	if value, ok := ecc.mutation.BreakFrom(); ok {
		_spec.SetField(employmentcontract.FieldBreakFrom, field.TypeTime, value)
		_node.BreakFrom = &value
	}
	if value, ok := ecc.mutation.BreakTo(); ok {
		_spec.SetField(employmentcontract.FieldBreakTo, field.TypeTime, value)
		_node.BreakTo = &value
	}
	if value, ok := ecc.mutation.PaidLeaveDays(); ok {
		_spec.SetField(employmentcontract.FieldPaidLeaveDays, field.TypeInt, value)
		_node.PaidLeaveDays = value
	}
	if value, ok := ecc.mutation.CreatedAt(); ok {
		_spec.SetField(employmentcontract.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ecc.mutation.UpdatedAt(); ok {
		_spec.SetField(employmentcontract.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// EmploymentContractCreateBulk is the builder for creating many EmploymentContract entities in bulk.
type EmploymentContractCreateBulk struct {
	config
	err      error
	builders []*EmploymentContractCreate
}

// Save creates the EmploymentContract entities in the database.
func (eccb *EmploymentContractCreateBulk) Save(ctx context.Context) ([]*EmploymentContract, error) {
	if eccb.err != nil {
		return nil, eccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(eccb.builders))
	nodes := make([]*EmploymentContract, len(eccb.builders))
	mutators := make([]Mutator, len(eccb.builders))
	for i := range eccb.builders {
		func(i int, root context.Context) {
			builder := eccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmploymentContractMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, eccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, eccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, eccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (eccb *EmploymentContractCreateBulk) SaveX(ctx context.Context) []*EmploymentContract {
	v, err := eccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (eccb *EmploymentContractCreateBulk) Exec(ctx context.Context) error {
	_, err := eccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eccb *EmploymentContractCreateBulk) ExecX(ctx context.Context) {
	if err := eccb.Exec(ctx); err != nil {
		panic(err)
	}
}
