// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/example/micro/employment-contracts/ent/employmentcontract"
	"github.com/example/micro/employment-contracts/ent/predicate"
)

// EmploymentContractUpdate is the builder for updating EmploymentContract entities.
type EmploymentContractUpdate struct {
	config
	hooks    []Hook
	mutation *EmploymentContractMutation
}

// Where appends a list predicates to the EmploymentContractUpdate builder.
func (ecu *EmploymentContractUpdate) Where(ps ...predicate.EmploymentContract) *EmploymentContractUpdate {
	ecu.mutation.Where(ps...)
	return ecu
}

// SetNumber sets the "number" field.
func (ecu *EmploymentContractUpdate) SetNumber(s string) *EmploymentContractUpdate {
	ecu.mutation.SetNumber(s)
	return ecu
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableNumber(s *string) *EmploymentContractUpdate {
	if s != nil {
		ecu.SetNumber(*s)
	}
	return ecu
}

// SetPersonnelNumber sets the "personnel_number" field.
func (ecu *EmploymentContractUpdate) SetPersonnelNumber(s string) *EmploymentContractUpdate {
	ecu.mutation.SetPersonnelNumber(s)
	return ecu
}

// SetNillablePersonnelNumber sets the "personnel_number" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillablePersonnelNumber(s *string) *EmploymentContractUpdate {
	if s != nil {
		ecu.SetPersonnelNumber(*s)
	}
	return ecu
}

// SetConclusionDate sets the "conclusion_date" field.
func (ecu *EmploymentContractUpdate) SetConclusionDate(t time.Time) *EmploymentContractUpdate {
	ecu.mutation.SetConclusionDate(t)
	return ecu
}

// SetNillableConclusionDate sets the "conclusion_date" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableConclusionDate(t *time.Time) *EmploymentContractUpdate {
	if t != nil {
		ecu.SetConclusionDate(*t)
	}
	return ecu
}

// SetOrganizationID sets the "organization_id" field.
func (ecu *EmploymentContractUpdate) SetOrganizationID(i int64) *EmploymentContractUpdate {
	ecu.mutation.ResetOrganizationID()
	ecu.mutation.SetOrganizationID(i)
	return ecu
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableOrganizationID(i *int64) *EmploymentContractUpdate {
	if i != nil {
		ecu.SetOrganizationID(*i)
	}
	return ecu
}

// AddOrganizationID adds i to the "organization_id" field.
func (ecu *EmploymentContractUpdate) AddOrganizationID(i int64) *EmploymentContractUpdate {
	ecu.mutation.AddOrganizationID(i)
	return ecu
}

// SetRepresentativeID sets the "representative_id" field.
func (ecu *EmploymentContractUpdate) SetRepresentativeID(i int64) *EmploymentContractUpdate {
	ecu.mutation.ResetRepresentativeID()
	ecu.mutation.SetRepresentativeID(i)
	return ecu
}

// SetNillableRepresentativeID sets the "representative_id" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableRepresentativeID(i *int64) *EmploymentContractUpdate {
	if i != nil {
		ecu.SetRepresentativeID(*i)
	}
	return ecu
}

// AddRepresentativeID adds i to the "representative_id" field.
func (ecu *EmploymentContractUpdate) AddRepresentativeID(i int64) *EmploymentContractUpdate {
	ecu.mutation.AddRepresentativeID(i)
	return ecu
}

// SetEmployeeID sets the "employee_id" field.
func (ecu *EmploymentContractUpdate) SetEmployeeID(i int64) *EmploymentContractUpdate {
	ecu.mutation.ResetEmployeeID()
	ecu.mutation.SetEmployeeID(i)
	return ecu
}

// SetNillableEmployeeID sets the "employee_id" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableEmployeeID(i *int64) *EmploymentContractUpdate {
	if i != nil {
		ecu.SetEmployeeID(*i)
	}
	return ecu
}

// AddEmployeeID adds i to the "employee_id" field.
func (ecu *EmploymentContractUpdate) AddEmployeeID(i int64) *EmploymentContractUpdate {
	ecu.mutation.AddEmployeeID(i)
	return ecu
}

// SetDepartmentID sets the "department_id" field.
func (ecu *EmploymentContractUpdate) SetDepartmentID(i int64) *EmploymentContractUpdate {
	ecu.mutation.ResetDepartmentID()
	ecu.mutation.SetDepartmentID(i)
	return ecu
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableDepartmentID(i *int64) *EmploymentContractUpdate {
	if i != nil {
		ecu.SetDepartmentID(*i)
	}
	return ecu
}

// AddDepartmentID adds i to the "department_id" field.
func (ecu *EmploymentContractUpdate) AddDepartmentID(i int64) *EmploymentContractUpdate {
	ecu.mutation.AddDepartmentID(i)
	return ecu
}

// SetPositionID sets the "position_id" field.
func (ecu *EmploymentContractUpdate) SetPositionID(i int64) *EmploymentContractUpdate {
	ecu.mutation.ResetPositionID()
	ecu.mutation.SetPositionID(i)
	return ecu
}

// SetNillablePositionID sets the "position_id" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillablePositionID(i *int64) *EmploymentContractUpdate {
	if i != nil {
		ecu.SetPositionID(*i)
	}
	return ecu
}

// AddPositionID adds i to the "position_id" field.
func (ecu *EmploymentContractUpdate) AddPositionID(i int64) *EmploymentContractUpdate {
	ecu.mutation.AddPositionID(i)
	return ecu
}

// SetConditionsClass sets the "conditions_class" field.
func (ecu *EmploymentContractUpdate) SetConditionsClass(i int) *EmploymentContractUpdate {
	ecu.mutation.ResetConditionsClass()
	ecu.mutation.SetConditionsClass(i)
	return ecu
}

// SetNillableConditionsClass sets the "conditions_class" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableConditionsClass(i *int) *EmploymentContractUpdate {
	if i != nil {
		ecu.SetConditionsClass(*i)
	}
	return ecu
}

// AddConditionsClass adds i to the "conditions_class" field.
func (ecu *EmploymentContractUpdate) AddConditionsClass(i int) *EmploymentContractUpdate {
	ecu.mutation.AddConditionsClass(i)
	return ecu
}

// SetWorkDateFrom sets the "work_date_from" field.
func (ecu *EmploymentContractUpdate) SetWorkDateFrom(t time.Time) *EmploymentContractUpdate {
	ecu.mutation.SetWorkDateFrom(t)
	return ecu
}

// SetNillableWorkDateFrom sets the "work_date_from" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableWorkDateFrom(t *time.Time) *EmploymentContractUpdate {
	if t != nil {
		ecu.SetWorkDateFrom(*t)
	}
	return ecu
}

// SetWorkDateTo sets the "work_date_to" field.
func (ecu *EmploymentContractUpdate) SetWorkDateTo(t time.Time) *EmploymentContractUpdate {
	ecu.mutation.SetWorkDateTo(t)
	return ecu
}

// SetNillableWorkDateTo sets the "work_date_to" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableWorkDateTo(t *time.Time) *EmploymentContractUpdate {
	if t != nil {
		ecu.SetWorkDateTo(*t)
	}
	return ecu
}

// ClearWorkDateTo clears the value of the "work_date_to" field.
func (ecu *EmploymentContractUpdate) ClearWorkDateTo() *EmploymentContractUpdate {
	ecu.mutation.ClearWorkDateTo()
	return ecu
}

// SetProbationMonths sets the "probation_months" field.
func (ecu *EmploymentContractUpdate) SetProbationMonths(i int) *EmploymentContractUpdate {
	ecu.mutation.ResetProbationMonths()
	ecu.mutation.SetProbationMonths(i)
	return ecu
}

// SetNillableProbationMonths sets the "probation_months" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableProbationMonths(i *int) *EmploymentContractUpdate {
	if i != nil {
		ecu.SetProbationMonths(*i)
	}
	return ecu
}

// AddProbationMonths adds i to the "probation_months" field.
func (ecu *EmploymentContractUpdate) AddProbationMonths(i int) *EmploymentContractUpdate {
	ecu.mutation.AddProbationMonths(i)
	return ecu
}

// ClearProbationMonths clears the value of the "probation_months" field.
func (ecu *EmploymentContractUpdate) ClearProbationMonths() *EmploymentContractUpdate {
	ecu.mutation.ClearProbationMonths()
	return ecu
}

// SetSalary sets the "salary" field.
func (ecu *EmploymentContractUpdate) SetSalary(f float64) *EmploymentContractUpdate {
	ecu.mutation.ResetSalary()
	ecu.mutation.SetSalary(f)
	return ecu
}

// SetNillableSalary sets the "salary" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableSalary(f *float64) *EmploymentContractUpdate {
	if f != nil {
		ecu.SetSalary(*f)
	}
	return ecu
}

// AddSalary adds f to the "salary" field.
func (ecu *EmploymentContractUpdate) AddSalary(f float64) *EmploymentContractUpdate {
	ecu.mutation.AddSalary(f)
	return ecu
}

// SetWorkHoursFrom sets the "work_hours_from" field.
func (ecu *EmploymentContractUpdate) SetWorkHoursFrom(t time.Time) *EmploymentContractUpdate {
	ecu.mutation.SetWorkHoursFrom(t)
	return ecu
}

// SetNillableWorkHoursFrom sets the "work_hours_from" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableWorkHoursFrom(t *time.Time) *EmploymentContractUpdate {
	if t != nil {
		ecu.SetWorkHoursFrom(*t)
	}
	return ecu
}

// SetWorkHoursTo sets the "work_hours_to" field.
func (ecu *EmploymentContractUpdate) SetWorkHoursTo(t time.Time) *EmploymentContractUpdate {
	ecu.mutation.SetWorkHoursTo(t)
	return ecu
}

// SetNillableWorkHoursTo sets the "work_hours_to" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableWorkHoursTo(t *time.Time) *EmploymentContractUpdate {
	if t != nil {
		ecu.SetWorkHoursTo(*t)
	}
	return ecu
}

// SetBreakFrom sets the "break_from" field.
func (ecu *EmploymentContractUpdate) SetBreakFrom(t time.Time) *EmploymentContractUpdate {
	ecu.mutation.SetBreakFrom(t)
	return ecu
}

// SetNillableBreakFrom sets the "break_from" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableBreakFrom(t *time.Time) *EmploymentContractUpdate {
	if t != nil {
		ecu.SetBreakFrom(*t)
	}
	return ecu
}

// ClearBreakFrom clears the value of the "break_from" field.
func (ecu *EmploymentContractUpdate) ClearBreakFrom() *EmploymentContractUpdate {
	ecu.mutation.ClearBreakFrom()
	return ecu
}

// SetBreakTo sets the "break_to" field.
func (ecu *EmploymentContractUpdate) SetBreakTo(t time.Time) *EmploymentContractUpdate {
	ecu.mutation.SetBreakTo(t)
	return ecu
}

// SetNillableBreakTo sets the "break_to" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableBreakTo(t *time.Time) *EmploymentContractUpdate {
	if t != nil {
		ecu.SetBreakTo(*t)
	}
	return ecu
}

// ClearBreakTo clears the value of the "break_to" field.
func (ecu *EmploymentContractUpdate) ClearBreakTo() *EmploymentContractUpdate {
	ecu.mutation.ClearBreakTo()
	return ecu
}

// SetPaidLeaveDays sets the "paid_leave_days" field.
func (ecu *EmploymentContractUpdate) SetPaidLeaveDays(i int) *EmploymentContractUpdate {
	ecu.mutation.ResetPaidLeaveDays()
	ecu.mutation.SetPaidLeaveDays(i)
	return ecu
}

// SetNillablePaidLeaveDays sets the "paid_leave_days" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillablePaidLeaveDays(i *int) *EmploymentContractUpdate {
	if i != nil {
		ecu.SetPaidLeaveDays(*i)
	}
	return ecu
}

// AddPaidLeaveDays adds i to the "paid_leave_days" field.
func (ecu *EmploymentContractUpdate) AddPaidLeaveDays(i int) *EmploymentContractUpdate {
	ecu.mutation.AddPaidLeaveDays(i)
	return ecu
}

// SetCreatedAt sets the "created_at" field.
func (ecu *EmploymentContractUpdate) SetCreatedAt(t time.Time) *EmploymentContractUpdate {
	ecu.mutation.SetCreatedAt(t)
	return ecu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ecu *EmploymentContractUpdate) SetNillableCreatedAt(t *time.Time) *EmploymentContractUpdate {
	if t != nil {
		ecu.SetCreatedAt(*t)
	}
	return ecu
}

// SetUpdatedAt sets the "updated_at" field.
func (ecu *EmploymentContractUpdate) SetUpdatedAt(t time.Time) *EmploymentContractUpdate {
	ecu.mutation.SetUpdatedAt(t)
	return ecu
}

// Mutation returns the EmploymentContractMutation object of the builder.
func (ecu *EmploymentContractUpdate) Mutation() *EmploymentContractMutation {
	return ecu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ecu *EmploymentContractUpdate) Save(ctx context.Context) (int, error) {
	ecu.defaults()
	return withHooks(ctx, ecu.sqlSave, ecu.mutation, ecu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ecu *EmploymentContractUpdate) SaveX(ctx context.Context) int {
	affected, err := ecu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ecu *EmploymentContractUpdate) Exec(ctx context.Context) error {
	_, err := ecu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecu *EmploymentContractUpdate) ExecX(ctx context.Context) {
	if err := ecu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ecu *EmploymentContractUpdate) defaults() {
	if _, ok := ecu.mutation.UpdatedAt(); !ok {
		v := employmentcontract.UpdateDefaultUpdatedAt()
		ecu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ecu *EmploymentContractUpdate) check() error {
	if v, ok := ecu.mutation.Number(); ok {
		if err := employmentcontract.NumberValidator(v); err != nil {
			return &ValidationError{Name: "number", err: fmt.Errorf(`ent: validator failed for field "EmploymentContract.number": %w`, err)}
		}
	}
	if v, ok := ecu.mutation.PersonnelNumber(); ok {
		if err := employmentcontract.PersonnelNumberValidator(v); err != nil {
			return &ValidationError{Name: "personnel_number", err: fmt.Errorf(`ent: validator failed for field "EmploymentContract.personnel_number": %w`, err)}
		}
	}
	return nil
}

func (ecu *EmploymentContractUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ecu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(employmentcontract.Table, employmentcontract.Columns, sqlgraph.NewFieldSpec(employmentcontract.FieldID, field.TypeInt64))
	if ps := ecu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ecu.mutation.Number(); ok {
		_spec.SetField(employmentcontract.FieldNumber, field.TypeString, value)
	}
	if value, ok := ecu.mutation.PersonnelNumber(); ok {
		_spec.SetField(employmentcontract.FieldPersonnelNumber, field.TypeString, value)
	}
	if value, ok := ecu.mutation.ConclusionDate(); ok {
		_spec.SetField(employmentcontract.FieldConclusionDate, field.TypeTime, value)
	}
	if value, ok := ecu.mutation.OrganizationID(); ok {
		_spec.SetField(employmentcontract.FieldOrganizationID, field.TypeInt64, value)
	}
	if value, ok := ecu.mutation.AddedOrganizationID(); ok {
		_spec.AddField(employmentcontract.FieldOrganizationID, field.TypeInt64, value)
	}
	if value, ok := ecu.mutation.RepresentativeID(); ok {
		_spec.SetField(employmentcontract.FieldRepresentativeID, field.TypeInt64, value)
	}
	if value, ok := ecu.mutation.AddedRepresentativeID(); ok {
		_spec.AddField(employmentcontract.FieldRepresentativeID, field.TypeInt64, value)
	}
	if value, ok := ecu.mutation.EmployeeID(); ok {
		_spec.SetField(employmentcontract.FieldEmployeeID, field.TypeInt64, value)
	}
	if value, ok := ecu.mutation.AddedEmployeeID(); ok {
		_spec.AddField(employmentcontract.FieldEmployeeID, field.TypeInt64, value)
	}
	if value, ok := ecu.mutation.DepartmentID(); ok {
		_spec.SetField(employmentcontract.FieldDepartmentID, field.TypeInt64, value)
	}
	if value, ok := ecu.mutation.AddedDepartmentID(); ok {
		_spec.AddField(employmentcontract.FieldDepartmentID, field.TypeInt64, value)
	}
	if value, ok := ecu.mutation.PositionID(); ok {
		_spec.SetField(employmentcontract.FieldPositionID, field.TypeInt64, value)
	}
	if value, ok := ecu.mutation.AddedPositionID(); ok {
		_spec.AddField(employmentcontract.FieldPositionID, field.TypeInt64, value)
	}
	if value, ok := ecu.mutation.ConditionsClass(); ok {
		_spec.SetField(employmentcontract.FieldConditionsClass, field.TypeInt, value)
	}
	if value, ok := ecu.mutation.AddedConditionsClass(); ok {
		_spec.AddField(employmentcontract.FieldConditionsClass, field.TypeInt, value)
	}
	if value, ok := ecu.mutation.WorkDateFrom(); ok {
		_spec.SetField(employmentcontract.FieldWorkDateFrom, field.TypeTime, value)
	}
	if value, ok := ecu.mutation.WorkDateTo(); ok {
		_spec.SetField(employmentcontract.FieldWorkDateTo, field.TypeTime, value)
	}
	if ecu.mutation.WorkDateToCleared() {
		_spec.ClearField(employmentcontract.FieldWorkDateTo, field.TypeTime)
	}
	if value, ok := ecu.mutation.ProbationMonths(); ok {
		_spec.SetField(employmentcontract.FieldProbationMonths, field.TypeInt, value)
	}
	if value, ok := ecu.mutation.AddedProbationMonths(); ok {
		_spec.AddField(employmentcontract.FieldProbationMonths, field.TypeInt, value)
	}
	if ecu.mutation.ProbationMonthsCleared() {
		_spec.ClearField(employmentcontract.FieldProbationMonths, field.TypeInt)
	}
	if value, ok := ecu.mutation.Salary(); ok {
		_spec.SetField(employmentcontract.FieldSalary, field.TypeFloat64, value)
	}
	if value, ok := ecu.mutation.AddedSalary(); ok {
		_spec.AddField(employmentcontract.FieldSalary, field.TypeFloat64, value)
	}
	if value, ok := ecu.mutation.WorkHoursFrom(); ok {
		_spec.SetField(employmentcontract.FieldWorkHoursFrom, field.TypeTime, value)
	}
	if value, ok := ecu.mutation.WorkHoursTo(); ok {
		_spec.SetField(employmentcontract.FieldWorkHoursTo, field.TypeTime, value)
	}
	if value, ok := ecu.mutation.BreakFrom(); ok {
		_spec.SetField(employmentcontract.FieldBreakFrom, field.TypeTime, value)
	}
	if ecu.mutation.BreakFromCleared() {
		_spec.ClearField(employmentcontract.FieldBreakFrom, field.TypeTime)
	}
	if value, ok := ecu.mutation.BreakTo(); ok {
		_spec.SetField(employmentcontract.FieldBreakTo, field.TypeTime, value)
	}
	if ecu.mutation.BreakToCleared() {
		_spec.ClearField(employmentcontract.FieldBreakTo, field.TypeTime)
	}
	if value, ok := ecu.mutation.PaidLeaveDays(); ok {
		_spec.SetField(employmentcontract.FieldPaidLeaveDays, field.TypeInt, value)
	}
	if value, ok := ecu.mutation.AddedPaidLeaveDays(); ok {
		_spec.AddField(employmentcontract.FieldPaidLeaveDays, field.TypeInt, value)
	}
	if value, ok := ecu.mutation.CreatedAt(); ok {
		_spec.SetField(employmentcontract.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := ecu.mutation.UpdatedAt(); ok {
		_spec.SetField(employmentcontract.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ecu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employmentcontract.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ecu.mutation.done = true
	return n, nil
}

// EmploymentContractUpdateOne is the builder for updating a single EmploymentContract entity.
type EmploymentContractUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmploymentContractMutation
}

// SetNumber sets the "number" field.
func (ecuo *EmploymentContractUpdateOne) SetNumber(s string) *EmploymentContractUpdateOne {
	ecuo.mutation.SetNumber(s)
	return ecuo
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableNumber(s *string) *EmploymentContractUpdateOne {
	if s != nil {
		ecuo.SetNumber(*s)
	}
	return ecuo
}

// SetPersonnelNumber sets the "personnel_number" field.
func (ecuo *EmploymentContractUpdateOne) SetPersonnelNumber(s string) *EmploymentContractUpdateOne {
	ecuo.mutation.SetPersonnelNumber(s)
	return ecuo
}

// SetNillablePersonnelNumber sets the "personnel_number" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillablePersonnelNumber(s *string) *EmploymentContractUpdateOne {
	if s != nil {
		ecuo.SetPersonnelNumber(*s)
	}
	return ecuo
}

// SetConclusionDate sets the "conclusion_date" field.
func (ecuo *EmploymentContractUpdateOne) SetConclusionDate(t time.Time) *EmploymentContractUpdateOne {
	ecuo.mutation.SetConclusionDate(t)
	return ecuo
}

// SetNillableConclusionDate sets the "conclusion_date" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableConclusionDate(t *time.Time) *EmploymentContractUpdateOne {
	if t != nil {
		ecuo.SetConclusionDate(*t)
	}
	return ecuo
}

// SetOrganizationID sets the "organization_id" field.
func (ecuo *EmploymentContractUpdateOne) SetOrganizationID(i int64) *EmploymentContractUpdateOne {
	ecuo.mutation.ResetOrganizationID()
	ecuo.mutation.SetOrganizationID(i)
	return ecuo
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableOrganizationID(i *int64) *EmploymentContractUpdateOne {
	if i != nil {
		ecuo.SetOrganizationID(*i)
	}
	return ecuo
}

// AddOrganizationID adds i to the "organization_id" field.
func (ecuo *EmploymentContractUpdateOne) AddOrganizationID(i int64) *EmploymentContractUpdateOne {
	ecuo.mutation.AddOrganizationID(i)
	return ecuo
}

// SetRepresentativeID sets the "representative_id" field.
func (ecuo *EmploymentContractUpdateOne) SetRepresentativeID(i int64) *EmploymentContractUpdateOne {
	ecuo.mutation.ResetRepresentativeID()
	ecuo.mutation.SetRepresentativeID(i)
	return ecuo
}

// SetNillableRepresentativeID sets the "representative_id" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableRepresentativeID(i *int64) *EmploymentContractUpdateOne {
	if i != nil {
		ecuo.SetRepresentativeID(*i)
	}
	return ecuo
}

// AddRepresentativeID adds i to the "representative_id" field.
func (ecuo *EmploymentContractUpdateOne) AddRepresentativeID(i int64) *EmploymentContractUpdateOne {
	ecuo.mutation.AddRepresentativeID(i)
	return ecuo
}

// SetEmployeeID sets the "employee_id" field.
func (ecuo *EmploymentContractUpdateOne) SetEmployeeID(i int64) *EmploymentContractUpdateOne {
	ecuo.mutation.ResetEmployeeID()
	ecuo.mutation.SetEmployeeID(i)
	return ecuo
}

// SetNillableEmployeeID sets the "employee_id" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableEmployeeID(i *int64) *EmploymentContractUpdateOne {
	if i != nil {
		ecuo.SetEmployeeID(*i)
	}
	return ecuo
}

// AddEmployeeID adds i to the "employee_id" field.
func (ecuo *EmploymentContractUpdateOne) AddEmployeeID(i int64) *EmploymentContractUpdateOne {
	ecuo.mutation.AddEmployeeID(i)
	return ecuo
}

// SetDepartmentID sets the "department_id" field.
func (ecuo *EmploymentContractUpdateOne) SetDepartmentID(i int64) *EmploymentContractUpdateOne {
	ecuo.mutation.ResetDepartmentID()
	ecuo.mutation.SetDepartmentID(i)
	return ecuo
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableDepartmentID(i *int64) *EmploymentContractUpdateOne {
	if i != nil {
		ecuo.SetDepartmentID(*i)
	}
	return ecuo
}

// AddDepartmentID adds i to the "department_id" field.
func (ecuo *EmploymentContractUpdateOne) AddDepartmentID(i int64) *EmploymentContractUpdateOne {
	ecuo.mutation.AddDepartmentID(i)
	return ecuo
}

// SetPositionID sets the "position_id" field.
func (ecuo *EmploymentContractUpdateOne) SetPositionID(i int64) *EmploymentContractUpdateOne {
	ecuo.mutation.ResetPositionID()
	ecuo.mutation.SetPositionID(i)
	return ecuo
}

// SetNillablePositionID sets the "position_id" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillablePositionID(i *int64) *EmploymentContractUpdateOne {
	if i != nil {
		ecuo.SetPositionID(*i)
	}
	return ecuo
}

// AddPositionID adds i to the "position_id" field.
func (ecuo *EmploymentContractUpdateOne) AddPositionID(i int64) *EmploymentContractUpdateOne {
	ecuo.mutation.AddPositionID(i)
	return ecuo
}

// SetConditionsClass sets the "conditions_class" field.
func (ecuo *EmploymentContractUpdateOne) SetConditionsClass(i int) *EmploymentContractUpdateOne {
	ecuo.mutation.ResetConditionsClass()
	ecuo.mutation.SetConditionsClass(i)
	return ecuo
}

// SetNillableConditionsClass sets the "conditions_class" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableConditionsClass(i *int) *EmploymentContractUpdateOne {
	if i != nil {
		ecuo.SetConditionsClass(*i)
	}
	return ecuo
}

// AddConditionsClass adds i to the "conditions_class" field.
func (ecuo *EmploymentContractUpdateOne) AddConditionsClass(i int) *EmploymentContractUpdateOne {
	ecuo.mutation.AddConditionsClass(i)
	return ecuo
}

// SetWorkDateFrom sets the "work_date_from" field.
func (ecuo *EmploymentContractUpdateOne) SetWorkDateFrom(t time.Time) *EmploymentContractUpdateOne {
	ecuo.mutation.SetWorkDateFrom(t)
	return ecuo
}

// SetNillableWorkDateFrom sets the "work_date_from" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableWorkDateFrom(t *time.Time) *EmploymentContractUpdateOne {
	if t != nil {
		ecuo.SetWorkDateFrom(*t)
	}
	return ecuo
}

// SetWorkDateTo sets the "work_date_to" field.
func (ecuo *EmploymentContractUpdateOne) SetWorkDateTo(t time.Time) *EmploymentContractUpdateOne {
	ecuo.mutation.SetWorkDateTo(t)
	return ecuo
}

// SetNillableWorkDateTo sets the "work_date_to" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableWorkDateTo(t *time.Time) *EmploymentContractUpdateOne {
	if t != nil {
		ecuo.SetWorkDateTo(*t)
	}
	return ecuo
}

// ClearWorkDateTo clears the value of the "work_date_to" field.
func (ecuo *EmploymentContractUpdateOne) ClearWorkDateTo() *EmploymentContractUpdateOne {
	ecuo.mutation.ClearWorkDateTo()
	return ecuo
}

// SetProbationMonths sets the "probation_months" field.
func (ecuo *EmploymentContractUpdateOne) SetProbationMonths(i int) *EmploymentContractUpdateOne {
	ecuo.mutation.ResetProbationMonths()
	ecuo.mutation.SetProbationMonths(i)
	return ecuo
}

// SetNillableProbationMonths sets the "probation_months" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableProbationMonths(i *int) *EmploymentContractUpdateOne {
	if i != nil {
		ecuo.SetProbationMonths(*i)
	}
	return ecuo
}

// AddProbationMonths adds i to the "probation_months" field.
func (ecuo *EmploymentContractUpdateOne) AddProbationMonths(i int) *EmploymentContractUpdateOne {
	ecuo.mutation.AddProbationMonths(i)
	return ecuo
}

// ClearProbationMonths clears the value of the "probation_months" field.
func (ecuo *EmploymentContractUpdateOne) ClearProbationMonths() *EmploymentContractUpdateOne {
	ecuo.mutation.ClearProbationMonths()
	return ecuo
}

// SetSalary sets the "salary" field.
func (ecuo *EmploymentContractUpdateOne) SetSalary(f float64) *EmploymentContractUpdateOne {
	ecuo.mutation.ResetSalary()
	ecuo.mutation.SetSalary(f)
	return ecuo
}

// SetNillableSalary sets the "salary" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableSalary(f *float64) *EmploymentContractUpdateOne {
	if f != nil {
		ecuo.SetSalary(*f)
	}
	return ecuo
}

// AddSalary adds f to the "salary" field.
func (ecuo *EmploymentContractUpdateOne) AddSalary(f float64) *EmploymentContractUpdateOne {
	ecuo.mutation.AddSalary(f)
	return ecuo
}

// SetWorkHoursFrom sets the "work_hours_from" field.
func (ecuo *EmploymentContractUpdateOne) SetWorkHoursFrom(t time.Time) *EmploymentContractUpdateOne {
	ecuo.mutation.SetWorkHoursFrom(t)
	return ecuo
}

// SetNillableWorkHoursFrom sets the "work_hours_from" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableWorkHoursFrom(t *time.Time) *EmploymentContractUpdateOne {
	if t != nil {
		ecuo.SetWorkHoursFrom(*t)
	}
	return ecuo
}

// SetWorkHoursTo sets the "work_hours_to" field.
func (ecuo *EmploymentContractUpdateOne) SetWorkHoursTo(t time.Time) *EmploymentContractUpdateOne {
	ecuo.mutation.SetWorkHoursTo(t)
	return ecuo
}

// SetNillableWorkHoursTo sets the "work_hours_to" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableWorkHoursTo(t *time.Time) *EmploymentContractUpdateOne {
	if t != nil {
		ecuo.SetWorkHoursTo(*t)
	}
	return ecuo
}

// SetBreakFrom sets the "break_from" field.
func (ecuo *EmploymentContractUpdateOne) SetBreakFrom(t time.Time) *EmploymentContractUpdateOne {
	ecuo.mutation.SetBreakFrom(t)
	return ecuo
}

// SetNillableBreakFrom sets the "break_from" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableBreakFrom(t *time.Time) *EmploymentContractUpdateOne {
	if t != nil {
		ecuo.SetBreakFrom(*t)
	}
	return ecuo
}

// ClearBreakFrom clears the value of the "break_from" field.
func (ecuo *EmploymentContractUpdateOne) ClearBreakFrom() *EmploymentContractUpdateOne {
	ecuo.mutation.ClearBreakFrom()
	return ecuo
}

// SetBreakTo sets the "break_to" field.
func (ecuo *EmploymentContractUpdateOne) SetBreakTo(t time.Time) *EmploymentContractUpdateOne {
	ecuo.mutation.SetBreakTo(t)
	return ecuo
}

// SetNillableBreakTo sets the "break_to" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableBreakTo(t *time.Time) *EmploymentContractUpdateOne {
	if t != nil {
		ecuo.SetBreakTo(*t)
	}
	return ecuo
}

// ClearBreakTo clears the value of the "break_to" field.
func (ecuo *EmploymentContractUpdateOne) ClearBreakTo() *EmploymentContractUpdateOne {
	ecuo.mutation.ClearBreakTo()
	return ecuo
}

// SetPaidLeaveDays sets the "paid_leave_days" field.
func (ecuo *EmploymentContractUpdateOne) SetPaidLeaveDays(i int) *EmploymentContractUpdateOne {
	ecuo.mutation.ResetPaidLeaveDays()
	ecuo.mutation.SetPaidLeaveDays(i)
	return ecuo
}

// SetNillablePaidLeaveDays sets the "paid_leave_days" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillablePaidLeaveDays(i *int) *EmploymentContractUpdateOne {
	if i != nil {
		ecuo.SetPaidLeaveDays(*i)
	}
	return ecuo
}

// AddPaidLeaveDays adds i to the "paid_leave_days" field.
func (ecuo *EmploymentContractUpdateOne) AddPaidLeaveDays(i int) *EmploymentContractUpdateOne {
	ecuo.mutation.AddPaidLeaveDays(i)
	return ecuo
}

// SetCreatedAt sets the "created_at" field.
func (ecuo *EmploymentContractUpdateOne) SetCreatedAt(t time.Time) *EmploymentContractUpdateOne {
	ecuo.mutation.SetCreatedAt(t)
	return ecuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ecuo *EmploymentContractUpdateOne) SetNillableCreatedAt(t *time.Time) *EmploymentContractUpdateOne {
	if t != nil {
		ecuo.SetCreatedAt(*t)
	}
	return ecuo
}

// SetUpdatedAt sets the "updated_at" field.
func (ecuo *EmploymentContractUpdateOne) SetUpdatedAt(t time.Time) *EmploymentContractUpdateOne {
	ecuo.mutation.SetUpdatedAt(t)
	return ecuo
}

// Mutation returns the EmploymentContractMutation object of the builder.
func (ecuo *EmploymentContractUpdateOne) Mutation() *EmploymentContractMutation {
	return ecuo.mutation
}

// Where appends a list predicates to the EmploymentContractUpdate builder.
func (ecuo *EmploymentContractUpdateOne) Where(ps ...predicate.EmploymentContract) *EmploymentContractUpdateOne {
	ecuo.mutation.Where(ps...)
	return ecuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ecuo *EmploymentContractUpdateOne) Select(field string, fields ...string) *EmploymentContractUpdateOne {
	ecuo.fields = append([]string{field}, fields...)
	return ecuo
}

// Save executes the query and returns the updated EmploymentContract entity.
func (ecuo *EmploymentContractUpdateOne) Save(ctx context.Context) (*EmploymentContract, error) {
	ecuo.defaults()
	return withHooks(ctx, ecuo.sqlSave, ecuo.mutation, ecuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ecuo *EmploymentContractUpdateOne) SaveX(ctx context.Context) *EmploymentContract {
	node, err := ecuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ecuo *EmploymentContractUpdateOne) Exec(ctx context.Context) error {
	_, err := ecuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecuo *EmploymentContractUpdateOne) ExecX(ctx context.Context) {
	if err := ecuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ecuo *EmploymentContractUpdateOne) defaults() {
	if _, ok := ecuo.mutation.UpdatedAt(); !ok {
		v := employmentcontract.UpdateDefaultUpdatedAt()
		ecuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ecuo *EmploymentContractUpdateOne) check() error {
	if v, ok := ecuo.mutation.Number(); ok {
		if err := employmentcontract.NumberValidator(v); err != nil {
			return &ValidationError{Name: "number", err: fmt.Errorf(`ent: validator failed for field "EmploymentContract.number": %w`, err)}
		}
	}
	if v, ok := ecuo.mutation.PersonnelNumber(); ok {
		if err := employmentcontract.PersonnelNumberValidator(v); err != nil {
			return &ValidationError{Name: "personnel_number", err: fmt.Errorf(`ent: validator failed for field "EmploymentContract.personnel_number": %w`, err)}
		}
	}
	return nil
}

func (ecuo *EmploymentContractUpdateOne) sqlSave(ctx context.Context) (_node *EmploymentContract, err error) {
	if err := ecuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(employmentcontract.Table, employmentcontract.Columns, sqlgraph.NewFieldSpec(employmentcontract.FieldID, field.TypeInt64))
	id, ok := ecuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmploymentContract.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ecuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, employmentcontract.FieldID)
		for _, f := range fields {
			if !employmentcontract.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != employmentcontract.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ecuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ecuo.mutation.Number(); ok {
		_spec.SetField(employmentcontract.FieldNumber, field.TypeString, value)
	}
	if value, ok := ecuo.mutation.PersonnelNumber(); ok {
		_spec.SetField(employmentcontract.FieldPersonnelNumber, field.TypeString, value)
	}
	if value, ok := ecuo.mutation.ConclusionDate(); ok {
		_spec.SetField(employmentcontract.FieldConclusionDate, field.TypeTime, value)
	}
	if value, ok := ecuo.mutation.OrganizationID(); ok {
		_spec.SetField(employmentcontract.FieldOrganizationID, field.TypeInt64, value)
	}
	if value, ok := ecuo.mutation.AddedOrganizationID(); ok {
		_spec.AddField(employmentcontract.FieldOrganizationID, field.TypeInt64, value)
	}
	if value, ok := ecuo.mutation.RepresentativeID(); ok {
		_spec.SetField(employmentcontract.FieldRepresentativeID, field.TypeInt64, value)
	}
	if value, ok := ecuo.mutation.AddedRepresentativeID(); ok {
		_spec.AddField(employmentcontract.FieldRepresentativeID, field.TypeInt64, value)
	}
	if value, ok := ecuo.mutation.EmployeeID(); ok {
		_spec.SetField(employmentcontract.FieldEmployeeID, field.TypeInt64, value)
	}
	if value, ok := ecuo.mutation.AddedEmployeeID(); ok {
		_spec.AddField(employmentcontract.FieldEmployeeID, field.TypeInt64, value)
	}
	if value, ok := ecuo.mutation.DepartmentID(); ok {
		_spec.SetField(employmentcontract.FieldDepartmentID, field.TypeInt64, value)
	}
	if value, ok := ecuo.mutation.AddedDepartmentID(); ok {
		_spec.AddField(employmentcontract.FieldDepartmentID, field.TypeInt64, value)
	}
	if value, ok := ecuo.mutation.PositionID(); ok {
		_spec.SetField(employmentcontract.FieldPositionID, field.TypeInt64, value)
	}
	if value, ok := ecuo.mutation.AddedPositionID(); ok {
		_spec.AddField(employmentcontract.FieldPositionID, field.TypeInt64, value)
	}
	if value, ok := ecuo.mutation.ConditionsClass(); ok {
		_spec.SetField(employmentcontract.FieldConditionsClass, field.TypeInt, value)
	}
	if value, ok := ecuo.mutation.AddedConditionsClass(); ok {
		_spec.AddField(employmentcontract.FieldConditionsClass, field.TypeInt, value)
	}
	if value, ok := ecuo.mutation.WorkDateFrom(); ok {
		_spec.SetField(employmentcontract.FieldWorkDateFrom, field.TypeTime, value)
	}
	if value, ok := ecuo.mutation.WorkDateTo(); ok {
		_spec.SetField(employmentcontract.FieldWorkDateTo, field.TypeTime, value)
	}
	if ecuo.mutation.WorkDateToCleared() {
		_spec.ClearField(employmentcontract.FieldWorkDateTo, field.TypeTime)
	}
	if value, ok := ecuo.mutation.ProbationMonths(); ok {
		_spec.SetField(employmentcontract.FieldProbationMonths, field.TypeInt, value)
	}
	if value, ok := ecuo.mutation.AddedProbationMonths(); ok {
		_spec.AddField(employmentcontract.FieldProbationMonths, field.TypeInt, value)
	}
	if ecuo.mutation.ProbationMonthsCleared() {
		_spec.ClearField(employmentcontract.FieldProbationMonths, field.TypeInt)
	}
	if value, ok := ecuo.mutation.Salary(); ok {
		_spec.SetField(employmentcontract.FieldSalary, field.TypeFloat64, value)
	}
	if value, ok := ecuo.mutation.AddedSalary(); ok {
		_spec.AddField(employmentcontract.FieldSalary, field.TypeFloat64, value)
	}
	if value, ok := ecuo.mutation.WorkHoursFrom(); ok {
		_spec.SetField(employmentcontract.FieldWorkHoursFrom, field.TypeTime, value)
	}
	if value, ok := ecuo.mutation.WorkHoursTo(); ok {
		_spec.SetField(employmentcontract.FieldWorkHoursTo, field.TypeTime, value)
	}
	if value, ok := ecuo.mutation.BreakFrom(); ok {
		_spec.SetField(employmentcontract.FieldBreakFrom, field.TypeTime, value)
	}
	if ecuo.mutation.BreakFromCleared() {
		_spec.ClearField(employmentcontract.FieldBreakFrom, field.TypeTime)
	}
	if value, ok := ecuo.mutation.BreakTo(); ok {
		_spec.SetField(employmentcontract.FieldBreakTo, field.TypeTime, value)
	}
	if ecuo.mutation.BreakToCleared() {
		_spec.ClearField(employmentcontract.FieldBreakTo, field.TypeTime)
	}
	if value, ok := ecuo.mutation.PaidLeaveDays(); ok {
		_spec.SetField(employmentcontract.FieldPaidLeaveDays, field.TypeInt, value)
	}
	if value, ok := ecuo.mutation.AddedPaidLeaveDays(); ok {
		_spec.AddField(employmentcontract.FieldPaidLeaveDays, field.TypeInt, value)
	}
	if value, ok := ecuo.mutation.CreatedAt(); ok {
		_spec.SetField(employmentcontract.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := ecuo.mutation.UpdatedAt(); ok {
		_spec.SetField(employmentcontract.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &EmploymentContract{config: ecuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ecuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employmentcontract.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ecuo.mutation.done = true
	return _node, nil
}
