// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/example/micro/employment-contracts/ent/employmentcontract"
	"github.com/example/micro/employment-contracts/ent/predicate"
)

// EmploymentContractDelete is the builder for deleting a EmploymentContract entity.
type EmploymentContractDelete struct {
	config
	hooks    []Hook
	mutation *EmploymentContractMutation
}

// Where appends a list predicates to the EmploymentContractDelete builder.
func (ecd *EmploymentContractDelete) Where(ps ...predicate.EmploymentContract) *EmploymentContractDelete {
	ecd.mutation.Where(ps...)
	return ecd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ecd *EmploymentContractDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ecd.sqlExec, ecd.mutation, ecd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ecd *EmploymentContractDelete) ExecX(ctx context.Context) int {
	n, err := ecd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ecd *EmploymentContractDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(employmentcontract.Table, sqlgraph.NewFieldSpec(employmentcontract.FieldID, field.TypeInt64))
	if ps := ecd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ecd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ecd.mutation.done = true
	return affected, err
}

// EmploymentContractDeleteOne is the builder for deleting a single EmploymentContract entity.
type EmploymentContractDeleteOne struct {
	ecd *EmploymentContractDelete
}

// Where appends a list predicates to the EmploymentContractDelete builder.
func (ecdo *EmploymentContractDeleteOne) Where(ps ...predicate.EmploymentContract) *EmploymentContractDeleteOne {
	ecdo.ecd.mutation.Where(ps...)
	return ecdo
}

// Exec executes the deletion query.
func (ecdo *EmploymentContractDeleteOne) Exec(ctx context.Context) error {
	n, err := ecdo.ecd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{employmentcontract.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ecdo *EmploymentContractDeleteOne) ExecX(ctx context.Context) {
	if err := ecdo.Exec(ctx); err != nil {
		panic(err)
	}
}
