// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/example/micro/employment-contracts/ent/employmentcontract"
	"github.com/example/micro/employment-contracts/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeEmploymentContract = "EmploymentContract"
)

// EmploymentContractMutation represents an operation that mutates the EmploymentContract nodes in the graph.
type EmploymentContractMutation struct {
	config
	op                   Op
	typ                  string
	id                   *int64
	number               *string
	personnel_number     *string
	conclusion_date      *time.Time
	organization_id      *int64
	addorganization_id   *int64
	representative_id    *int64
	addrepresentative_id *int64
	employee_id          *int64
	addemployee_id       *int64
	department_id        *int64
	adddepartment_id     *int64
	position_id          *int64
	addposition_id       *int64
	conditions_class     *int
	addconditions_class  *int
	work_date_from       *time.Time
	work_date_to         *time.Time
	probation_months     *int
	addprobation_months  *int
	salary               *float64
	addsalary            *float64
	work_hours_from      *time.Time
	work_hours_to        *time.Time
	break_from           *time.Time
	break_to             *time.Time
	paid_leave_days      *int
	addpaid_leave_days   *int
	created_at           *time.Time
	updated_at           *time.Time
	clearedFields        map[string]struct{}
	done                 bool
	oldValue             func(context.Context) (*EmploymentContract, error)
	predicates           []predicate.EmploymentContract
}

var _ ent.Mutation = (*EmploymentContractMutation)(nil)

// employmentcontractOption allows management of the mutation configuration using functional options.
type employmentcontractOption func(*EmploymentContractMutation)

// newEmploymentContractMutation creates new mutation for the EmploymentContract entity.
func newEmploymentContractMutation(c config, op Op, opts ...employmentcontractOption) *EmploymentContractMutation {
	m := &EmploymentContractMutation{
		config:        c,
		op:            op,
		typ:           TypeEmploymentContract,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withEmploymentContractID sets the ID field of the mutation.
func withEmploymentContractID(id int64) employmentcontractOption {
	return func(m *EmploymentContractMutation) {
		var (
			err   error
			once  sync.Once
			value *EmploymentContract
		)
		m.oldValue = func(ctx context.Context) (*EmploymentContract, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().EmploymentContract.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withEmploymentContract sets the old EmploymentContract of the mutation.
func withEmploymentContract(node *EmploymentContract) employmentcontractOption {
	return func(m *EmploymentContractMutation) {
		m.oldValue = func(context.Context) (*EmploymentContract, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m EmploymentContractMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m EmploymentContractMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of EmploymentContract entities.
func (m *EmploymentContractMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *EmploymentContractMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *EmploymentContractMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().EmploymentContract.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetNumber sets the "number" field.
func (m *EmploymentContractMutation) SetNumber(s string) {
	m.number = &s
}

// Number returns the value of the "number" field in the mutation.
func (m *EmploymentContractMutation) Number() (r string, exists bool) {
	v := m.number
	if v == nil {
		return
	}
	return *v, true
}

// OldNumber returns the old "number" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldNumber(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNumber: %w", err)
	}
	return oldValue.Number, nil
}

// ResetNumber resets all changes to the "number" field.
func (m *EmploymentContractMutation) ResetNumber() {
	m.number = nil
}

// SetPersonnelNumber sets the "personnel_number" field.
func (m *EmploymentContractMutation) SetPersonnelNumber(s string) {
	m.personnel_number = &s
}

// PersonnelNumber returns the value of the "personnel_number" field in the mutation.
func (m *EmploymentContractMutation) PersonnelNumber() (r string, exists bool) {
	v := m.personnel_number
	if v == nil {
		return
	}
	return *v, true
}

// OldPersonnelNumber returns the old "personnel_number" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldPersonnelNumber(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPersonnelNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPersonnelNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPersonnelNumber: %w", err)
	}
	return oldValue.PersonnelNumber, nil
}

// ResetPersonnelNumber resets all changes to the "personnel_number" field.
func (m *EmploymentContractMutation) ResetPersonnelNumber() {
	m.personnel_number = nil
}

// SetConclusionDate sets the "conclusion_date" field.
func (m *EmploymentContractMutation) SetConclusionDate(t time.Time) {
	m.conclusion_date = &t
}

// ConclusionDate returns the value of the "conclusion_date" field in the mutation.
func (m *EmploymentContractMutation) ConclusionDate() (r time.Time, exists bool) {
	v := m.conclusion_date
	if v == nil {
		return
	}
	return *v, true
}

// OldConclusionDate returns the old "conclusion_date" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldConclusionDate(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldConclusionDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldConclusionDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldConclusionDate: %w", err)
	}
	return oldValue.ConclusionDate, nil
}

// ResetConclusionDate resets all changes to the "conclusion_date" field.
func (m *EmploymentContractMutation) ResetConclusionDate() {
	m.conclusion_date = nil
}

// SetOrganizationID sets the "organization_id" field.
func (m *EmploymentContractMutation) SetOrganizationID(i int64) {
	m.organization_id = &i
	m.addorganization_id = nil
}

// OrganizationID returns the value of the "organization_id" field in the mutation.
func (m *EmploymentContractMutation) OrganizationID() (r int64, exists bool) {
	v := m.organization_id
	if v == nil {
		return
	}
	return *v, true
}

// OldOrganizationID returns the old "organization_id" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldOrganizationID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOrganizationID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOrganizationID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOrganizationID: %w", err)
	}
	return oldValue.OrganizationID, nil
}

// AddOrganizationID adds i to the "organization_id" field.
func (m *EmploymentContractMutation) AddOrganizationID(i int64) {
	if m.addorganization_id != nil {
		*m.addorganization_id += i
	} else {
		m.addorganization_id = &i
	}
}

// AddedOrganizationID returns the value that was added to the "organization_id" field in this mutation.
func (m *EmploymentContractMutation) AddedOrganizationID() (r int64, exists bool) {
	v := m.addorganization_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetOrganizationID resets all changes to the "organization_id" field.
func (m *EmploymentContractMutation) ResetOrganizationID() {
	m.organization_id = nil
	m.addorganization_id = nil
}

// SetRepresentativeID sets the "representative_id" field.
func (m *EmploymentContractMutation) SetRepresentativeID(i int64) {
	m.representative_id = &i
	m.addrepresentative_id = nil
}

// RepresentativeID returns the value of the "representative_id" field in the mutation.
func (m *EmploymentContractMutation) RepresentativeID() (r int64, exists bool) {
	v := m.representative_id
	if v == nil {
		return
	}
	return *v, true
}

// OldRepresentativeID returns the old "representative_id" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldRepresentativeID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRepresentativeID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRepresentativeID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRepresentativeID: %w", err)
	}
	return oldValue.RepresentativeID, nil
}

// AddRepresentativeID adds i to the "representative_id" field.
func (m *EmploymentContractMutation) AddRepresentativeID(i int64) {
	if m.addrepresentative_id != nil {
		*m.addrepresentative_id += i
	} else {
		m.addrepresentative_id = &i
	}
}

// AddedRepresentativeID returns the value that was added to the "representative_id" field in this mutation.
func (m *EmploymentContractMutation) AddedRepresentativeID() (r int64, exists bool) {
	v := m.addrepresentative_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetRepresentativeID resets all changes to the "representative_id" field.
func (m *EmploymentContractMutation) ResetRepresentativeID() {
	m.representative_id = nil
	m.addrepresentative_id = nil
}

// SetEmployeeID sets the "employee_id" field.
func (m *EmploymentContractMutation) SetEmployeeID(i int64) {
	m.employee_id = &i
	m.addemployee_id = nil
}

// EmployeeID returns the value of the "employee_id" field in the mutation.
func (m *EmploymentContractMutation) EmployeeID() (r int64, exists bool) {
	v := m.employee_id
	if v == nil {
		return
	}
	return *v, true
}

// OldEmployeeID returns the old "employee_id" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldEmployeeID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmployeeID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmployeeID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmployeeID: %w", err)
	}
	return oldValue.EmployeeID, nil
}

// AddEmployeeID adds i to the "employee_id" field.
func (m *EmploymentContractMutation) AddEmployeeID(i int64) {
	if m.addemployee_id != nil {
		*m.addemployee_id += i
	} else {
		m.addemployee_id = &i
	}
}

// AddedEmployeeID returns the value that was added to the "employee_id" field in this mutation.
func (m *EmploymentContractMutation) AddedEmployeeID() (r int64, exists bool) {
	v := m.addemployee_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetEmployeeID resets all changes to the "employee_id" field.
func (m *EmploymentContractMutation) ResetEmployeeID() {
	m.employee_id = nil
	m.addemployee_id = nil
}

// SetDepartmentID sets the "department_id" field.
func (m *EmploymentContractMutation) SetDepartmentID(i int64) {
	m.department_id = &i
	m.adddepartment_id = nil
}

// DepartmentID returns the value of the "department_id" field in the mutation.
func (m *EmploymentContractMutation) DepartmentID() (r int64, exists bool) {
	v := m.department_id
	if v == nil {
		return
	}
	return *v, true
}

// OldDepartmentID returns the old "department_id" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldDepartmentID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDepartmentID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDepartmentID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDepartmentID: %w", err)
	}
	return oldValue.DepartmentID, nil
}

// AddDepartmentID adds i to the "department_id" field.
func (m *EmploymentContractMutation) AddDepartmentID(i int64) {
	if m.adddepartment_id != nil {
		*m.adddepartment_id += i
	} else {
		m.adddepartment_id = &i
	}
}

// AddedDepartmentID returns the value that was added to the "department_id" field in this mutation.
func (m *EmploymentContractMutation) AddedDepartmentID() (r int64, exists bool) {
	v := m.adddepartment_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetDepartmentID resets all changes to the "department_id" field.
func (m *EmploymentContractMutation) ResetDepartmentID() {
	m.department_id = nil
	m.adddepartment_id = nil
}

// SetPositionID sets the "position_id" field.
func (m *EmploymentContractMutation) SetPositionID(i int64) {
	m.position_id = &i
	m.addposition_id = nil
}

// PositionID returns the value of the "position_id" field in the mutation.
func (m *EmploymentContractMutation) PositionID() (r int64, exists bool) {
	v := m.position_id
	if v == nil {
		return
	}
	return *v, true
}

// OldPositionID returns the old "position_id" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldPositionID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPositionID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPositionID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPositionID: %w", err)
	}
	return oldValue.PositionID, nil
}

// AddPositionID adds i to the "position_id" field.
func (m *EmploymentContractMutation) AddPositionID(i int64) {
	if m.addposition_id != nil {
		*m.addposition_id += i
	} else {
		m.addposition_id = &i
	}
}

// AddedPositionID returns the value that was added to the "position_id" field in this mutation.
func (m *EmploymentContractMutation) AddedPositionID() (r int64, exists bool) {
	v := m.addposition_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetPositionID resets all changes to the "position_id" field.
func (m *EmploymentContractMutation) ResetPositionID() {
	m.position_id = nil
	m.addposition_id = nil
}

// SetConditionsClass sets the "conditions_class" field.
func (m *EmploymentContractMutation) SetConditionsClass(i int) {
	m.conditions_class = &i
	m.addconditions_class = nil
}

// ConditionsClass returns the value of the "conditions_class" field in the mutation.
func (m *EmploymentContractMutation) ConditionsClass() (r int, exists bool) {
	v := m.conditions_class
	if v == nil {
		return
	}
	return *v, true
}

// OldConditionsClass returns the old "conditions_class" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldConditionsClass(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldConditionsClass is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldConditionsClass requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldConditionsClass: %w", err)
	}
	return oldValue.ConditionsClass, nil
}

// AddConditionsClass adds i to the "conditions_class" field.
func (m *EmploymentContractMutation) AddConditionsClass(i int) {
	if m.addconditions_class != nil {
		*m.addconditions_class += i
	} else {
		m.addconditions_class = &i
	}
}

// AddedConditionsClass returns the value that was added to the "conditions_class" field in this mutation.
func (m *EmploymentContractMutation) AddedConditionsClass() (r int, exists bool) {
	v := m.addconditions_class
	if v == nil {
		return
	}
	return *v, true
}

// ResetConditionsClass resets all changes to the "conditions_class" field.
func (m *EmploymentContractMutation) ResetConditionsClass() {
	m.conditions_class = nil
	m.addconditions_class = nil
}

// SetWorkDateFrom sets the "work_date_from" field.
func (m *EmploymentContractMutation) SetWorkDateFrom(t time.Time) {
	m.work_date_from = &t
}

// WorkDateFrom returns the value of the "work_date_from" field in the mutation.
func (m *EmploymentContractMutation) WorkDateFrom() (r time.Time, exists bool) {
	v := m.work_date_from
	if v == nil {
		return
	}
	return *v, true
}

// OldWorkDateFrom returns the old "work_date_from" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldWorkDateFrom(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWorkDateFrom is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWorkDateFrom requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWorkDateFrom: %w", err)
	}
	return oldValue.WorkDateFrom, nil
}

// ResetWorkDateFrom resets all changes to the "work_date_from" field.
func (m *EmploymentContractMutation) ResetWorkDateFrom() {
	m.work_date_from = nil
}

// SetWorkDateTo sets the "work_date_to" field.
func (m *EmploymentContractMutation) SetWorkDateTo(t time.Time) {
	m.work_date_to = &t
}

// WorkDateTo returns the value of the "work_date_to" field in the mutation.
func (m *EmploymentContractMutation) WorkDateTo() (r time.Time, exists bool) {
	v := m.work_date_to
	if v == nil {
		return
	}
	return *v, true
}

// OldWorkDateTo returns the old "work_date_to" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldWorkDateTo(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWorkDateTo is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWorkDateTo requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWorkDateTo: %w", err)
	}
	return oldValue.WorkDateTo, nil
}

// ClearWorkDateTo clears the value of the "work_date_to" field.
func (m *EmploymentContractMutation) ClearWorkDateTo() {
	m.work_date_to = nil
	m.clearedFields[employmentcontract.FieldWorkDateTo] = struct{}{}
}

// WorkDateToCleared returns if the "work_date_to" field was cleared in this mutation.
func (m *EmploymentContractMutation) WorkDateToCleared() bool {
	_, ok := m.clearedFields[employmentcontract.FieldWorkDateTo]
	return ok
}

// ResetWorkDateTo resets all changes to the "work_date_to" field.
func (m *EmploymentContractMutation) ResetWorkDateTo() {
	m.work_date_to = nil
	delete(m.clearedFields, employmentcontract.FieldWorkDateTo)
}

// SetProbationMonths sets the "probation_months" field.
func (m *EmploymentContractMutation) SetProbationMonths(i int) {
	m.probation_months = &i
	m.addprobation_months = nil
}

// ProbationMonths returns the value of the "probation_months" field in the mutation.
func (m *EmploymentContractMutation) ProbationMonths() (r int, exists bool) {
	v := m.probation_months
	if v == nil {
		return
	}
	return *v, true
}

// OldProbationMonths returns the old "probation_months" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldProbationMonths(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProbationMonths is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProbationMonths requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProbationMonths: %w", err)
	}
	return oldValue.ProbationMonths, nil
}

// AddProbationMonths adds i to the "probation_months" field.
func (m *EmploymentContractMutation) AddProbationMonths(i int) {
	if m.addprobation_months != nil {
		*m.addprobation_months += i
	} else {
		m.addprobation_months = &i
	}
}

// AddedProbationMonths returns the value that was added to the "probation_months" field in this mutation.
func (m *EmploymentContractMutation) AddedProbationMonths() (r int, exists bool) {
	v := m.addprobation_months
	if v == nil {
		return
	}
	return *v, true
}

// ClearProbationMonths clears the value of the "probation_months" field.
func (m *EmploymentContractMutation) ClearProbationMonths() {
	m.probation_months = nil
	m.addprobation_months = nil
	m.clearedFields[employmentcontract.FieldProbationMonths] = struct{}{}
}

// ProbationMonthsCleared returns if the "probation_months" field was cleared in this mutation.
func (m *EmploymentContractMutation) ProbationMonthsCleared() bool {
	_, ok := m.clearedFields[employmentcontract.FieldProbationMonths]
	return ok
}

// ResetProbationMonths resets all changes to the "probation_months" field.
func (m *EmploymentContractMutation) ResetProbationMonths() {
	m.probation_months = nil
	m.addprobation_months = nil
	delete(m.clearedFields, employmentcontract.FieldProbationMonths)
}

// SetSalary sets the "salary" field.
func (m *EmploymentContractMutation) SetSalary(f float64) {
	m.salary = &f
	m.addsalary = nil
}

// Salary returns the value of the "salary" field in the mutation.
func (m *EmploymentContractMutation) Salary() (r float64, exists bool) {
	v := m.salary
	if v == nil {
		return
	}
	return *v, true
}

// OldSalary returns the old "salary" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldSalary(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSalary is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSalary requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSalary: %w", err)
	}
	return oldValue.Salary, nil
}

// AddSalary adds f to the "salary" field.
func (m *EmploymentContractMutation) AddSalary(f float64) {
	if m.addsalary != nil {
		*m.addsalary += f
	} else {
		m.addsalary = &f
	}
}

// AddedSalary returns the value that was added to the "salary" field in this mutation.
func (m *EmploymentContractMutation) AddedSalary() (r float64, exists bool) {
	v := m.addsalary
	if v == nil {
		return
	}
	return *v, true
}

// ResetSalary resets all changes to the "salary" field.
func (m *EmploymentContractMutation) ResetSalary() {
	m.salary = nil
	m.addsalary = nil
}

// SetWorkHoursFrom sets the "work_hours_from" field.
func (m *EmploymentContractMutation) SetWorkHoursFrom(t time.Time) {
	m.work_hours_from = &t
}

// WorkHoursFrom returns the value of the "work_hours_from" field in the mutation.
func (m *EmploymentContractMutation) WorkHoursFrom() (r time.Time, exists bool) {
	v := m.work_hours_from
	if v == nil {
		return
	}
	return *v, true
}

// OldWorkHoursFrom returns the old "work_hours_from" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldWorkHoursFrom(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWorkHoursFrom is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWorkHoursFrom requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWorkHoursFrom: %w", err)
	}
	return oldValue.WorkHoursFrom, nil
}

// ResetWorkHoursFrom resets all changes to the "work_hours_from" field.
func (m *EmploymentContractMutation) ResetWorkHoursFrom() {
	m.work_hours_from = nil
}

// SetWorkHoursTo sets the "work_hours_to" field.
func (m *EmploymentContractMutation) SetWorkHoursTo(t time.Time) {
	m.work_hours_to = &t
}

// WorkHoursTo returns the value of the "work_hours_to" field in the mutation.
func (m *EmploymentContractMutation) WorkHoursTo() (r time.Time, exists bool) {
	v := m.work_hours_to
	if v == nil {
		return
	}
	return *v, true
}

// OldWorkHoursTo returns the old "work_hours_to" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldWorkHoursTo(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWorkHoursTo is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWorkHoursTo requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWorkHoursTo: %w", err)
	}
	return oldValue.WorkHoursTo, nil
}

// ResetWorkHoursTo resets all changes to the "work_hours_to" field.
func (m *EmploymentContractMutation) ResetWorkHoursTo() {
	m.work_hours_to = nil
}

// SetBreakFrom sets the "break_from" field.
func (m *EmploymentContractMutation) SetBreakFrom(t time.Time) {
	m.break_from = &t
}

// BreakFrom returns the value of the "break_from" field in the mutation.
func (m *EmploymentContractMutation) BreakFrom() (r time.Time, exists bool) {
	v := m.break_from
	if v == nil {
		return
	}
	return *v, true
}

// OldBreakFrom returns the old "break_from" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldBreakFrom(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBreakFrom is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBreakFrom requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBreakFrom: %w", err)
	}
	return oldValue.BreakFrom, nil
}

// ClearBreakFrom clears the value of the "break_from" field.
func (m *EmploymentContractMutation) ClearBreakFrom() {
	m.break_from = nil
	m.clearedFields[employmentcontract.FieldBreakFrom] = struct{}{}
}

// BreakFromCleared returns if the "break_from" field was cleared in this mutation.
func (m *EmploymentContractMutation) BreakFromCleared() bool {
	_, ok := m.clearedFields[employmentcontract.FieldBreakFrom]
	return ok
}

// ResetBreakFrom resets all changes to the "break_from" field.
func (m *EmploymentContractMutation) ResetBreakFrom() {
	m.break_from = nil
	delete(m.clearedFields, employmentcontract.FieldBreakFrom)
}

// SetBreakTo sets the "break_to" field.
func (m *EmploymentContractMutation) SetBreakTo(t time.Time) {
	m.break_to = &t
}

// BreakTo returns the value of the "break_to" field in the mutation.
func (m *EmploymentContractMutation) BreakTo() (r time.Time, exists bool) {
	v := m.break_to
	if v == nil {
		return
	}
	return *v, true
}

// OldBreakTo returns the old "break_to" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldBreakTo(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBreakTo is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBreakTo requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBreakTo: %w", err)
	}
	return oldValue.BreakTo, nil
}

// ClearBreakTo clears the value of the "break_to" field.
func (m *EmploymentContractMutation) ClearBreakTo() {
	m.break_to = nil
	m.clearedFields[employmentcontract.FieldBreakTo] = struct{}{}
}

// BreakToCleared returns if the "break_to" field was cleared in this mutation.
func (m *EmploymentContractMutation) BreakToCleared() bool {
	_, ok := m.clearedFields[employmentcontract.FieldBreakTo]
	return ok
}

// ResetBreakTo resets all changes to the "break_to" field.
func (m *EmploymentContractMutation) ResetBreakTo() {
	m.break_to = nil
	delete(m.clearedFields, employmentcontract.FieldBreakTo)
}

// SetPaidLeaveDays sets the "paid_leave_days" field.
func (m *EmploymentContractMutation) SetPaidLeaveDays(i int) {
	m.paid_leave_days = &i
	m.addpaid_leave_days = nil
}

// PaidLeaveDays returns the value of the "paid_leave_days" field in the mutation.
func (m *EmploymentContractMutation) PaidLeaveDays() (r int, exists bool) {
	v := m.paid_leave_days
	if v == nil {
		return
	}
	return *v, true
}

// OldPaidLeaveDays returns the old "paid_leave_days" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldPaidLeaveDays(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPaidLeaveDays is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPaidLeaveDays requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPaidLeaveDays: %w", err)
	}
	return oldValue.PaidLeaveDays, nil
}

// AddPaidLeaveDays adds i to the "paid_leave_days" field.
func (m *EmploymentContractMutation) AddPaidLeaveDays(i int) {
	if m.addpaid_leave_days != nil {
		*m.addpaid_leave_days += i
	} else {
		m.addpaid_leave_days = &i
	}
}

// AddedPaidLeaveDays returns the value that was added to the "paid_leave_days" field in this mutation.
func (m *EmploymentContractMutation) AddedPaidLeaveDays() (r int, exists bool) {
	v := m.addpaid_leave_days
	if v == nil {
		return
	}
	return *v, true
}

// ResetPaidLeaveDays resets all changes to the "paid_leave_days" field.
func (m *EmploymentContractMutation) ResetPaidLeaveDays() {
	m.paid_leave_days = nil
	m.addpaid_leave_days = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *EmploymentContractMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *EmploymentContractMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *EmploymentContractMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *EmploymentContractMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *EmploymentContractMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the EmploymentContract entity.
// If the EmploymentContract object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EmploymentContractMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *EmploymentContractMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the EmploymentContractMutation builder.
func (m *EmploymentContractMutation) Where(ps ...predicate.EmploymentContract) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the EmploymentContractMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *EmploymentContractMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.EmploymentContract, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *EmploymentContractMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *EmploymentContractMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (EmploymentContract).
func (m *EmploymentContractMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *EmploymentContractMutation) Fields() []string {
	fields := make([]string, 0, 20)
	if m.number != nil {
		fields = append(fields, employmentcontract.FieldNumber)
	}
	if m.personnel_number != nil {
		fields = append(fields, employmentcontract.FieldPersonnelNumber)
	}
	if m.conclusion_date != nil {
		fields = append(fields, employmentcontract.FieldConclusionDate)
	}
	if m.organization_id != nil {
		fields = append(fields, employmentcontract.FieldOrganizationID)
	}
	if m.representative_id != nil {
		fields = append(fields, employmentcontract.FieldRepresentativeID)
	}
	if m.employee_id != nil {
		fields = append(fields, employmentcontract.FieldEmployeeID)
	}
	if m.department_id != nil {
		fields = append(fields, employmentcontract.FieldDepartmentID)
	}
	if m.position_id != nil {
		fields = append(fields, employmentcontract.FieldPositionID)
	}
	if m.conditions_class != nil {
		fields = append(fields, employmentcontract.FieldConditionsClass)
	}
	if m.work_date_from != nil {
		fields = append(fields, employmentcontract.FieldWorkDateFrom)
	}
	if m.work_date_to != nil {
		fields = append(fields, employmentcontract.FieldWorkDateTo)
	}
	if m.probation_months != nil {
		fields = append(fields, employmentcontract.FieldProbationMonths)
	}
	if m.salary != nil {
		fields = append(fields, employmentcontract.FieldSalary)
	}
	if m.work_hours_from != nil {
		fields = append(fields, employmentcontract.FieldWorkHoursFrom)
	}
	if m.work_hours_to != nil {
		fields = append(fields, employmentcontract.FieldWorkHoursTo)
	}
	if m.break_from != nil {
		fields = append(fields, employmentcontract.FieldBreakFrom)
	}
	if m.break_to != nil {
		fields = append(fields, employmentcontract.FieldBreakTo)
	}
	if m.paid_leave_days != nil {
		fields = append(fields, employmentcontract.FieldPaidLeaveDays)
	}
	if m.created_at != nil {
		fields = append(fields, employmentcontract.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, employmentcontract.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *EmploymentContractMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case employmentcontract.FieldNumber:
		return m.Number()
	case employmentcontract.FieldPersonnelNumber:
		return m.PersonnelNumber()
	case employmentcontract.FieldConclusionDate:
		return m.ConclusionDate()
	case employmentcontract.FieldOrganizationID:
		return m.OrganizationID()
	case employmentcontract.FieldRepresentativeID:
		return m.RepresentativeID()
	case employmentcontract.FieldEmployeeID:
		return m.EmployeeID()
	case employmentcontract.FieldDepartmentID:
		return m.DepartmentID()
	case employmentcontract.FieldPositionID:
		return m.PositionID()
	case employmentcontract.FieldConditionsClass:
		return m.ConditionsClass()
	case employmentcontract.FieldWorkDateFrom:
		return m.WorkDateFrom()
	case employmentcontract.FieldWorkDateTo:
		return m.WorkDateTo()
	case employmentcontract.FieldProbationMonths:
		return m.ProbationMonths()
	case employmentcontract.FieldSalary:
		return m.Salary()
	case employmentcontract.FieldWorkHoursFrom:
		return m.WorkHoursFrom()
	case employmentcontract.FieldWorkHoursTo:
		return m.WorkHoursTo()
	case employmentcontract.FieldBreakFrom:
		return m.BreakFrom()
	case employmentcontract.FieldBreakTo:
		return m.BreakTo()
	case employmentcontract.FieldPaidLeaveDays:
		return m.PaidLeaveDays()
	case employmentcontract.FieldCreatedAt:
		return m.CreatedAt()
	case employmentcontract.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *EmploymentContractMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case employmentcontract.FieldNumber:
		return m.OldNumber(ctx)
	case employmentcontract.FieldPersonnelNumber:
		return m.OldPersonnelNumber(ctx)
	case employmentcontract.FieldConclusionDate:
		return m.OldConclusionDate(ctx)
	case employmentcontract.FieldOrganizationID:
		return m.OldOrganizationID(ctx)
	case employmentcontract.FieldRepresentativeID:
		return m.OldRepresentativeID(ctx)
	case employmentcontract.FieldEmployeeID:
		return m.OldEmployeeID(ctx)
	case employmentcontract.FieldDepartmentID:
		return m.OldDepartmentID(ctx)
	case employmentcontract.FieldPositionID:
		return m.OldPositionID(ctx)
	case employmentcontract.FieldConditionsClass:
		return m.OldConditionsClass(ctx)
	case employmentcontract.FieldWorkDateFrom:
		return m.OldWorkDateFrom(ctx)
	case employmentcontract.FieldWorkDateTo:
		return m.OldWorkDateTo(ctx)
	case employmentcontract.FieldProbationMonths:
		return m.OldProbationMonths(ctx)
	case employmentcontract.FieldSalary:
		return m.OldSalary(ctx)
	case employmentcontract.FieldWorkHoursFrom:
		return m.OldWorkHoursFrom(ctx)
	case employmentcontract.FieldWorkHoursTo:
		return m.OldWorkHoursTo(ctx)
	case employmentcontract.FieldBreakFrom:
		return m.OldBreakFrom(ctx)
	case employmentcontract.FieldBreakTo:
		return m.OldBreakTo(ctx)
	case employmentcontract.FieldPaidLeaveDays:
		return m.OldPaidLeaveDays(ctx)
	case employmentcontract.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case employmentcontract.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown EmploymentContract field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EmploymentContractMutation) SetField(name string, value ent.Value) error {
	switch name {
	case employmentcontract.FieldNumber:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNumber(v)
		return nil
	case employmentcontract.FieldPersonnelNumber:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPersonnelNumber(v)
		return nil
	case employmentcontract.FieldConclusionDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetConclusionDate(v)
		return nil
	case employmentcontract.FieldOrganizationID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOrganizationID(v)
		return nil
	case employmentcontract.FieldRepresentativeID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRepresentativeID(v)
		return nil
	case employmentcontract.FieldEmployeeID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmployeeID(v)
		return nil
	case employmentcontract.FieldDepartmentID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDepartmentID(v)
		return nil
	case employmentcontract.FieldPositionID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPositionID(v)
		return nil
	case employmentcontract.FieldConditionsClass:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetConditionsClass(v)
		return nil
	case employmentcontract.FieldWorkDateFrom:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWorkDateFrom(v)
		return nil
	case employmentcontract.FieldWorkDateTo:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWorkDateTo(v)
		return nil
	case employmentcontract.FieldProbationMonths:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProbationMonths(v)
		return nil
	case employmentcontract.FieldSalary:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSalary(v)
		return nil
	case employmentcontract.FieldWorkHoursFrom:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWorkHoursFrom(v)
		return nil
	case employmentcontract.FieldWorkHoursTo:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWorkHoursTo(v)
		return nil
	case employmentcontract.FieldBreakFrom:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBreakFrom(v)
		return nil
	case employmentcontract.FieldBreakTo:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBreakTo(v)
		return nil
	case employmentcontract.FieldPaidLeaveDays:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPaidLeaveDays(v)
		return nil
	case employmentcontract.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case employmentcontract.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown EmploymentContract field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *EmploymentContractMutation) AddedFields() []string {
	var fields []string
	if m.addorganization_id != nil {
		fields = append(fields, employmentcontract.FieldOrganizationID)
	}
	if m.addrepresentative_id != nil {
		fields = append(fields, employmentcontract.FieldRepresentativeID)
	}
	if m.addemployee_id != nil {
		fields = append(fields, employmentcontract.FieldEmployeeID)
	}
	if m.adddepartment_id != nil {
		fields = append(fields, employmentcontract.FieldDepartmentID)
	}
	if m.addposition_id != nil {
		fields = append(fields, employmentcontract.FieldPositionID)
	}
	if m.addconditions_class != nil {
		fields = append(fields, employmentcontract.FieldConditionsClass)
	}
	if m.addprobation_months != nil {
		fields = append(fields, employmentcontract.FieldProbationMonths)
	}
	if m.addsalary != nil {
		fields = append(fields, employmentcontract.FieldSalary)
	}
	if m.addpaid_leave_days != nil {
		fields = append(fields, employmentcontract.FieldPaidLeaveDays)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *EmploymentContractMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case employmentcontract.FieldOrganizationID:
		return m.AddedOrganizationID()
	case employmentcontract.FieldRepresentativeID:
		return m.AddedRepresentativeID()
	case employmentcontract.FieldEmployeeID:
		return m.AddedEmployeeID()
	case employmentcontract.FieldDepartmentID:
		return m.AddedDepartmentID()
	case employmentcontract.FieldPositionID:
		return m.AddedPositionID()
	case employmentcontract.FieldConditionsClass:
		return m.AddedConditionsClass()
	case employmentcontract.FieldProbationMonths:
		return m.AddedProbationMonths()
	case employmentcontract.FieldSalary:
		return m.AddedSalary()
	case employmentcontract.FieldPaidLeaveDays:
		return m.AddedPaidLeaveDays()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EmploymentContractMutation) AddField(name string, value ent.Value) error {
	switch name {
	case employmentcontract.FieldOrganizationID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddOrganizationID(v)
		return nil
	case employmentcontract.FieldRepresentativeID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRepresentativeID(v)
		return nil
	case employmentcontract.FieldEmployeeID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddEmployeeID(v)
		return nil
	case employmentcontract.FieldDepartmentID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDepartmentID(v)
		return nil
	case employmentcontract.FieldPositionID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPositionID(v)
		return nil
	case employmentcontract.FieldConditionsClass:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddConditionsClass(v)
		return nil
	case employmentcontract.FieldProbationMonths:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddProbationMonths(v)
		return nil
	case employmentcontract.FieldSalary:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSalary(v)
		return nil
	case employmentcontract.FieldPaidLeaveDays:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPaidLeaveDays(v)
		return nil
	}
	return fmt.Errorf("unknown EmploymentContract numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *EmploymentContractMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(employmentcontract.FieldWorkDateTo) {
		fields = append(fields, employmentcontract.FieldWorkDateTo)
	}
	if m.FieldCleared(employmentcontract.FieldProbationMonths) {
		fields = append(fields, employmentcontract.FieldProbationMonths)
	}
	if m.FieldCleared(employmentcontract.FieldBreakFrom) {
		fields = append(fields, employmentcontract.FieldBreakFrom)
	}
	if m.FieldCleared(employmentcontract.FieldBreakTo) {
		fields = append(fields, employmentcontract.FieldBreakTo)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *EmploymentContractMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *EmploymentContractMutation) ClearField(name string) error {
	switch name {
	case employmentcontract.FieldWorkDateTo:
		m.ClearWorkDateTo()
		return nil
	case employmentcontract.FieldProbationMonths:
		m.ClearProbationMonths()
		return nil
	case employmentcontract.FieldBreakFrom:
		m.ClearBreakFrom()
		return nil
	case employmentcontract.FieldBreakTo:
		m.ClearBreakTo()
		return nil
	}
	return fmt.Errorf("unknown EmploymentContract nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *EmploymentContractMutation) ResetField(name string) error {
	switch name {
	case employmentcontract.FieldNumber:
		m.ResetNumber()
		return nil
	case employmentcontract.FieldPersonnelNumber:
		m.ResetPersonnelNumber()
		return nil
	case employmentcontract.FieldConclusionDate:
		m.ResetConclusionDate()
		return nil
	case employmentcontract.FieldOrganizationID:
		m.ResetOrganizationID()
		return nil
	case employmentcontract.FieldRepresentativeID:
		m.ResetRepresentativeID()
		return nil
	case employmentcontract.FieldEmployeeID:
		m.ResetEmployeeID()
		return nil
	case employmentcontract.FieldDepartmentID:
		m.ResetDepartmentID()
		return nil
	case employmentcontract.FieldPositionID:
		m.ResetPositionID()
		return nil
	case employmentcontract.FieldConditionsClass:
		m.ResetConditionsClass()
		return nil
	case employmentcontract.FieldWorkDateFrom:
		m.ResetWorkDateFrom()
		return nil
	case employmentcontract.FieldWorkDateTo:
		m.ResetWorkDateTo()
		return nil
	case employmentcontract.FieldProbationMonths:
		m.ResetProbationMonths()
		return nil
	case employmentcontract.FieldSalary:
		m.ResetSalary()
		return nil
	case employmentcontract.FieldWorkHoursFrom:
		m.ResetWorkHoursFrom()
		return nil
	case employmentcontract.FieldWorkHoursTo:
		m.ResetWorkHoursTo()
		return nil
	case employmentcontract.FieldBreakFrom:
		m.ResetBreakFrom()
		return nil
	case employmentcontract.FieldBreakTo:
		m.ResetBreakTo()
		return nil
	case employmentcontract.FieldPaidLeaveDays:
		m.ResetPaidLeaveDays()
		return nil
	case employmentcontract.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case employmentcontract.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown EmploymentContract field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *EmploymentContractMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *EmploymentContractMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *EmploymentContractMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *EmploymentContractMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *EmploymentContractMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *EmploymentContractMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *EmploymentContractMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown EmploymentContract unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *EmploymentContractMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown EmploymentContract edge %s", name)
}
