// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/example/micro/employment-contracts/ent/employmentcontract"
	"github.com/example/micro/employment-contracts/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	employmentcontractFields := schema.EmploymentContract{}.Fields()
	_ = employmentcontractFields
	// employmentcontractDescNumber is the schema descriptor for number field.
	employmentcontractDescNumber := employmentcontractFields[1].Descriptor()
	// employmentcontract.NumberValidator is a validator for the "number" field. It is called by the builders before save.
	employmentcontract.NumberValidator = func() func(string) error {
		validators := employmentcontractDescNumber.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(number string) error {
			for _, fn := range fns {
				if err := fn(number); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// employmentcontractDescPersonnelNumber is the schema descriptor for personnel_number field.
	employmentcontractDescPersonnelNumber := employmentcontractFields[2].Descriptor()
	// employmentcontract.PersonnelNumberValidator is a validator for the "personnel_number" field. It is called by the builders before save.
	employmentcontract.PersonnelNumberValidator = employmentcontractDescPersonnelNumber.Validators[0].(func(string) error)
	// employmentcontractDescCreatedAt is the schema descriptor for created_at field.
	employmentcontractDescCreatedAt := employmentcontractFields[19].Descriptor()
	// employmentcontract.DefaultCreatedAt holds the default value on creation for the created_at field.
	employmentcontract.DefaultCreatedAt = employmentcontractDescCreatedAt.Default.(func() time.Time)
	// employmentcontractDescUpdatedAt is the schema descriptor for updated_at field.
	employmentcontractDescUpdatedAt := employmentcontractFields[20].Descriptor()
	// employmentcontract.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	employmentcontract.DefaultUpdatedAt = employmentcontractDescUpdatedAt.Default.(func() time.Time)
	// employmentcontract.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	employmentcontract.UpdateDefaultUpdatedAt = employmentcontractDescUpdatedAt.UpdateDefault.(func() time.Time)
}
