// Code generated by ent, DO NOT EDIT.

package organization

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/example/micro/organizations/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldTitle, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldAddress, v))
}

// Okpo applies equality check predicate on the "okpo" field. It's identical to OkpoEQ.
func Okpo(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldOkpo, v))
}

// Inn applies equality check predicate on the "inn" field. It's identical to InnEQ.
func Inn(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldInn, v))
}

// Kpp applies equality check predicate on the "kpp" field. It's identical to KppEQ.
func Kpp(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldKpp, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldAccountID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContainsFold(FieldTitle, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContainsFold(FieldAddress, v))
}

// OkpoEQ applies the EQ predicate on the "okpo" field.
func OkpoEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldOkpo, v))
}

// OkpoNEQ applies the NEQ predicate on the "okpo" field.
func OkpoNEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldOkpo, v))
}

// OkpoIn applies the In predicate on the "okpo" field.
func OkpoIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldOkpo, vs...))
}

// OkpoNotIn applies the NotIn predicate on the "okpo" field.
func OkpoNotIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldOkpo, vs...))
}

// OkpoGT applies the GT predicate on the "okpo" field.
func OkpoGT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldOkpo, v))
}

// OkpoGTE applies the GTE predicate on the "okpo" field.
func OkpoGTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldOkpo, v))
}

// OkpoLT applies the LT predicate on the "okpo" field.
func OkpoLT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldOkpo, v))
}

// OkpoLTE applies the LTE predicate on the "okpo" field.
func OkpoLTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldOkpo, v))
}

// OkpoContains applies the Contains predicate on the "okpo" field.
func OkpoContains(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContains(FieldOkpo, v))
}

// OkpoHasPrefix applies the HasPrefix predicate on the "okpo" field.
func OkpoHasPrefix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasPrefix(FieldOkpo, v))
}

// OkpoHasSuffix applies the HasSuffix predicate on the "okpo" field.
func OkpoHasSuffix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasSuffix(FieldOkpo, v))
}

// OkpoEqualFold applies the EqualFold predicate on the "okpo" field.
func OkpoEqualFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEqualFold(FieldOkpo, v))
}

// OkpoContainsFold applies the ContainsFold predicate on the "okpo" field.
func OkpoContainsFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContainsFold(FieldOkpo, v))
}

// InnEQ applies the EQ predicate on the "inn" field.
func InnEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldInn, v))
}

// InnNEQ applies the NEQ predicate on the "inn" field.
func InnNEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldInn, v))
}

// InnIn applies the In predicate on the "inn" field.
func InnIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldInn, vs...))
}

// InnNotIn applies the NotIn predicate on the "inn" field.
func InnNotIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldInn, vs...))
}

// InnGT applies the GT predicate on the "inn" field.
func InnGT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldInn, v))
}

// InnGTE applies the GTE predicate on the "inn" field.
func InnGTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldInn, v))
}

// InnLT applies the LT predicate on the "inn" field.
func InnLT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldInn, v))
}

// InnLTE applies the LTE predicate on the "inn" field.
func InnLTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldInn, v))
}

// InnContains applies the Contains predicate on the "inn" field.
func InnContains(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContains(FieldInn, v))
}

// InnHasPrefix applies the HasPrefix predicate on the "inn" field.
func InnHasPrefix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasPrefix(FieldInn, v))
}

// InnHasSuffix applies the HasSuffix predicate on the "inn" field.
func InnHasSuffix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasSuffix(FieldInn, v))
}

// InnEqualFold applies the EqualFold predicate on the "inn" field.
func InnEqualFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEqualFold(FieldInn, v))
}

// InnContainsFold applies the ContainsFold predicate on the "inn" field.
func InnContainsFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContainsFold(FieldInn, v))
}

// KppEQ applies the EQ predicate on the "kpp" field.
func KppEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldKpp, v))
}

// KppNEQ applies the NEQ predicate on the "kpp" field.
func KppNEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldKpp, v))
}

// KppIn applies the In predicate on the "kpp" field.
func KppIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldKpp, vs...))
}

// KppNotIn applies the NotIn predicate on the "kpp" field.
func KppNotIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldKpp, vs...))
}

// KppGT applies the GT predicate on the "kpp" field.
func KppGT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldKpp, v))
}

// KppGTE applies the GTE predicate on the "kpp" field.
func KppGTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldKpp, v))
}

// KppLT applies the LT predicate on the "kpp" field.
func KppLT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldKpp, v))
}

// KppLTE applies the LTE predicate on the "kpp" field.
func KppLTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldKpp, v))
}

// KppContains applies the Contains predicate on the "kpp" field.
func KppContains(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContains(FieldKpp, v))
}

// KppHasPrefix applies the HasPrefix predicate on the "kpp" field.
func KppHasPrefix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasPrefix(FieldKpp, v))
}

// KppHasSuffix applies the HasSuffix predicate on the "kpp" field.
func KppHasSuffix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasSuffix(FieldKpp, v))
}

// KppIsNil applies the IsNil predicate on the "kpp" field.
func KppIsNil() predicate.Organization {
	return predicate.Organization(sql.FieldIsNull(FieldKpp))
}

// KppNotNil applies the NotNil predicate on the "kpp" field.
func KppNotNil() predicate.Organization {
	return predicate.Organization(sql.FieldNotNull(FieldKpp))
}

// KppEqualFold applies the EqualFold predicate on the "kpp" field.
func KppEqualFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEqualFold(FieldKpp, v))
}

// KppContainsFold applies the ContainsFold predicate on the "kpp" field.
func KppContainsFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContainsFold(FieldKpp, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldAccountID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Organization) predicate.Organization {
	return predicate.Organization(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Organization) predicate.Organization {
	return predicate.Organization(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Organization) predicate.Organization {
	return predicate.Organization(sql.NotPredicates(p))
}
