// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/example/micro/dismissal-order/ent/dismissalorderheader"
)

// DismissalOrderHeader is the model entity for the DismissalOrderHeader schema.
type DismissalOrderHeader struct {
	config `json:"-"`
	// ID of the ent.
	// matches BIGSERIAL
	ID int64 `json:"id,omitempty"`
	// Number holds the value of the "number" field.
	Number string `json:"number,omitempty"`
	// PreparationDate holds the value of the "preparation_date" field.
	PreparationDate time.Time `json:"preparation_date,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID int64 `json:"organization_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DismissalOrderHeaderQuery when eager-loading is set.
	Edges        DismissalOrderHeaderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DismissalOrderHeaderEdges holds the relations/edges for other nodes in the graph.
type DismissalOrderHeaderEdges struct {
	// Bodies holds the value of the bodies edge.
	Bodies []*DismissalOrderBody `json:"bodies,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// BodiesOrErr returns the Bodies value or an error if the edge
// was not loaded in eager-loading.
func (e DismissalOrderHeaderEdges) BodiesOrErr() ([]*DismissalOrderBody, error) {
	if e.loadedTypes[0] {
		return e.Bodies, nil
	}
	return nil, &NotLoadedError{edge: "bodies"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DismissalOrderHeader) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dismissalorderheader.FieldID, dismissalorderheader.FieldOrganizationID:
			values[i] = new(sql.NullInt64)
		case dismissalorderheader.FieldNumber:
			values[i] = new(sql.NullString)
		case dismissalorderheader.FieldPreparationDate, dismissalorderheader.FieldCreatedAt, dismissalorderheader.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DismissalOrderHeader fields.
func (doh *DismissalOrderHeader) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dismissalorderheader.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			doh.ID = int64(value.Int64)
		case dismissalorderheader.FieldNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field number", values[i])
			} else if value.Valid {
				doh.Number = value.String
			}
		case dismissalorderheader.FieldPreparationDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field preparation_date", values[i])
			} else if value.Valid {
				doh.PreparationDate = value.Time
			}
		case dismissalorderheader.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				doh.OrganizationID = value.Int64
			}
		case dismissalorderheader.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				doh.CreatedAt = value.Time
			}
		case dismissalorderheader.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				doh.UpdatedAt = value.Time
			}
		default:
			doh.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DismissalOrderHeader.
// This includes values selected through modifiers, order, etc.
func (doh *DismissalOrderHeader) Value(name string) (ent.Value, error) {
	return doh.selectValues.Get(name)
}

// QueryBodies queries the "bodies" edge of the DismissalOrderHeader entity.
func (doh *DismissalOrderHeader) QueryBodies() *DismissalOrderBodyQuery {
	return NewDismissalOrderHeaderClient(doh.config).QueryBodies(doh)
}

// Update returns a builder for updating this DismissalOrderHeader.
// Note that you need to call DismissalOrderHeader.Unwrap() before calling this method if this DismissalOrderHeader
// was returned from a transaction, and the transaction was committed or rolled back.
func (doh *DismissalOrderHeader) Update() *DismissalOrderHeaderUpdateOne {
	return NewDismissalOrderHeaderClient(doh.config).UpdateOne(doh)
}

// Unwrap unwraps the DismissalOrderHeader entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (doh *DismissalOrderHeader) Unwrap() *DismissalOrderHeader {
	_tx, ok := doh.config.driver.(*txDriver)
	if !ok {
		panic("ent: DismissalOrderHeader is not a transactional entity")
	}
	doh.config.driver = _tx.drv
	return doh
}

// String implements the fmt.Stringer.
func (doh *DismissalOrderHeader) String() string {
	var builder strings.Builder
	builder.WriteString("DismissalOrderHeader(")
	builder.WriteString(fmt.Sprintf("id=%v, ", doh.ID))
	builder.WriteString("number=")
	builder.WriteString(doh.Number)
	builder.WriteString(", ")
	builder.WriteString("preparation_date=")
	builder.WriteString(doh.PreparationDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("organization_id=")
	builder.WriteString(fmt.Sprintf("%v", doh.OrganizationID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(doh.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(doh.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DismissalOrderHeaders is a parsable slice of DismissalOrderHeader.
type DismissalOrderHeaders []*DismissalOrderHeader
