// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/example/micro/dismissal-order/ent/dismissalorderbody"
	"github.com/example/micro/dismissal-order/ent/predicate"
)

// DismissalOrderBodyDelete is the builder for deleting a DismissalOrderBody entity.
type DismissalOrderBodyDelete struct {
	config
	hooks    []Hook
	mutation *DismissalOrderBodyMutation
}

// Where appends a list predicates to the DismissalOrderBodyDelete builder.
func (dobd *DismissalOrderBodyDelete) Where(ps ...predicate.DismissalOrderBody) *DismissalOrderBodyDelete {
	dobd.mutation.Where(ps...)
	return dobd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dobd *DismissalOrderBodyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dobd.sqlExec, dobd.mutation, dobd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dobd *DismissalOrderBodyDelete) ExecX(ctx context.Context) int {
	n, err := dobd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dobd *DismissalOrderBodyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dismissalorderbody.Table, sqlgraph.NewFieldSpec(dismissalorderbody.FieldID, field.TypeInt64))
	if ps := dobd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dobd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dobd.mutation.done = true
	return affected, err
}

// DismissalOrderBodyDeleteOne is the builder for deleting a single DismissalOrderBody entity.
type DismissalOrderBodyDeleteOne struct {
	dobd *DismissalOrderBodyDelete
}

// Where appends a list predicates to the DismissalOrderBodyDelete builder.
func (dobdo *DismissalOrderBodyDeleteOne) Where(ps ...predicate.DismissalOrderBody) *DismissalOrderBodyDeleteOne {
	dobdo.dobd.mutation.Where(ps...)
	return dobdo
}

// Exec executes the deletion query.
func (dobdo *DismissalOrderBodyDeleteOne) Exec(ctx context.Context) error {
	n, err := dobdo.dobd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dismissalorderbody.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dobdo *DismissalOrderBodyDeleteOne) ExecX(ctx context.Context) {
	if err := dobdo.Exec(ctx); err != nil {
		panic(err)
	}
}
