// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/example/micro/dismissal-order/ent/dismissalorderbody"
	"github.com/example/micro/dismissal-order/ent/dismissalorderheader"
)

// DismissalOrderBody is the model entity for the DismissalOrderBody schema.
type DismissalOrderBody struct {
	config `json:"-"`
	// ID of the ent.
	// matches BIGSERIAL
	ID int64 `json:"id,omitempty"`
	// DismissalOrderHeaderID holds the value of the "dismissal_order_header_id" field.
	DismissalOrderHeaderID int64 `json:"dismissal_order_header_id,omitempty"`
	// EmploymentContractID holds the value of the "employment_contract_id" field.
	EmploymentContractID int64 `json:"employment_contract_id,omitempty"`
	// DepartmentID holds the value of the "department_id" field.
	DepartmentID int64 `json:"department_id,omitempty"`
	// PositionID holds the value of the "position_id" field.
	PositionID int64 `json:"position_id,omitempty"`
	// DismissalDate holds the value of the "dismissal_date" field.
	DismissalDate time.Time `json:"dismissal_date,omitempty"`
	// DismissalGround holds the value of the "dismissal_ground" field.
	DismissalGround string `json:"dismissal_ground,omitempty"`
	// DocNumber holds the value of the "doc_number" field.
	DocNumber *int `json:"doc_number,omitempty"`
	// DocDate holds the value of the "doc_date" field.
	DocDate *time.Time `json:"doc_date,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DismissalOrderBodyQuery when eager-loading is set.
	Edges        DismissalOrderBodyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DismissalOrderBodyEdges holds the relations/edges for other nodes in the graph.
type DismissalOrderBodyEdges struct {
	// Header holds the value of the header edge.
	Header *DismissalOrderHeader `json:"header,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// HeaderOrErr returns the Header value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DismissalOrderBodyEdges) HeaderOrErr() (*DismissalOrderHeader, error) {
	if e.Header != nil {
		return e.Header, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: dismissalorderheader.Label}
	}
	return nil, &NotLoadedError{edge: "header"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DismissalOrderBody) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dismissalorderbody.FieldID, dismissalorderbody.FieldDismissalOrderHeaderID, dismissalorderbody.FieldEmploymentContractID, dismissalorderbody.FieldDepartmentID, dismissalorderbody.FieldPositionID, dismissalorderbody.FieldDocNumber:
			values[i] = new(sql.NullInt64)
		case dismissalorderbody.FieldDocDate:
			values[i] = new(sql.NullTime)
		case dismissalorderbody.FieldDismissalGround:
			values[i] = new(sql.NullString)
		case dismissalorderbody.FieldDismissalDate, dismissalorderbody.FieldCreatedAt, dismissalorderbody.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DismissalOrderBody fields.
func (dob *DismissalOrderBody) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dismissalorderbody.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			dob.ID = int64(value.Int64)
		case dismissalorderbody.FieldDismissalOrderHeaderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field dismissal_order_header_id", values[i])
			} else if value.Valid {
				dob.DismissalOrderHeaderID = value.Int64
			}
		case dismissalorderbody.FieldEmploymentContractID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field employment_contract_id", values[i])
			} else if value.Valid {
				dob.EmploymentContractID = value.Int64
			}
		case dismissalorderbody.FieldDepartmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value.Valid {
				dob.DepartmentID = value.Int64
			}
		case dismissalorderbody.FieldPositionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position_id", values[i])
			} else if value.Valid {
				dob.PositionID = value.Int64
			}
		case dismissalorderbody.FieldDismissalDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field dismissal_date", values[i])
			} else if value.Valid {
				dob.DismissalDate = value.Time
			}
		case dismissalorderbody.FieldDismissalGround:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dismissal_ground", values[i])
			} else if value.Valid {
				dob.DismissalGround = value.String
			}
		case dismissalorderbody.FieldDocNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field doc_number", values[i])
			} else if value.Valid {
				dob.DocNumber = new(int)
				*dob.DocNumber = int(value.Int64)
			}
		case dismissalorderbody.FieldDocDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field doc_date", values[i])
			} else if value.Valid {
				dob.DocDate = new(time.Time)
				*dob.DocDate = value.Time
			}
		case dismissalorderbody.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				dob.CreatedAt = value.Time
			}
		case dismissalorderbody.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				dob.UpdatedAt = value.Time
			}
		default:
			dob.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DismissalOrderBody.
// This includes values selected through modifiers, order, etc.
func (dob *DismissalOrderBody) Value(name string) (ent.Value, error) {
	return dob.selectValues.Get(name)
}

// QueryHeader queries the "header" edge of the DismissalOrderBody entity.
func (dob *DismissalOrderBody) QueryHeader() *DismissalOrderHeaderQuery {
	return NewDismissalOrderBodyClient(dob.config).QueryHeader(dob)
}

// Update returns a builder for updating this DismissalOrderBody.
// Note that you need to call DismissalOrderBody.Unwrap() before calling this method if this DismissalOrderBody
// was returned from a transaction, and the transaction was committed or rolled back.
func (dob *DismissalOrderBody) Update() *DismissalOrderBodyUpdateOne {
	return NewDismissalOrderBodyClient(dob.config).UpdateOne(dob)
}

// Unwrap unwraps the DismissalOrderBody entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (dob *DismissalOrderBody) Unwrap() *DismissalOrderBody {
	_tx, ok := dob.config.driver.(*txDriver)
	if !ok {
		panic("ent: DismissalOrderBody is not a transactional entity")
	}
	dob.config.driver = _tx.drv
	return dob
}

// String implements the fmt.Stringer.
func (dob *DismissalOrderBody) String() string {
	var builder strings.Builder
	builder.WriteString("DismissalOrderBody(")
	builder.WriteString(fmt.Sprintf("id=%v, ", dob.ID))
	builder.WriteString("dismissal_order_header_id=")
	builder.WriteString(fmt.Sprintf("%v", dob.DismissalOrderHeaderID))
	builder.WriteString(", ")
	builder.WriteString("employment_contract_id=")
	builder.WriteString(fmt.Sprintf("%v", dob.EmploymentContractID))
	builder.WriteString(", ")
	builder.WriteString("department_id=")
	builder.WriteString(fmt.Sprintf("%v", dob.DepartmentID))
	builder.WriteString(", ")
	builder.WriteString("position_id=")
	builder.WriteString(fmt.Sprintf("%v", dob.PositionID))
	builder.WriteString(", ")
	builder.WriteString("dismissal_date=")
	builder.WriteString(dob.DismissalDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("dismissal_ground=")
	builder.WriteString(dob.DismissalGround)
	builder.WriteString(", ")
	if v := dob.DocNumber; v != nil {
		builder.WriteString("doc_number=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := dob.DocDate; v != nil {
		builder.WriteString("doc_date=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(dob.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(dob.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DismissalOrderBodies is a parsable slice of DismissalOrderBody.
type DismissalOrderBodies []*DismissalOrderBody
