// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/example/micro/dismissal-order/ent/dismissalorderbody"
	"github.com/example/micro/dismissal-order/ent/dismissalorderheader"
	"github.com/example/micro/dismissal-order/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeDismissalOrderBody   = "DismissalOrderBody"
	TypeDismissalOrderHeader = "DismissalOrderHeader"
)

// DismissalOrderBodyMutation represents an operation that mutates the DismissalOrderBody nodes in the graph.
type DismissalOrderBodyMutation struct {
	config
	op                        Op
	typ                       string
	id                        *int64
	employment_contract_id    *int64
	addemployment_contract_id *int64
	department_id             *int64
	adddepartment_id          *int64
	position_id               *int64
	addposition_id            *int64
	dismissal_date            *time.Time
	dismissal_ground          *string
	doc_number                *int
	adddoc_number             *int
	doc_date                  *time.Time
	adddoc_date               *time.Time
	created_at                *time.Time
	updated_at                *time.Time
	clearedFields             map[string]struct{}
	header                    *int64
	clearedheader             bool
	done                      bool
	oldValue                  func(context.Context) (*DismissalOrderBody, error)
	predicates                []predicate.DismissalOrderBody
}

var _ ent.Mutation = (*DismissalOrderBodyMutation)(nil)

// dismissalorderbodyOption allows management of the mutation configuration using functional options.
type dismissalorderbodyOption func(*DismissalOrderBodyMutation)

// newDismissalOrderBodyMutation creates new mutation for the DismissalOrderBody entity.
func newDismissalOrderBodyMutation(c config, op Op, opts ...dismissalorderbodyOption) *DismissalOrderBodyMutation {
	m := &DismissalOrderBodyMutation{
		config:        c,
		op:            op,
		typ:           TypeDismissalOrderBody,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDismissalOrderBodyID sets the ID field of the mutation.
func withDismissalOrderBodyID(id int64) dismissalorderbodyOption {
	return func(m *DismissalOrderBodyMutation) {
		var (
			err   error
			once  sync.Once
			value *DismissalOrderBody
		)
		m.oldValue = func(ctx context.Context) (*DismissalOrderBody, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().DismissalOrderBody.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDismissalOrderBody sets the old DismissalOrderBody of the mutation.
func withDismissalOrderBody(node *DismissalOrderBody) dismissalorderbodyOption {
	return func(m *DismissalOrderBodyMutation) {
		m.oldValue = func(context.Context) (*DismissalOrderBody, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DismissalOrderBodyMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DismissalOrderBodyMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of DismissalOrderBody entities.
func (m *DismissalOrderBodyMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DismissalOrderBodyMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DismissalOrderBodyMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().DismissalOrderBody.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetDismissalOrderHeaderID sets the "dismissal_order_header_id" field.
func (m *DismissalOrderBodyMutation) SetDismissalOrderHeaderID(i int64) {
	m.header = &i
}

// DismissalOrderHeaderID returns the value of the "dismissal_order_header_id" field in the mutation.
func (m *DismissalOrderBodyMutation) DismissalOrderHeaderID() (r int64, exists bool) {
	v := m.header
	if v == nil {
		return
	}
	return *v, true
}

// OldDismissalOrderHeaderID returns the old "dismissal_order_header_id" field's value of the DismissalOrderBody entity.
// If the DismissalOrderBody object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DismissalOrderBodyMutation) OldDismissalOrderHeaderID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDismissalOrderHeaderID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDismissalOrderHeaderID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDismissalOrderHeaderID: %w", err)
	}
	return oldValue.DismissalOrderHeaderID, nil
}

// ResetDismissalOrderHeaderID resets all changes to the "dismissal_order_header_id" field.
func (m *DismissalOrderBodyMutation) ResetDismissalOrderHeaderID() {
	m.header = nil
}

// SetEmploymentContractID sets the "employment_contract_id" field.
func (m *DismissalOrderBodyMutation) SetEmploymentContractID(i int64) {
	m.employment_contract_id = &i
	m.addemployment_contract_id = nil
}

// EmploymentContractID returns the value of the "employment_contract_id" field in the mutation.
func (m *DismissalOrderBodyMutation) EmploymentContractID() (r int64, exists bool) {
	v := m.employment_contract_id
	if v == nil {
		return
	}
	return *v, true
}

// OldEmploymentContractID returns the old "employment_contract_id" field's value of the DismissalOrderBody entity.
// If the DismissalOrderBody object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DismissalOrderBodyMutation) OldEmploymentContractID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmploymentContractID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmploymentContractID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmploymentContractID: %w", err)
	}
	return oldValue.EmploymentContractID, nil
}

// AddEmploymentContractID adds i to the "employment_contract_id" field.
func (m *DismissalOrderBodyMutation) AddEmploymentContractID(i int64) {
	if m.addemployment_contract_id != nil {
		*m.addemployment_contract_id += i
	} else {
		m.addemployment_contract_id = &i
	}
}

// AddedEmploymentContractID returns the value that was added to the "employment_contract_id" field in this mutation.
func (m *DismissalOrderBodyMutation) AddedEmploymentContractID() (r int64, exists bool) {
	v := m.addemployment_contract_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetEmploymentContractID resets all changes to the "employment_contract_id" field.
func (m *DismissalOrderBodyMutation) ResetEmploymentContractID() {
	m.employment_contract_id = nil
	m.addemployment_contract_id = nil
}

// SetDepartmentID sets the "department_id" field.
func (m *DismissalOrderBodyMutation) SetDepartmentID(i int64) {
	m.department_id = &i
	m.adddepartment_id = nil
}

// DepartmentID returns the value of the "department_id" field in the mutation.
func (m *DismissalOrderBodyMutation) DepartmentID() (r int64, exists bool) {
	v := m.department_id
	if v == nil {
		return
	}
	return *v, true
}

// OldDepartmentID returns the old "department_id" field's value of the DismissalOrderBody entity.
// If the DismissalOrderBody object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DismissalOrderBodyMutation) OldDepartmentID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDepartmentID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDepartmentID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDepartmentID: %w", err)
	}
	return oldValue.DepartmentID, nil
}

// AddDepartmentID adds i to the "department_id" field.
func (m *DismissalOrderBodyMutation) AddDepartmentID(i int64) {
	if m.adddepartment_id != nil {
		*m.adddepartment_id += i
	} else {
		m.adddepartment_id = &i
	}
}

// AddedDepartmentID returns the value that was added to the "department_id" field in this mutation.
func (m *DismissalOrderBodyMutation) AddedDepartmentID() (r int64, exists bool) {
	v := m.adddepartment_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetDepartmentID resets all changes to the "department_id" field.
func (m *DismissalOrderBodyMutation) ResetDepartmentID() {
	m.department_id = nil
	m.adddepartment_id = nil
}

// SetPositionID sets the "position_id" field.
func (m *DismissalOrderBodyMutation) SetPositionID(i int64) {
	m.position_id = &i
	m.addposition_id = nil
}

// PositionID returns the value of the "position_id" field in the mutation.
func (m *DismissalOrderBodyMutation) PositionID() (r int64, exists bool) {
	v := m.position_id
	if v == nil {
		return
	}
	return *v, true
}

// OldPositionID returns the old "position_id" field's value of the DismissalOrderBody entity.
// If the DismissalOrderBody object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DismissalOrderBodyMutation) OldPositionID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPositionID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPositionID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPositionID: %w", err)
	}
	return oldValue.PositionID, nil
}

// AddPositionID adds i to the "position_id" field.
func (m *DismissalOrderBodyMutation) AddPositionID(i int64) {
	if m.addposition_id != nil {
		*m.addposition_id += i
	} else {
		m.addposition_id = &i
	}
}

// AddedPositionID returns the value that was added to the "position_id" field in this mutation.
func (m *DismissalOrderBodyMutation) AddedPositionID() (r int64, exists bool) {
	v := m.addposition_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetPositionID resets all changes to the "position_id" field.
func (m *DismissalOrderBodyMutation) ResetPositionID() {
	m.position_id = nil
	m.addposition_id = nil
}

// SetDismissalDate sets the "dismissal_date" field.
func (m *DismissalOrderBodyMutation) SetDismissalDate(t time.Time) {
	m.dismissal_date = &t
}

// DismissalDate returns the value of the "dismissal_date" field in the mutation.
func (m *DismissalOrderBodyMutation) DismissalDate() (r time.Time, exists bool) {
	v := m.dismissal_date
	if v == nil {
		return
	}
	return *v, true
}

// OldDismissalDate returns the old "dismissal_date" field's value of the DismissalOrderBody entity.
// If the DismissalOrderBody object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DismissalOrderBodyMutation) OldDismissalDate(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDismissalDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDismissalDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDismissalDate: %w", err)
	}
	return oldValue.DismissalDate, nil
}

// ResetDismissalDate resets all changes to the "dismissal_date" field.
func (m *DismissalOrderBodyMutation) ResetDismissalDate() {
	m.dismissal_date = nil
}

// SetDismissalGround sets the "dismissal_ground" field.
func (m *DismissalOrderBodyMutation) SetDismissalGround(s string) {
	m.dismissal_ground = &s
}

// DismissalGround returns the value of the "dismissal_ground" field in the mutation.
func (m *DismissalOrderBodyMutation) DismissalGround() (r string, exists bool) {
	v := m.dismissal_ground
	if v == nil {
		return
	}
	return *v, true
}

// OldDismissalGround returns the old "dismissal_ground" field's value of the DismissalOrderBody entity.
// If the DismissalOrderBody object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DismissalOrderBodyMutation) OldDismissalGround(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDismissalGround is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDismissalGround requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDismissalGround: %w", err)
	}
	return oldValue.DismissalGround, nil
}

// ResetDismissalGround resets all changes to the "dismissal_ground" field.
func (m *DismissalOrderBodyMutation) ResetDismissalGround() {
	m.dismissal_ground = nil
}

// SetDocNumber sets the "doc_number" field.
func (m *DismissalOrderBodyMutation) SetDocNumber(i int) {
	m.doc_number = &i
	m.adddoc_number = nil
}

// DocNumber returns the value of the "doc_number" field in the mutation.
func (m *DismissalOrderBodyMutation) DocNumber() (r int, exists bool) {
	v := m.doc_number
	if v == nil {
		return
	}
	return *v, true
}

// OldDocNumber returns the old "doc_number" field's value of the DismissalOrderBody entity.
// If the DismissalOrderBody object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DismissalOrderBodyMutation) OldDocNumber(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDocNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDocNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDocNumber: %w", err)
	}
	return oldValue.DocNumber, nil
}

// AddDocNumber adds i to the "doc_number" field.
func (m *DismissalOrderBodyMutation) AddDocNumber(i int) {
	if m.adddoc_number != nil {
		*m.adddoc_number += i
	} else {
		m.adddoc_number = &i
	}
}

// AddedDocNumber returns the value that was added to the "doc_number" field in this mutation.
func (m *DismissalOrderBodyMutation) AddedDocNumber() (r int, exists bool) {
	v := m.adddoc_number
	if v == nil {
		return
	}
	return *v, true
}

// ClearDocNumber clears the value of the "doc_number" field.
func (m *DismissalOrderBodyMutation) ClearDocNumber() {
	m.doc_number = nil
	m.adddoc_number = nil
	m.clearedFields[dismissalorderbody.FieldDocNumber] = struct{}{}
}

// DocNumberCleared returns if the "doc_number" field was cleared in this mutation.
func (m *DismissalOrderBodyMutation) DocNumberCleared() bool {
	_, ok := m.clearedFields[dismissalorderbody.FieldDocNumber]
	return ok
}

// ResetDocNumber resets all changes to the "doc_number" field.
func (m *DismissalOrderBodyMutation) ResetDocNumber() {
	m.doc_number = nil
	m.adddoc_number = nil
	delete(m.clearedFields, dismissalorderbody.FieldDocNumber)
}

// SetDocDate sets the "doc_date" field.
func (m *DismissalOrderBodyMutation) SetDocDate(t time.Time) {
	m.doc_date = &t
	m.adddoc_date = nil
}

// DocDate returns the value of the "doc_date" field in the mutation.
func (m *DismissalOrderBodyMutation) DocDate() (r time.Time, exists bool) {
	v := m.doc_date
	if v == nil {
		return
	}
	return *v, true
}

// OldDocDate returns the old "doc_date" field's value of the DismissalOrderBody entity.
// If the DismissalOrderBody object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DismissalOrderBodyMutation) OldDocDate(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDocDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDocDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDocDate: %w", err)
	}
	return oldValue.DocDate, nil
}

// AddDocDate sets the "doc_date" field to the provided time.
// (Note: originally generated for numeric fields; adapted for time fields.)
func (m *DismissalOrderBodyMutation) AddDocDate(t time.Time) {
	if m.adddoc_date != nil {
		*m.adddoc_date = t
	} else {
		m.adddoc_date = &t
	}
}

// AddedDocDate returns the value that was set to the "doc_date" field in this mutation.
func (m *DismissalOrderBodyMutation) AddedDocDate() (r time.Time, exists bool) {
	v := m.adddoc_date
	if v == nil {
		return
	}
	return *v, true
}

// ClearDocDate clears the value of the "doc_date" field.
func (m *DismissalOrderBodyMutation) ClearDocDate() {
	m.doc_date = nil
	m.adddoc_date = nil
	m.clearedFields[dismissalorderbody.FieldDocDate] = struct{}{}
}

// DocDateCleared returns if the "doc_date" field was cleared in this mutation.
func (m *DismissalOrderBodyMutation) DocDateCleared() bool {
	_, ok := m.clearedFields[dismissalorderbody.FieldDocDate]
	return ok
}

// ResetDocDate resets all changes to the "doc_date" field.
func (m *DismissalOrderBodyMutation) ResetDocDate() {
	m.doc_date = nil
	m.adddoc_date = nil
	delete(m.clearedFields, dismissalorderbody.FieldDocDate)
}

// SetCreatedAt sets the "created_at" field.
func (m *DismissalOrderBodyMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *DismissalOrderBodyMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the DismissalOrderBody entity.
// If the DismissalOrderBody object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DismissalOrderBodyMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *DismissalOrderBodyMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *DismissalOrderBodyMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *DismissalOrderBodyMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the DismissalOrderBody entity.
// If the DismissalOrderBody object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DismissalOrderBodyMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *DismissalOrderBodyMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetHeaderID sets the "header" edge to the DismissalOrderHeader entity by id.
func (m *DismissalOrderBodyMutation) SetHeaderID(id int64) {
	m.header = &id
}

// ClearHeader clears the "header" edge to the DismissalOrderHeader entity.
func (m *DismissalOrderBodyMutation) ClearHeader() {
	m.clearedheader = true
	m.clearedFields[dismissalorderbody.FieldDismissalOrderHeaderID] = struct{}{}
}

// HeaderCleared reports if the "header" edge to the DismissalOrderHeader entity was cleared.
func (m *DismissalOrderBodyMutation) HeaderCleared() bool {
	return m.clearedheader
}

// HeaderID returns the "header" edge ID in the mutation.
func (m *DismissalOrderBodyMutation) HeaderID() (id int64, exists bool) {
	if m.header != nil {
		return *m.header, true
	}
	return
}

// HeaderIDs returns the "header" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// HeaderID instead. It exists only for internal usage by the builders.
func (m *DismissalOrderBodyMutation) HeaderIDs() (ids []int64) {
	if id := m.header; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetHeader resets all changes to the "header" edge.
func (m *DismissalOrderBodyMutation) ResetHeader() {
	m.header = nil
	m.clearedheader = false
}

// Where appends a list predicates to the DismissalOrderBodyMutation builder.
func (m *DismissalOrderBodyMutation) Where(ps ...predicate.DismissalOrderBody) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DismissalOrderBodyMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DismissalOrderBodyMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.DismissalOrderBody, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DismissalOrderBodyMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DismissalOrderBodyMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (DismissalOrderBody).
func (m *DismissalOrderBodyMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DismissalOrderBodyMutation) Fields() []string {
	fields := make([]string, 0, 10)
	if m.header != nil {
		fields = append(fields, dismissalorderbody.FieldDismissalOrderHeaderID)
	}
	if m.employment_contract_id != nil {
		fields = append(fields, dismissalorderbody.FieldEmploymentContractID)
	}
	if m.department_id != nil {
		fields = append(fields, dismissalorderbody.FieldDepartmentID)
	}
	if m.position_id != nil {
		fields = append(fields, dismissalorderbody.FieldPositionID)
	}
	if m.dismissal_date != nil {
		fields = append(fields, dismissalorderbody.FieldDismissalDate)
	}
	if m.dismissal_ground != nil {
		fields = append(fields, dismissalorderbody.FieldDismissalGround)
	}
	if m.doc_number != nil {
		fields = append(fields, dismissalorderbody.FieldDocNumber)
	}
	if m.doc_date != nil {
		fields = append(fields, dismissalorderbody.FieldDocDate)
	}
	if m.created_at != nil {
		fields = append(fields, dismissalorderbody.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, dismissalorderbody.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DismissalOrderBodyMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case dismissalorderbody.FieldDismissalOrderHeaderID:
		return m.DismissalOrderHeaderID()
	case dismissalorderbody.FieldEmploymentContractID:
		return m.EmploymentContractID()
	case dismissalorderbody.FieldDepartmentID:
		return m.DepartmentID()
	case dismissalorderbody.FieldPositionID:
		return m.PositionID()
	case dismissalorderbody.FieldDismissalDate:
		return m.DismissalDate()
	case dismissalorderbody.FieldDismissalGround:
		return m.DismissalGround()
	case dismissalorderbody.FieldDocNumber:
		return m.DocNumber()
	case dismissalorderbody.FieldDocDate:
		return m.DocDate()
	case dismissalorderbody.FieldCreatedAt:
		return m.CreatedAt()
	case dismissalorderbody.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DismissalOrderBodyMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case dismissalorderbody.FieldDismissalOrderHeaderID:
		return m.OldDismissalOrderHeaderID(ctx)
	case dismissalorderbody.FieldEmploymentContractID:
		return m.OldEmploymentContractID(ctx)
	case dismissalorderbody.FieldDepartmentID:
		return m.OldDepartmentID(ctx)
	case dismissalorderbody.FieldPositionID:
		return m.OldPositionID(ctx)
	case dismissalorderbody.FieldDismissalDate:
		return m.OldDismissalDate(ctx)
	case dismissalorderbody.FieldDismissalGround:
		return m.OldDismissalGround(ctx)
	case dismissalorderbody.FieldDocNumber:
		return m.OldDocNumber(ctx)
	case dismissalorderbody.FieldDocDate:
		return m.OldDocDate(ctx)
	case dismissalorderbody.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case dismissalorderbody.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown DismissalOrderBody field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DismissalOrderBodyMutation) SetField(name string, value ent.Value) error {
	switch name {
	case dismissalorderbody.FieldDismissalOrderHeaderID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDismissalOrderHeaderID(v)
		return nil
	case dismissalorderbody.FieldEmploymentContractID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmploymentContractID(v)
		return nil
	case dismissalorderbody.FieldDepartmentID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDepartmentID(v)
		return nil
	case dismissalorderbody.FieldPositionID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPositionID(v)
		return nil
	case dismissalorderbody.FieldDismissalDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDismissalDate(v)
		return nil
	case dismissalorderbody.FieldDismissalGround:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDismissalGround(v)
		return nil
	case dismissalorderbody.FieldDocNumber:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDocNumber(v)
		return nil
	case dismissalorderbody.FieldDocDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDocDate(v)
		return nil
	case dismissalorderbody.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case dismissalorderbody.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown DismissalOrderBody field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DismissalOrderBodyMutation) AddedFields() []string {
	var fields []string
	if m.addemployment_contract_id != nil {
		fields = append(fields, dismissalorderbody.FieldEmploymentContractID)
	}
	if m.adddepartment_id != nil {
		fields = append(fields, dismissalorderbody.FieldDepartmentID)
	}
	if m.addposition_id != nil {
		fields = append(fields, dismissalorderbody.FieldPositionID)
	}
	if m.adddoc_number != nil {
		fields = append(fields, dismissalorderbody.FieldDocNumber)
	}
	if m.adddoc_date != nil {
		fields = append(fields, dismissalorderbody.FieldDocDate)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DismissalOrderBodyMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case dismissalorderbody.FieldEmploymentContractID:
		return m.AddedEmploymentContractID()
	case dismissalorderbody.FieldDepartmentID:
		return m.AddedDepartmentID()
	case dismissalorderbody.FieldPositionID:
		return m.AddedPositionID()
	case dismissalorderbody.FieldDocNumber:
		return m.AddedDocNumber()
	case dismissalorderbody.FieldDocDate:
		return m.AddedDocDate()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DismissalOrderBodyMutation) AddField(name string, value ent.Value) error {
	switch name {
	case dismissalorderbody.FieldEmploymentContractID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddEmploymentContractID(v)
		return nil
	case dismissalorderbody.FieldDepartmentID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDepartmentID(v)
		return nil
	case dismissalorderbody.FieldPositionID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPositionID(v)
		return nil
	case dismissalorderbody.FieldDocNumber:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDocNumber(v)
		return nil
	case dismissalorderbody.FieldDocDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDocDate(v)
		return nil
	}
	return fmt.Errorf("unknown DismissalOrderBody numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DismissalOrderBodyMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(dismissalorderbody.FieldDocNumber) {
		fields = append(fields, dismissalorderbody.FieldDocNumber)
	}
	if m.FieldCleared(dismissalorderbody.FieldDocDate) {
		fields = append(fields, dismissalorderbody.FieldDocDate)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DismissalOrderBodyMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DismissalOrderBodyMutation) ClearField(name string) error {
	switch name {
	case dismissalorderbody.FieldDocNumber:
		m.ClearDocNumber()
		return nil
	case dismissalorderbody.FieldDocDate:
		m.ClearDocDate()
		return nil
	}
	return fmt.Errorf("unknown DismissalOrderBody nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DismissalOrderBodyMutation) ResetField(name string) error {
	switch name {
	case dismissalorderbody.FieldDismissalOrderHeaderID:
		m.ResetDismissalOrderHeaderID()
		return nil
	case dismissalorderbody.FieldEmploymentContractID:
		m.ResetEmploymentContractID()
		return nil
	case dismissalorderbody.FieldDepartmentID:
		m.ResetDepartmentID()
		return nil
	case dismissalorderbody.FieldPositionID:
		m.ResetPositionID()
		return nil
	case dismissalorderbody.FieldDismissalDate:
		m.ResetDismissalDate()
		return nil
	case dismissalorderbody.FieldDismissalGround:
		m.ResetDismissalGround()
		return nil
	case dismissalorderbody.FieldDocNumber:
		m.ResetDocNumber()
		return nil
	case dismissalorderbody.FieldDocDate:
		m.ResetDocDate()
		return nil
	case dismissalorderbody.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case dismissalorderbody.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown DismissalOrderBody field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DismissalOrderBodyMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.header != nil {
		edges = append(edges, dismissalorderbody.EdgeHeader)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DismissalOrderBodyMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case dismissalorderbody.EdgeHeader:
		if id := m.header; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DismissalOrderBodyMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DismissalOrderBodyMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DismissalOrderBodyMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedheader {
		edges = append(edges, dismissalorderbody.EdgeHeader)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DismissalOrderBodyMutation) EdgeCleared(name string) bool {
	switch name {
	case dismissalorderbody.EdgeHeader:
		return m.clearedheader
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DismissalOrderBodyMutation) ClearEdge(name string) error {
	switch name {
	case dismissalorderbody.EdgeHeader:
		m.ClearHeader()
		return nil
	}
	return fmt.Errorf("unknown DismissalOrderBody unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DismissalOrderBodyMutation) ResetEdge(name string) error {
	switch name {
	case dismissalorderbody.EdgeHeader:
		m.ResetHeader()
		return nil
	}
	return fmt.Errorf("unknown DismissalOrderBody edge %s", name)
}

// DismissalOrderHeaderMutation represents an operation that mutates the DismissalOrderHeader nodes in the graph.
type DismissalOrderHeaderMutation struct {
	config
	op                 Op
	typ                string
	id                 *int64
	number             *string
	preparation_date   *time.Time
	organization_id    *int64
	addorganization_id *int64
	created_at         *time.Time
	updated_at         *time.Time
	clearedFields      map[string]struct{}
	bodies             map[int64]struct{}
	removedbodies      map[int64]struct{}
	clearedbodies      bool
	done               bool
	oldValue           func(context.Context) (*DismissalOrderHeader, error)
	predicates         []predicate.DismissalOrderHeader
}

var _ ent.Mutation = (*DismissalOrderHeaderMutation)(nil)

// dismissalorderheaderOption allows management of the mutation configuration using functional options.
type dismissalorderheaderOption func(*DismissalOrderHeaderMutation)

// newDismissalOrderHeaderMutation creates new mutation for the DismissalOrderHeader entity.
func newDismissalOrderHeaderMutation(c config, op Op, opts ...dismissalorderheaderOption) *DismissalOrderHeaderMutation {
	m := &DismissalOrderHeaderMutation{
		config:        c,
		op:            op,
		typ:           TypeDismissalOrderHeader,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDismissalOrderHeaderID sets the ID field of the mutation.
func withDismissalOrderHeaderID(id int64) dismissalorderheaderOption {
	return func(m *DismissalOrderHeaderMutation) {
		var (
			err   error
			once  sync.Once
			value *DismissalOrderHeader
		)
		m.oldValue = func(ctx context.Context) (*DismissalOrderHeader, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().DismissalOrderHeader.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDismissalOrderHeader sets the old DismissalOrderHeader of the mutation.
func withDismissalOrderHeader(node *DismissalOrderHeader) dismissalorderheaderOption {
	return func(m *DismissalOrderHeaderMutation) {
		m.oldValue = func(context.Context) (*DismissalOrderHeader, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DismissalOrderHeaderMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DismissalOrderHeaderMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of DismissalOrderHeader entities.
func (m *DismissalOrderHeaderMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DismissalOrderHeaderMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DismissalOrderHeaderMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().DismissalOrderHeader.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetNumber sets the "number" field.
func (m *DismissalOrderHeaderMutation) SetNumber(s string) {
	m.number = &s
}

// Number returns the value of the "number" field in the mutation.
func (m *DismissalOrderHeaderMutation) Number() (r string, exists bool) {
	v := m.number
	if v == nil {
		return
	}
	return *v, true
}

// OldNumber returns the old "number" field's value of the DismissalOrderHeader entity.
// If the DismissalOrderHeader object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DismissalOrderHeaderMutation) OldNumber(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNumber: %w", err)
	}
	return oldValue.Number, nil
}

// ResetNumber resets all changes to the "number" field.
func (m *DismissalOrderHeaderMutation) ResetNumber() {
	m.number = nil
}

// SetPreparationDate sets the "preparation_date" field.
func (m *DismissalOrderHeaderMutation) SetPreparationDate(t time.Time) {
	m.preparation_date = &t
}

// PreparationDate returns the value of the "preparation_date" field in the mutation.
func (m *DismissalOrderHeaderMutation) PreparationDate() (r time.Time, exists bool) {
	v := m.preparation_date
	if v == nil {
		return
	}
	return *v, true
}

// OldPreparationDate returns the old "preparation_date" field's value of the DismissalOrderHeader entity.
// If the DismissalOrderHeader object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DismissalOrderHeaderMutation) OldPreparationDate(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPreparationDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPreparationDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPreparationDate: %w", err)
	}
	return oldValue.PreparationDate, nil
}

// ResetPreparationDate resets all changes to the "preparation_date" field.
func (m *DismissalOrderHeaderMutation) ResetPreparationDate() {
	m.preparation_date = nil
}

// SetOrganizationID sets the "organization_id" field.
func (m *DismissalOrderHeaderMutation) SetOrganizationID(i int64) {
	m.organization_id = &i
	m.addorganization_id = nil
}

// OrganizationID returns the value of the "organization_id" field in the mutation.
func (m *DismissalOrderHeaderMutation) OrganizationID() (r int64, exists bool) {
	v := m.organization_id
	if v == nil {
		return
	}
	return *v, true
}

// OldOrganizationID returns the old "organization_id" field's value of the DismissalOrderHeader entity.
// If the DismissalOrderHeader object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DismissalOrderHeaderMutation) OldOrganizationID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOrganizationID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOrganizationID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOrganizationID: %w", err)
	}
	return oldValue.OrganizationID, nil
}

// AddOrganizationID adds i to the "organization_id" field.
func (m *DismissalOrderHeaderMutation) AddOrganizationID(i int64) {
	if m.addorganization_id != nil {
		*m.addorganization_id += i
	} else {
		m.addorganization_id = &i
	}
}

// AddedOrganizationID returns the value that was added to the "organization_id" field in this mutation.
func (m *DismissalOrderHeaderMutation) AddedOrganizationID() (r int64, exists bool) {
	v := m.addorganization_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetOrganizationID resets all changes to the "organization_id" field.
func (m *DismissalOrderHeaderMutation) ResetOrganizationID() {
	m.organization_id = nil
	m.addorganization_id = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *DismissalOrderHeaderMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *DismissalOrderHeaderMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the DismissalOrderHeader entity.
// If the DismissalOrderHeader object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DismissalOrderHeaderMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *DismissalOrderHeaderMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *DismissalOrderHeaderMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *DismissalOrderHeaderMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the DismissalOrderHeader entity.
// If the DismissalOrderHeader object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DismissalOrderHeaderMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *DismissalOrderHeaderMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddBodyIDs adds the "bodies" edge to the DismissalOrderBody entity by ids.
func (m *DismissalOrderHeaderMutation) AddBodyIDs(ids ...int64) {
	if m.bodies == nil {
		m.bodies = make(map[int64]struct{})
	}
	for i := range ids {
		m.bodies[ids[i]] = struct{}{}
	}
}

// ClearBodies clears the "bodies" edge to the DismissalOrderBody entity.
func (m *DismissalOrderHeaderMutation) ClearBodies() {
	m.clearedbodies = true
}

// BodiesCleared reports if the "bodies" edge to the DismissalOrderBody entity was cleared.
func (m *DismissalOrderHeaderMutation) BodiesCleared() bool {
	return m.clearedbodies
}

// RemoveBodyIDs removes the "bodies" edge to the DismissalOrderBody entity by IDs.
func (m *DismissalOrderHeaderMutation) RemoveBodyIDs(ids ...int64) {
	if m.removedbodies == nil {
		m.removedbodies = make(map[int64]struct{})
	}
	for i := range ids {
		delete(m.bodies, ids[i])
		m.removedbodies[ids[i]] = struct{}{}
	}
}

// RemovedBodies returns the removed IDs of the "bodies" edge to the DismissalOrderBody entity.
func (m *DismissalOrderHeaderMutation) RemovedBodiesIDs() (ids []int64) {
	for id := range m.removedbodies {
		ids = append(ids, id)
	}
	return
}

// BodiesIDs returns the "bodies" edge IDs in the mutation.
func (m *DismissalOrderHeaderMutation) BodiesIDs() (ids []int64) {
	for id := range m.bodies {
		ids = append(ids, id)
	}
	return
}

// ResetBodies resets all changes to the "bodies" edge.
func (m *DismissalOrderHeaderMutation) ResetBodies() {
	m.bodies = nil
	m.clearedbodies = false
	m.removedbodies = nil
}

// Where appends a list predicates to the DismissalOrderHeaderMutation builder.
func (m *DismissalOrderHeaderMutation) Where(ps ...predicate.DismissalOrderHeader) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DismissalOrderHeaderMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DismissalOrderHeaderMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.DismissalOrderHeader, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DismissalOrderHeaderMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DismissalOrderHeaderMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (DismissalOrderHeader).
func (m *DismissalOrderHeaderMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DismissalOrderHeaderMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.number != nil {
		fields = append(fields, dismissalorderheader.FieldNumber)
	}
	if m.preparation_date != nil {
		fields = append(fields, dismissalorderheader.FieldPreparationDate)
	}
	if m.organization_id != nil {
		fields = append(fields, dismissalorderheader.FieldOrganizationID)
	}
	if m.created_at != nil {
		fields = append(fields, dismissalorderheader.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, dismissalorderheader.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DismissalOrderHeaderMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case dismissalorderheader.FieldNumber:
		return m.Number()
	case dismissalorderheader.FieldPreparationDate:
		return m.PreparationDate()
	case dismissalorderheader.FieldOrganizationID:
		return m.OrganizationID()
	case dismissalorderheader.FieldCreatedAt:
		return m.CreatedAt()
	case dismissalorderheader.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DismissalOrderHeaderMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case dismissalorderheader.FieldNumber:
		return m.OldNumber(ctx)
	case dismissalorderheader.FieldPreparationDate:
		return m.OldPreparationDate(ctx)
	case dismissalorderheader.FieldOrganizationID:
		return m.OldOrganizationID(ctx)
	case dismissalorderheader.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case dismissalorderheader.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown DismissalOrderHeader field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DismissalOrderHeaderMutation) SetField(name string, value ent.Value) error {
	switch name {
	case dismissalorderheader.FieldNumber:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNumber(v)
		return nil
	case dismissalorderheader.FieldPreparationDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPreparationDate(v)
		return nil
	case dismissalorderheader.FieldOrganizationID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOrganizationID(v)
		return nil
	case dismissalorderheader.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case dismissalorderheader.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown DismissalOrderHeader field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DismissalOrderHeaderMutation) AddedFields() []string {
	var fields []string
	if m.addorganization_id != nil {
		fields = append(fields, dismissalorderheader.FieldOrganizationID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DismissalOrderHeaderMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case dismissalorderheader.FieldOrganizationID:
		return m.AddedOrganizationID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DismissalOrderHeaderMutation) AddField(name string, value ent.Value) error {
	switch name {
	case dismissalorderheader.FieldOrganizationID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddOrganizationID(v)
		return nil
	}
	return fmt.Errorf("unknown DismissalOrderHeader numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DismissalOrderHeaderMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DismissalOrderHeaderMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DismissalOrderHeaderMutation) ClearField(name string) error {
	return fmt.Errorf("unknown DismissalOrderHeader nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DismissalOrderHeaderMutation) ResetField(name string) error {
	switch name {
	case dismissalorderheader.FieldNumber:
		m.ResetNumber()
		return nil
	case dismissalorderheader.FieldPreparationDate:
		m.ResetPreparationDate()
		return nil
	case dismissalorderheader.FieldOrganizationID:
		m.ResetOrganizationID()
		return nil
	case dismissalorderheader.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case dismissalorderheader.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown DismissalOrderHeader field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DismissalOrderHeaderMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.bodies != nil {
		edges = append(edges, dismissalorderheader.EdgeBodies)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DismissalOrderHeaderMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case dismissalorderheader.EdgeBodies:
		ids := make([]ent.Value, 0, len(m.bodies))
		for id := range m.bodies {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DismissalOrderHeaderMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedbodies != nil {
		edges = append(edges, dismissalorderheader.EdgeBodies)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DismissalOrderHeaderMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case dismissalorderheader.EdgeBodies:
		ids := make([]ent.Value, 0, len(m.removedbodies))
		for id := range m.removedbodies {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DismissalOrderHeaderMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedbodies {
		edges = append(edges, dismissalorderheader.EdgeBodies)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DismissalOrderHeaderMutation) EdgeCleared(name string) bool {
	switch name {
	case dismissalorderheader.EdgeBodies:
		return m.clearedbodies
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DismissalOrderHeaderMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown DismissalOrderHeader unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DismissalOrderHeaderMutation) ResetEdge(name string) error {
	switch name {
	case dismissalorderheader.EdgeBodies:
		m.ResetBodies()
		return nil
	}
	return fmt.Errorf("unknown DismissalOrderHeader edge %s", name)
}
