// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/example/micro/dismissal-order/ent/dismissalorderbody"
	"github.com/example/micro/dismissal-order/ent/dismissalorderheader"
	"github.com/example/micro/dismissal-order/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dismissalorderbodyFields := schema.DismissalOrderBody{}.Fields()
	_ = dismissalorderbodyFields
	// dismissalorderbodyDescDismissalGround is the schema descriptor for dismissal_ground field.
	dismissalorderbodyDescDismissalGround := dismissalorderbodyFields[6].Descriptor()
	// dismissalorderbody.DismissalGroundValidator is a validator for the "dismissal_ground" field. It is called by the builders before save.
	dismissalorderbody.DismissalGroundValidator = func() func(string) error {
		validators := dismissalorderbodyDescDismissalGround.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(dismissal_ground string) error {
			for _, fn := range fns {
				if err := fn(dismissal_ground); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dismissalorderbodyDescCreatedAt is the schema descriptor for created_at field.
	dismissalorderbodyDescCreatedAt := dismissalorderbodyFields[9].Descriptor()
	// dismissalorderbody.DefaultCreatedAt holds the default value on creation for the created_at field.
	dismissalorderbody.DefaultCreatedAt = dismissalorderbodyDescCreatedAt.Default.(func() time.Time)
	// dismissalorderbodyDescUpdatedAt is the schema descriptor for updated_at field.
	dismissalorderbodyDescUpdatedAt := dismissalorderbodyFields[10].Descriptor()
	// dismissalorderbody.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dismissalorderbody.DefaultUpdatedAt = dismissalorderbodyDescUpdatedAt.Default.(func() time.Time)
	// dismissalorderbody.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dismissalorderbody.UpdateDefaultUpdatedAt = dismissalorderbodyDescUpdatedAt.UpdateDefault.(func() time.Time)
	dismissalorderheaderFields := schema.DismissalOrderHeader{}.Fields()
	_ = dismissalorderheaderFields
	// dismissalorderheaderDescNumber is the schema descriptor for number field.
	dismissalorderheaderDescNumber := dismissalorderheaderFields[1].Descriptor()
	// dismissalorderheader.NumberValidator is a validator for the "number" field. It is called by the builders before save.
	dismissalorderheader.NumberValidator = func() func(string) error {
		validators := dismissalorderheaderDescNumber.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(number string) error {
			for _, fn := range fns {
				if err := fn(number); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dismissalorderheaderDescCreatedAt is the schema descriptor for created_at field.
	dismissalorderheaderDescCreatedAt := dismissalorderheaderFields[4].Descriptor()
	// dismissalorderheader.DefaultCreatedAt holds the default value on creation for the created_at field.
	dismissalorderheader.DefaultCreatedAt = dismissalorderheaderDescCreatedAt.Default.(func() time.Time)
	// dismissalorderheaderDescUpdatedAt is the schema descriptor for updated_at field.
	dismissalorderheaderDescUpdatedAt := dismissalorderheaderFields[5].Descriptor()
	// dismissalorderheader.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dismissalorderheader.DefaultUpdatedAt = dismissalorderheaderDescUpdatedAt.Default.(func() time.Time)
	// dismissalorderheader.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dismissalorderheader.UpdateDefaultUpdatedAt = dismissalorderheaderDescUpdatedAt.UpdateDefault.(func() time.Time)
}
