// Code generated by ent, DO NOT EDIT.

package employmentcontract

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/example/micro/employment-contracts/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldID, id))
}

// Number applies equality check predicate on the "number" field. It's identical to NumberEQ.
func Number(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldNumber, v))
}

// PersonnelNumber applies equality check predicate on the "personnel_number" field. It's identical to PersonnelNumberEQ.
func PersonnelNumber(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldPersonnelNumber, v))
}

// ConclusionDate applies equality check predicate on the "conclusion_date" field. It's identical to ConclusionDateEQ.
func ConclusionDate(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldConclusionDate, v))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldOrganizationID, v))
}

// RepresentativeID applies equality check predicate on the "representative_id" field. It's identical to RepresentativeIDEQ.
func RepresentativeID(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldRepresentativeID, v))
}

// EmployeeID applies equality check predicate on the "employee_id" field. It's identical to EmployeeIDEQ.
func EmployeeID(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldEmployeeID, v))
}

// DepartmentID applies equality check predicate on the "department_id" field. It's identical to DepartmentIDEQ.
func DepartmentID(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldDepartmentID, v))
}

// PositionID applies equality check predicate on the "position_id" field. It's identical to PositionIDEQ.
func PositionID(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldPositionID, v))
}

// ConditionsClass applies equality check predicate on the "conditions_class" field. It's identical to ConditionsClassEQ.
func ConditionsClass(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldConditionsClass, v))
}

// WorkDateFrom applies equality check predicate on the "work_date_from" field. It's identical to WorkDateFromEQ.
func WorkDateFrom(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldWorkDateFrom, v))
}

// WorkDateTo applies equality check predicate on the "work_date_to" field. It's identical to WorkDateToEQ.
func WorkDateTo(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldWorkDateTo, v))
}

// ProbationMonths applies equality check predicate on the "probation_months" field. It's identical to ProbationMonthsEQ.
func ProbationMonths(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldProbationMonths, v))
}

// Salary applies equality check predicate on the "salary" field. It's identical to SalaryEQ.
func Salary(v float64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldSalary, v))
}

// WorkHoursFrom applies equality check predicate on the "work_hours_from" field. It's identical to WorkHoursFromEQ.
func WorkHoursFrom(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldWorkHoursFrom, v))
}

// WorkHoursTo applies equality check predicate on the "work_hours_to" field. It's identical to WorkHoursToEQ.
func WorkHoursTo(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldWorkHoursTo, v))
}

// BreakFrom applies equality check predicate on the "break_from" field. It's identical to BreakFromEQ.
func BreakFrom(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldBreakFrom, v))
}

// BreakTo applies equality check predicate on the "break_to" field. It's identical to BreakToEQ.
func BreakTo(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldBreakTo, v))
}

// PaidLeaveDays applies equality check predicate on the "paid_leave_days" field. It's identical to PaidLeaveDaysEQ.
func PaidLeaveDays(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldPaidLeaveDays, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldUpdatedAt, v))
}

// NumberEQ applies the EQ predicate on the "number" field.
func NumberEQ(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldNumber, v))
}

// NumberNEQ applies the NEQ predicate on the "number" field.
func NumberNEQ(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldNumber, v))
}

// NumberIn applies the In predicate on the "number" field.
func NumberIn(vs ...string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldNumber, vs...))
}

// NumberNotIn applies the NotIn predicate on the "number" field.
func NumberNotIn(vs ...string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldNumber, vs...))
}

// NumberGT applies the GT predicate on the "number" field.
func NumberGT(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldNumber, v))
}

// NumberGTE applies the GTE predicate on the "number" field.
func NumberGTE(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldNumber, v))
}

// NumberLT applies the LT predicate on the "number" field.
func NumberLT(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldNumber, v))
}

// NumberLTE applies the LTE predicate on the "number" field.
func NumberLTE(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldNumber, v))
}

// NumberContains applies the Contains predicate on the "number" field.
func NumberContains(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldContains(FieldNumber, v))
}

// NumberHasPrefix applies the HasPrefix predicate on the "number" field.
func NumberHasPrefix(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldHasPrefix(FieldNumber, v))
}

// NumberHasSuffix applies the HasSuffix predicate on the "number" field.
func NumberHasSuffix(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldHasSuffix(FieldNumber, v))
}

// NumberEqualFold applies the EqualFold predicate on the "number" field.
func NumberEqualFold(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEqualFold(FieldNumber, v))
}

// NumberContainsFold applies the ContainsFold predicate on the "number" field.
func NumberContainsFold(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldContainsFold(FieldNumber, v))
}

// PersonnelNumberEQ applies the EQ predicate on the "personnel_number" field.
func PersonnelNumberEQ(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldPersonnelNumber, v))
}

// PersonnelNumberNEQ applies the NEQ predicate on the "personnel_number" field.
func PersonnelNumberNEQ(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldPersonnelNumber, v))
}

// PersonnelNumberIn applies the In predicate on the "personnel_number" field.
func PersonnelNumberIn(vs ...string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldPersonnelNumber, vs...))
}

// PersonnelNumberNotIn applies the NotIn predicate on the "personnel_number" field.
func PersonnelNumberNotIn(vs ...string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldPersonnelNumber, vs...))
}

// PersonnelNumberGT applies the GT predicate on the "personnel_number" field.
func PersonnelNumberGT(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldPersonnelNumber, v))
}

// PersonnelNumberGTE applies the GTE predicate on the "personnel_number" field.
func PersonnelNumberGTE(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldPersonnelNumber, v))
}

// PersonnelNumberLT applies the LT predicate on the "personnel_number" field.
func PersonnelNumberLT(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldPersonnelNumber, v))
}

// PersonnelNumberLTE applies the LTE predicate on the "personnel_number" field.
func PersonnelNumberLTE(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldPersonnelNumber, v))
}

// PersonnelNumberContains applies the Contains predicate on the "personnel_number" field.
func PersonnelNumberContains(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldContains(FieldPersonnelNumber, v))
}

// PersonnelNumberHasPrefix applies the HasPrefix predicate on the "personnel_number" field.
func PersonnelNumberHasPrefix(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldHasPrefix(FieldPersonnelNumber, v))
}

// PersonnelNumberHasSuffix applies the HasSuffix predicate on the "personnel_number" field.
func PersonnelNumberHasSuffix(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldHasSuffix(FieldPersonnelNumber, v))
}

// PersonnelNumberEqualFold applies the EqualFold predicate on the "personnel_number" field.
func PersonnelNumberEqualFold(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEqualFold(FieldPersonnelNumber, v))
}

// PersonnelNumberContainsFold applies the ContainsFold predicate on the "personnel_number" field.
func PersonnelNumberContainsFold(v string) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldContainsFold(FieldPersonnelNumber, v))
}

// ConclusionDateEQ applies the EQ predicate on the "conclusion_date" field.
func ConclusionDateEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldConclusionDate, v))
}

// ConclusionDateNEQ applies the NEQ predicate on the "conclusion_date" field.
func ConclusionDateNEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldConclusionDate, v))
}

// ConclusionDateIn applies the In predicate on the "conclusion_date" field.
func ConclusionDateIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldConclusionDate, vs...))
}

// ConclusionDateNotIn applies the NotIn predicate on the "conclusion_date" field.
func ConclusionDateNotIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldConclusionDate, vs...))
}

// ConclusionDateGT applies the GT predicate on the "conclusion_date" field.
func ConclusionDateGT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldConclusionDate, v))
}

// ConclusionDateGTE applies the GTE predicate on the "conclusion_date" field.
func ConclusionDateGTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldConclusionDate, v))
}

// ConclusionDateLT applies the LT predicate on the "conclusion_date" field.
func ConclusionDateLT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldConclusionDate, v))
}

// ConclusionDateLTE applies the LTE predicate on the "conclusion_date" field.
func ConclusionDateLTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldConclusionDate, v))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// OrganizationIDGT applies the GT predicate on the "organization_id" field.
func OrganizationIDGT(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldOrganizationID, v))
}

// OrganizationIDGTE applies the GTE predicate on the "organization_id" field.
func OrganizationIDGTE(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldOrganizationID, v))
}

// OrganizationIDLT applies the LT predicate on the "organization_id" field.
func OrganizationIDLT(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldOrganizationID, v))
}

// OrganizationIDLTE applies the LTE predicate on the "organization_id" field.
func OrganizationIDLTE(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldOrganizationID, v))
}

// RepresentativeIDEQ applies the EQ predicate on the "representative_id" field.
func RepresentativeIDEQ(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldRepresentativeID, v))
}

// RepresentativeIDNEQ applies the NEQ predicate on the "representative_id" field.
func RepresentativeIDNEQ(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldRepresentativeID, v))
}

// RepresentativeIDIn applies the In predicate on the "representative_id" field.
func RepresentativeIDIn(vs ...int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldRepresentativeID, vs...))
}

// RepresentativeIDNotIn applies the NotIn predicate on the "representative_id" field.
func RepresentativeIDNotIn(vs ...int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldRepresentativeID, vs...))
}

// RepresentativeIDGT applies the GT predicate on the "representative_id" field.
func RepresentativeIDGT(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldRepresentativeID, v))
}

// RepresentativeIDGTE applies the GTE predicate on the "representative_id" field.
func RepresentativeIDGTE(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldRepresentativeID, v))
}

// RepresentativeIDLT applies the LT predicate on the "representative_id" field.
func RepresentativeIDLT(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldRepresentativeID, v))
}

// RepresentativeIDLTE applies the LTE predicate on the "representative_id" field.
func RepresentativeIDLTE(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldRepresentativeID, v))
}

// EmployeeIDEQ applies the EQ predicate on the "employee_id" field.
func EmployeeIDEQ(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldEmployeeID, v))
}

// EmployeeIDNEQ applies the NEQ predicate on the "employee_id" field.
func EmployeeIDNEQ(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldEmployeeID, v))
}

// EmployeeIDIn applies the In predicate on the "employee_id" field.
func EmployeeIDIn(vs ...int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldEmployeeID, vs...))
}

// EmployeeIDNotIn applies the NotIn predicate on the "employee_id" field.
func EmployeeIDNotIn(vs ...int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldEmployeeID, vs...))
}

// EmployeeIDGT applies the GT predicate on the "employee_id" field.
func EmployeeIDGT(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldEmployeeID, v))
}

// EmployeeIDGTE applies the GTE predicate on the "employee_id" field.
func EmployeeIDGTE(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldEmployeeID, v))
}

// EmployeeIDLT applies the LT predicate on the "employee_id" field.
func EmployeeIDLT(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldEmployeeID, v))
}

// EmployeeIDLTE applies the LTE predicate on the "employee_id" field.
func EmployeeIDLTE(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldEmployeeID, v))
}

// DepartmentIDEQ applies the EQ predicate on the "department_id" field.
func DepartmentIDEQ(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldDepartmentID, v))
}

// DepartmentIDNEQ applies the NEQ predicate on the "department_id" field.
func DepartmentIDNEQ(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldDepartmentID, v))
}

// DepartmentIDIn applies the In predicate on the "department_id" field.
func DepartmentIDIn(vs ...int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldDepartmentID, vs...))
}

// DepartmentIDNotIn applies the NotIn predicate on the "department_id" field.
func DepartmentIDNotIn(vs ...int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldDepartmentID, vs...))
}

// DepartmentIDGT applies the GT predicate on the "department_id" field.
func DepartmentIDGT(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldDepartmentID, v))
}

// DepartmentIDGTE applies the GTE predicate on the "department_id" field.
func DepartmentIDGTE(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldDepartmentID, v))
}

// DepartmentIDLT applies the LT predicate on the "department_id" field.
func DepartmentIDLT(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldDepartmentID, v))
}

// DepartmentIDLTE applies the LTE predicate on the "department_id" field.
func DepartmentIDLTE(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldDepartmentID, v))
}

// PositionIDEQ applies the EQ predicate on the "position_id" field.
func PositionIDEQ(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldPositionID, v))
}

// PositionIDNEQ applies the NEQ predicate on the "position_id" field.
func PositionIDNEQ(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldPositionID, v))
}

// PositionIDIn applies the In predicate on the "position_id" field.
func PositionIDIn(vs ...int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldPositionID, vs...))
}

// PositionIDNotIn applies the NotIn predicate on the "position_id" field.
func PositionIDNotIn(vs ...int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldPositionID, vs...))
}

// PositionIDGT applies the GT predicate on the "position_id" field.
func PositionIDGT(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldPositionID, v))
}

// PositionIDGTE applies the GTE predicate on the "position_id" field.
func PositionIDGTE(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldPositionID, v))
}

// PositionIDLT applies the LT predicate on the "position_id" field.
func PositionIDLT(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldPositionID, v))
}

// PositionIDLTE applies the LTE predicate on the "position_id" field.
func PositionIDLTE(v int64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldPositionID, v))
}

// ConditionsClassEQ applies the EQ predicate on the "conditions_class" field.
func ConditionsClassEQ(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldConditionsClass, v))
}

// ConditionsClassNEQ applies the NEQ predicate on the "conditions_class" field.
func ConditionsClassNEQ(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldConditionsClass, v))
}

// ConditionsClassIn applies the In predicate on the "conditions_class" field.
func ConditionsClassIn(vs ...int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldConditionsClass, vs...))
}

// ConditionsClassNotIn applies the NotIn predicate on the "conditions_class" field.
func ConditionsClassNotIn(vs ...int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldConditionsClass, vs...))
}

// ConditionsClassGT applies the GT predicate on the "conditions_class" field.
func ConditionsClassGT(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldConditionsClass, v))
}

// ConditionsClassGTE applies the GTE predicate on the "conditions_class" field.
func ConditionsClassGTE(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldConditionsClass, v))
}

// ConditionsClassLT applies the LT predicate on the "conditions_class" field.
func ConditionsClassLT(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldConditionsClass, v))
}

// ConditionsClassLTE applies the LTE predicate on the "conditions_class" field.
func ConditionsClassLTE(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldConditionsClass, v))
}

// WorkDateFromEQ applies the EQ predicate on the "work_date_from" field.
func WorkDateFromEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldWorkDateFrom, v))
}

// WorkDateFromNEQ applies the NEQ predicate on the "work_date_from" field.
func WorkDateFromNEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldWorkDateFrom, v))
}

// WorkDateFromIn applies the In predicate on the "work_date_from" field.
func WorkDateFromIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldWorkDateFrom, vs...))
}

// WorkDateFromNotIn applies the NotIn predicate on the "work_date_from" field.
func WorkDateFromNotIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldWorkDateFrom, vs...))
}

// WorkDateFromGT applies the GT predicate on the "work_date_from" field.
func WorkDateFromGT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldWorkDateFrom, v))
}

// WorkDateFromGTE applies the GTE predicate on the "work_date_from" field.
func WorkDateFromGTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldWorkDateFrom, v))
}

// WorkDateFromLT applies the LT predicate on the "work_date_from" field.
func WorkDateFromLT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldWorkDateFrom, v))
}

// WorkDateFromLTE applies the LTE predicate on the "work_date_from" field.
func WorkDateFromLTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldWorkDateFrom, v))
}

// WorkDateToEQ applies the EQ predicate on the "work_date_to" field.
func WorkDateToEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldWorkDateTo, v))
}

// WorkDateToNEQ applies the NEQ predicate on the "work_date_to" field.
func WorkDateToNEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldWorkDateTo, v))
}

// WorkDateToIn applies the In predicate on the "work_date_to" field.
func WorkDateToIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldWorkDateTo, vs...))
}

// WorkDateToNotIn applies the NotIn predicate on the "work_date_to" field.
func WorkDateToNotIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldWorkDateTo, vs...))
}

// WorkDateToGT applies the GT predicate on the "work_date_to" field.
func WorkDateToGT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldWorkDateTo, v))
}

// WorkDateToGTE applies the GTE predicate on the "work_date_to" field.
func WorkDateToGTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldWorkDateTo, v))
}

// WorkDateToLT applies the LT predicate on the "work_date_to" field.
func WorkDateToLT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldWorkDateTo, v))
}

// WorkDateToLTE applies the LTE predicate on the "work_date_to" field.
func WorkDateToLTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldWorkDateTo, v))
}

// WorkDateToIsNil applies the IsNil predicate on the "work_date_to" field.
func WorkDateToIsNil() predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIsNull(FieldWorkDateTo))
}

// WorkDateToNotNil applies the NotNil predicate on the "work_date_to" field.
func WorkDateToNotNil() predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotNull(FieldWorkDateTo))
}

// ProbationMonthsEQ applies the EQ predicate on the "probation_months" field.
func ProbationMonthsEQ(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldProbationMonths, v))
}

// ProbationMonthsNEQ applies the NEQ predicate on the "probation_months" field.
func ProbationMonthsNEQ(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldProbationMonths, v))
}

// ProbationMonthsIn applies the In predicate on the "probation_months" field.
func ProbationMonthsIn(vs ...int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldProbationMonths, vs...))
}

// ProbationMonthsNotIn applies the NotIn predicate on the "probation_months" field.
func ProbationMonthsNotIn(vs ...int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldProbationMonths, vs...))
}

// ProbationMonthsGT applies the GT predicate on the "probation_months" field.
func ProbationMonthsGT(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldProbationMonths, v))
}

// ProbationMonthsGTE applies the GTE predicate on the "probation_months" field.
func ProbationMonthsGTE(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldProbationMonths, v))
}

// ProbationMonthsLT applies the LT predicate on the "probation_months" field.
func ProbationMonthsLT(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldProbationMonths, v))
}

// ProbationMonthsLTE applies the LTE predicate on the "probation_months" field.
func ProbationMonthsLTE(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldProbationMonths, v))
}

// ProbationMonthsIsNil applies the IsNil predicate on the "probation_months" field.
func ProbationMonthsIsNil() predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIsNull(FieldProbationMonths))
}

// ProbationMonthsNotNil applies the NotNil predicate on the "probation_months" field.
func ProbationMonthsNotNil() predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotNull(FieldProbationMonths))
}

// SalaryEQ applies the EQ predicate on the "salary" field.
func SalaryEQ(v float64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldSalary, v))
}

// SalaryNEQ applies the NEQ predicate on the "salary" field.
func SalaryNEQ(v float64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldSalary, v))
}

// SalaryIn applies the In predicate on the "salary" field.
func SalaryIn(vs ...float64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldSalary, vs...))
}

// SalaryNotIn applies the NotIn predicate on the "salary" field.
func SalaryNotIn(vs ...float64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldSalary, vs...))
}

// SalaryGT applies the GT predicate on the "salary" field.
func SalaryGT(v float64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldSalary, v))
}

// SalaryGTE applies the GTE predicate on the "salary" field.
func SalaryGTE(v float64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldSalary, v))
}

// SalaryLT applies the LT predicate on the "salary" field.
func SalaryLT(v float64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldSalary, v))
}

// SalaryLTE applies the LTE predicate on the "salary" field.
func SalaryLTE(v float64) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldSalary, v))
}

// WorkHoursFromEQ applies the EQ predicate on the "work_hours_from" field.
func WorkHoursFromEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldWorkHoursFrom, v))
}

// WorkHoursFromNEQ applies the NEQ predicate on the "work_hours_from" field.
func WorkHoursFromNEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldWorkHoursFrom, v))
}

// WorkHoursFromIn applies the In predicate on the "work_hours_from" field.
func WorkHoursFromIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldWorkHoursFrom, vs...))
}

// WorkHoursFromNotIn applies the NotIn predicate on the "work_hours_from" field.
func WorkHoursFromNotIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldWorkHoursFrom, vs...))
}

// WorkHoursFromGT applies the GT predicate on the "work_hours_from" field.
func WorkHoursFromGT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldWorkHoursFrom, v))
}

// WorkHoursFromGTE applies the GTE predicate on the "work_hours_from" field.
func WorkHoursFromGTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldWorkHoursFrom, v))
}

// WorkHoursFromLT applies the LT predicate on the "work_hours_from" field.
func WorkHoursFromLT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldWorkHoursFrom, v))
}

// WorkHoursFromLTE applies the LTE predicate on the "work_hours_from" field.
func WorkHoursFromLTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldWorkHoursFrom, v))
}

// WorkHoursToEQ applies the EQ predicate on the "work_hours_to" field.
func WorkHoursToEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldWorkHoursTo, v))
}

// WorkHoursToNEQ applies the NEQ predicate on the "work_hours_to" field.
func WorkHoursToNEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldWorkHoursTo, v))
}

// WorkHoursToIn applies the In predicate on the "work_hours_to" field.
func WorkHoursToIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldWorkHoursTo, vs...))
}

// WorkHoursToNotIn applies the NotIn predicate on the "work_hours_to" field.
func WorkHoursToNotIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldWorkHoursTo, vs...))
}

// WorkHoursToGT applies the GT predicate on the "work_hours_to" field.
func WorkHoursToGT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldWorkHoursTo, v))
}

// WorkHoursToGTE applies the GTE predicate on the "work_hours_to" field.
func WorkHoursToGTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldWorkHoursTo, v))
}

// WorkHoursToLT applies the LT predicate on the "work_hours_to" field.
func WorkHoursToLT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldWorkHoursTo, v))
}

// WorkHoursToLTE applies the LTE predicate on the "work_hours_to" field.
func WorkHoursToLTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldWorkHoursTo, v))
}

// BreakFromEQ applies the EQ predicate on the "break_from" field.
func BreakFromEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldBreakFrom, v))
}

// BreakFromNEQ applies the NEQ predicate on the "break_from" field.
func BreakFromNEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldBreakFrom, v))
}

// BreakFromIn applies the In predicate on the "break_from" field.
func BreakFromIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldBreakFrom, vs...))
}

// BreakFromNotIn applies the NotIn predicate on the "break_from" field.
func BreakFromNotIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldBreakFrom, vs...))
}

// BreakFromGT applies the GT predicate on the "break_from" field.
func BreakFromGT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldBreakFrom, v))
}

// BreakFromGTE applies the GTE predicate on the "break_from" field.
func BreakFromGTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldBreakFrom, v))
}

// BreakFromLT applies the LT predicate on the "break_from" field.
func BreakFromLT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldBreakFrom, v))
}

// BreakFromLTE applies the LTE predicate on the "break_from" field.
func BreakFromLTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldBreakFrom, v))
}

// BreakFromIsNil applies the IsNil predicate on the "break_from" field.
func BreakFromIsNil() predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIsNull(FieldBreakFrom))
}

// BreakFromNotNil applies the NotNil predicate on the "break_from" field.
func BreakFromNotNil() predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotNull(FieldBreakFrom))
}

// BreakToEQ applies the EQ predicate on the "break_to" field.
func BreakToEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldBreakTo, v))
}

// BreakToNEQ applies the NEQ predicate on the "break_to" field.
func BreakToNEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldBreakTo, v))
}

// BreakToIn applies the In predicate on the "break_to" field.
func BreakToIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldBreakTo, vs...))
}

// BreakToNotIn applies the NotIn predicate on the "break_to" field.
func BreakToNotIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldBreakTo, vs...))
}

// BreakToGT applies the GT predicate on the "break_to" field.
func BreakToGT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldBreakTo, v))
}

// BreakToGTE applies the GTE predicate on the "break_to" field.
func BreakToGTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldBreakTo, v))
}

// BreakToLT applies the LT predicate on the "break_to" field.
func BreakToLT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldBreakTo, v))
}

// BreakToLTE applies the LTE predicate on the "break_to" field.
func BreakToLTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldBreakTo, v))
}

// BreakToIsNil applies the IsNil predicate on the "break_to" field.
func BreakToIsNil() predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIsNull(FieldBreakTo))
}

// BreakToNotNil applies the NotNil predicate on the "break_to" field.
func BreakToNotNil() predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotNull(FieldBreakTo))
}

// PaidLeaveDaysEQ applies the EQ predicate on the "paid_leave_days" field.
func PaidLeaveDaysEQ(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldPaidLeaveDays, v))
}

// PaidLeaveDaysNEQ applies the NEQ predicate on the "paid_leave_days" field.
func PaidLeaveDaysNEQ(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldPaidLeaveDays, v))
}

// PaidLeaveDaysIn applies the In predicate on the "paid_leave_days" field.
func PaidLeaveDaysIn(vs ...int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldPaidLeaveDays, vs...))
}

// PaidLeaveDaysNotIn applies the NotIn predicate on the "paid_leave_days" field.
func PaidLeaveDaysNotIn(vs ...int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldPaidLeaveDays, vs...))
}

// PaidLeaveDaysGT applies the GT predicate on the "paid_leave_days" field.
func PaidLeaveDaysGT(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldPaidLeaveDays, v))
}

// PaidLeaveDaysGTE applies the GTE predicate on the "paid_leave_days" field.
func PaidLeaveDaysGTE(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldPaidLeaveDays, v))
}

// PaidLeaveDaysLT applies the LT predicate on the "paid_leave_days" field.
func PaidLeaveDaysLT(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldPaidLeaveDays, v))
}

// PaidLeaveDaysLTE applies the LTE predicate on the "paid_leave_days" field.
func PaidLeaveDaysLTE(v int) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldPaidLeaveDays, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EmploymentContract) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EmploymentContract) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EmploymentContract) predicate.EmploymentContract {
	return predicate.EmploymentContract(sql.NotPredicates(p))
}
