// Code generated by ent, DO NOT EDIT.

package dismissalorderbody

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/example/micro/dismissal-order/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLTE(FieldID, id))
}

// DismissalOrderHeaderID applies equality check predicate on the "dismissal_order_header_id" field. It's identical to DismissalOrderHeaderIDEQ.
func DismissalOrderHeaderID(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldDismissalOrderHeaderID, v))
}

// EmploymentContractID applies equality check predicate on the "employment_contract_id" field. It's identical to EmploymentContractIDEQ.
func EmploymentContractID(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldEmploymentContractID, v))
}

// DepartmentID applies equality check predicate on the "department_id" field. It's identical to DepartmentIDEQ.
func DepartmentID(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldDepartmentID, v))
}

// PositionID applies equality check predicate on the "position_id" field. It's identical to PositionIDEQ.
func PositionID(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldPositionID, v))
}

// DismissalDate applies equality check predicate on the "dismissal_date" field. It's identical to DismissalDateEQ.
func DismissalDate(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldDismissalDate, v))
}

// DismissalGround applies equality check predicate on the "dismissal_ground" field. It's identical to DismissalGroundEQ.
func DismissalGround(v string) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldDismissalGround, v))
}

// DocNumber applies equality check predicate on the "doc_number" field. It's identical to DocNumberEQ.
func DocNumber(v int) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldDocNumber, v))
}

// DocDate applies equality check predicate on the "doc_date" field. It's identical to DocDateEQ.
func DocDate(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldDocDate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldUpdatedAt, v))
}

// DismissalOrderHeaderIDEQ applies the EQ predicate on the "dismissal_order_header_id" field.
func DismissalOrderHeaderIDEQ(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldDismissalOrderHeaderID, v))
}

// DismissalOrderHeaderIDNEQ applies the NEQ predicate on the "dismissal_order_header_id" field.
func DismissalOrderHeaderIDNEQ(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNEQ(FieldDismissalOrderHeaderID, v))
}

// DismissalOrderHeaderIDIn applies the In predicate on the "dismissal_order_header_id" field.
func DismissalOrderHeaderIDIn(vs ...int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldIn(FieldDismissalOrderHeaderID, vs...))
}

// DismissalOrderHeaderIDNotIn applies the NotIn predicate on the "dismissal_order_header_id" field.
func DismissalOrderHeaderIDNotIn(vs ...int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNotIn(FieldDismissalOrderHeaderID, vs...))
}

// EmploymentContractIDEQ applies the EQ predicate on the "employment_contract_id" field.
func EmploymentContractIDEQ(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldEmploymentContractID, v))
}

// EmploymentContractIDNEQ applies the NEQ predicate on the "employment_contract_id" field.
func EmploymentContractIDNEQ(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNEQ(FieldEmploymentContractID, v))
}

// EmploymentContractIDIn applies the In predicate on the "employment_contract_id" field.
func EmploymentContractIDIn(vs ...int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldIn(FieldEmploymentContractID, vs...))
}

// EmploymentContractIDNotIn applies the NotIn predicate on the "employment_contract_id" field.
func EmploymentContractIDNotIn(vs ...int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNotIn(FieldEmploymentContractID, vs...))
}

// EmploymentContractIDGT applies the GT predicate on the "employment_contract_id" field.
func EmploymentContractIDGT(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGT(FieldEmploymentContractID, v))
}

// EmploymentContractIDGTE applies the GTE predicate on the "employment_contract_id" field.
func EmploymentContractIDGTE(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGTE(FieldEmploymentContractID, v))
}

// EmploymentContractIDLT applies the LT predicate on the "employment_contract_id" field.
func EmploymentContractIDLT(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLT(FieldEmploymentContractID, v))
}

// EmploymentContractIDLTE applies the LTE predicate on the "employment_contract_id" field.
func EmploymentContractIDLTE(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLTE(FieldEmploymentContractID, v))
}

// DepartmentIDEQ applies the EQ predicate on the "department_id" field.
func DepartmentIDEQ(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldDepartmentID, v))
}

// DepartmentIDNEQ applies the NEQ predicate on the "department_id" field.
func DepartmentIDNEQ(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNEQ(FieldDepartmentID, v))
}

// DepartmentIDIn applies the In predicate on the "department_id" field.
func DepartmentIDIn(vs ...int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldIn(FieldDepartmentID, vs...))
}

// DepartmentIDNotIn applies the NotIn predicate on the "department_id" field.
func DepartmentIDNotIn(vs ...int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNotIn(FieldDepartmentID, vs...))
}

// DepartmentIDGT applies the GT predicate on the "department_id" field.
func DepartmentIDGT(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGT(FieldDepartmentID, v))
}

// DepartmentIDGTE applies the GTE predicate on the "department_id" field.
func DepartmentIDGTE(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGTE(FieldDepartmentID, v))
}

// DepartmentIDLT applies the LT predicate on the "department_id" field.
func DepartmentIDLT(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLT(FieldDepartmentID, v))
}

// DepartmentIDLTE applies the LTE predicate on the "department_id" field.
func DepartmentIDLTE(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLTE(FieldDepartmentID, v))
}

// PositionIDEQ applies the EQ predicate on the "position_id" field.
func PositionIDEQ(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldPositionID, v))
}

// PositionIDNEQ applies the NEQ predicate on the "position_id" field.
func PositionIDNEQ(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNEQ(FieldPositionID, v))
}

// PositionIDIn applies the In predicate on the "position_id" field.
func PositionIDIn(vs ...int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldIn(FieldPositionID, vs...))
}

// PositionIDNotIn applies the NotIn predicate on the "position_id" field.
func PositionIDNotIn(vs ...int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNotIn(FieldPositionID, vs...))
}

// PositionIDGT applies the GT predicate on the "position_id" field.
func PositionIDGT(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGT(FieldPositionID, v))
}

// PositionIDGTE applies the GTE predicate on the "position_id" field.
func PositionIDGTE(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGTE(FieldPositionID, v))
}

// PositionIDLT applies the LT predicate on the "position_id" field.
func PositionIDLT(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLT(FieldPositionID, v))
}

// PositionIDLTE applies the LTE predicate on the "position_id" field.
func PositionIDLTE(v int64) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLTE(FieldPositionID, v))
}

// DismissalDateEQ applies the EQ predicate on the "dismissal_date" field.
func DismissalDateEQ(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldDismissalDate, v))
}

// DismissalDateNEQ applies the NEQ predicate on the "dismissal_date" field.
func DismissalDateNEQ(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNEQ(FieldDismissalDate, v))
}

// DismissalDateIn applies the In predicate on the "dismissal_date" field.
func DismissalDateIn(vs ...time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldIn(FieldDismissalDate, vs...))
}

// DismissalDateNotIn applies the NotIn predicate on the "dismissal_date" field.
func DismissalDateNotIn(vs ...time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNotIn(FieldDismissalDate, vs...))
}

// DismissalDateGT applies the GT predicate on the "dismissal_date" field.
func DismissalDateGT(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGT(FieldDismissalDate, v))
}

// DismissalDateGTE applies the GTE predicate on the "dismissal_date" field.
func DismissalDateGTE(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGTE(FieldDismissalDate, v))
}

// DismissalDateLT applies the LT predicate on the "dismissal_date" field.
func DismissalDateLT(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLT(FieldDismissalDate, v))
}

// DismissalDateLTE applies the LTE predicate on the "dismissal_date" field.
func DismissalDateLTE(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLTE(FieldDismissalDate, v))
}

// DismissalGroundEQ applies the EQ predicate on the "dismissal_ground" field.
func DismissalGroundEQ(v string) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldDismissalGround, v))
}

// DismissalGroundNEQ applies the NEQ predicate on the "dismissal_ground" field.
func DismissalGroundNEQ(v string) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNEQ(FieldDismissalGround, v))
}

// DismissalGroundIn applies the In predicate on the "dismissal_ground" field.
func DismissalGroundIn(vs ...string) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldIn(FieldDismissalGround, vs...))
}

// DismissalGroundNotIn applies the NotIn predicate on the "dismissal_ground" field.
func DismissalGroundNotIn(vs ...string) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNotIn(FieldDismissalGround, vs...))
}

// DismissalGroundGT applies the GT predicate on the "dismissal_ground" field.
func DismissalGroundGT(v string) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGT(FieldDismissalGround, v))
}

// DismissalGroundGTE applies the GTE predicate on the "dismissal_ground" field.
func DismissalGroundGTE(v string) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGTE(FieldDismissalGround, v))
}

// DismissalGroundLT applies the LT predicate on the "dismissal_ground" field.
func DismissalGroundLT(v string) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLT(FieldDismissalGround, v))
}

// DismissalGroundLTE applies the LTE predicate on the "dismissal_ground" field.
func DismissalGroundLTE(v string) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLTE(FieldDismissalGround, v))
}

// DismissalGroundContains applies the Contains predicate on the "dismissal_ground" field.
func DismissalGroundContains(v string) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldContains(FieldDismissalGround, v))
}

// DismissalGroundHasPrefix applies the HasPrefix predicate on the "dismissal_ground" field.
func DismissalGroundHasPrefix(v string) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldHasPrefix(FieldDismissalGround, v))
}

// DismissalGroundHasSuffix applies the HasSuffix predicate on the "dismissal_ground" field.
func DismissalGroundHasSuffix(v string) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldHasSuffix(FieldDismissalGround, v))
}

// DismissalGroundEqualFold applies the EqualFold predicate on the "dismissal_ground" field.
func DismissalGroundEqualFold(v string) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEqualFold(FieldDismissalGround, v))
}

// DismissalGroundContainsFold applies the ContainsFold predicate on the "dismissal_ground" field.
func DismissalGroundContainsFold(v string) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldContainsFold(FieldDismissalGround, v))
}

// DocNumberEQ applies the EQ predicate on the "doc_number" field.
func DocNumberEQ(v int) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldDocNumber, v))
}

// DocNumberNEQ applies the NEQ predicate on the "doc_number" field.
func DocNumberNEQ(v int) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNEQ(FieldDocNumber, v))
}

// DocNumberIn applies the In predicate on the "doc_number" field.
func DocNumberIn(vs ...int) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldIn(FieldDocNumber, vs...))
}

// DocNumberNotIn applies the NotIn predicate on the "doc_number" field.
func DocNumberNotIn(vs ...int) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNotIn(FieldDocNumber, vs...))
}

// DocNumberGT applies the GT predicate on the "doc_number" field.
func DocNumberGT(v int) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGT(FieldDocNumber, v))
}

// DocNumberGTE applies the GTE predicate on the "doc_number" field.
func DocNumberGTE(v int) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGTE(FieldDocNumber, v))
}

// DocNumberLT applies the LT predicate on the "doc_number" field.
func DocNumberLT(v int) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLT(FieldDocNumber, v))
}

// DocNumberLTE applies the LTE predicate on the "doc_number" field.
func DocNumberLTE(v int) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLTE(FieldDocNumber, v))
}

// DocNumberIsNil applies the IsNil predicate on the "doc_number" field.
func DocNumberIsNil() predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldIsNull(FieldDocNumber))
}

// DocNumberNotNil applies the NotNil predicate on the "doc_number" field.
func DocNumberNotNil() predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNotNull(FieldDocNumber))
}

// DocDateEQ applies the EQ predicate on the "doc_date" field.
func DocDateEQ(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldDocDate, v))
}

// DocDateNEQ applies the NEQ predicate on the "doc_date" field.
func DocDateNEQ(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNEQ(FieldDocDate, v))
}

// DocDateIn applies the In predicate on the "doc_date" field.
func DocDateIn(vs ...time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldIn(FieldDocDate, vs...))
}

// DocDateNotIn applies the NotIn predicate on the "doc_date" field.
func DocDateNotIn(vs ...time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNotIn(FieldDocDate, vs...))
}

// DocDateGT applies the GT predicate on the "doc_date" field.
func DocDateGT(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGT(FieldDocDate, v))
}

// DocDateGTE applies the GTE predicate on the "doc_date" field.
func DocDateGTE(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGTE(FieldDocDate, v))
}

// DocDateLT applies the LT predicate on the "doc_date" field.
func DocDateLT(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLT(FieldDocDate, v))
}

// DocDateLTE applies the LTE predicate on the "doc_date" field.
func DocDateLTE(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLTE(FieldDocDate, v))
}

// DocDateIsNil applies the IsNil predicate on the "doc_date" field.
func DocDateIsNil() predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldIsNull(FieldDocDate))
}

// DocDateNotNil applies the NotNil predicate on the "doc_date" field.
func DocDateNotNil() predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNotNull(FieldDocDate))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasHeader applies the HasEdge predicate on the "header" edge.
func HasHeader() predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, HeaderTable, HeaderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHeaderWith applies the HasEdge predicate on the "header" edge with a given conditions (other predicates).
func HasHeaderWith(preds ...predicate.DismissalOrderHeader) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(func(s *sql.Selector) {
		step := newHeaderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DismissalOrderBody) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DismissalOrderBody) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DismissalOrderBody) predicate.DismissalOrderBody {
	return predicate.DismissalOrderBody(sql.NotPredicates(p))
}
