// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/example/micro/individuals/ent/individual"
	"github.com/example/micro/individuals/ent/predicate"
)

// IndividualUpdate is the builder for updating Individual entities.
type IndividualUpdate struct {
	config
	hooks    []Hook
	mutation *IndividualMutation
}

// Where appends a list predicates to the IndividualUpdate builder.
func (iu *IndividualUpdate) Where(ps ...predicate.Individual) *IndividualUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetFirstName sets the "first_name" field.
func (iu *IndividualUpdate) SetFirstName(s string) *IndividualUpdate {
	iu.mutation.SetFirstName(s)
	return iu
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (iu *IndividualUpdate) SetNillableFirstName(s *string) *IndividualUpdate {
	if s != nil {
		iu.SetFirstName(*s)
	}
	return iu
}

// SetLastName sets the "last_name" field.
func (iu *IndividualUpdate) SetLastName(s string) *IndividualUpdate {
	iu.mutation.SetLastName(s)
	return iu
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (iu *IndividualUpdate) SetNillableLastName(s *string) *IndividualUpdate {
	if s != nil {
		iu.SetLastName(*s)
	}
	return iu
}

// SetPatronymic sets the "patronymic" field.
func (iu *IndividualUpdate) SetPatronymic(s string) *IndividualUpdate {
	iu.mutation.SetPatronymic(s)
	return iu
}

// SetNillablePatronymic sets the "patronymic" field if the given value is not nil.
func (iu *IndividualUpdate) SetNillablePatronymic(s *string) *IndividualUpdate {
	if s != nil {
		iu.SetPatronymic(*s)
	}
	return iu
}

// ClearPatronymic clears the value of the "patronymic" field.
func (iu *IndividualUpdate) ClearPatronymic() *IndividualUpdate {
	iu.mutation.ClearPatronymic()
	return iu
}

// SetRegistrationAddress sets the "registration_address" field.
func (iu *IndividualUpdate) SetRegistrationAddress(s string) *IndividualUpdate {
	iu.mutation.SetRegistrationAddress(s)
	return iu
}

// SetNillableRegistrationAddress sets the "registration_address" field if the given value is not nil.
func (iu *IndividualUpdate) SetNillableRegistrationAddress(s *string) *IndividualUpdate {
	if s != nil {
		iu.SetRegistrationAddress(*s)
	}
	return iu
}

// SetPassportSeries sets the "passport_series" field.
func (iu *IndividualUpdate) SetPassportSeries(s string) *IndividualUpdate {
	iu.mutation.SetPassportSeries(s)
	return iu
}

// SetNillablePassportSeries sets the "passport_series" field if the given value is not nil.
func (iu *IndividualUpdate) SetNillablePassportSeries(s *string) *IndividualUpdate {
	if s != nil {
		iu.SetPassportSeries(*s)
	}
	return iu
}

// SetPassportNumber sets the "passport_number" field.
func (iu *IndividualUpdate) SetPassportNumber(s string) *IndividualUpdate {
	iu.mutation.SetPassportNumber(s)
	return iu
}

// SetNillablePassportNumber sets the "passport_number" field if the given value is not nil.
func (iu *IndividualUpdate) SetNillablePassportNumber(s *string) *IndividualUpdate {
	if s != nil {
		iu.SetPassportNumber(*s)
	}
	return iu
}

// SetPassportIssuedBy sets the "passport_issued_by" field.
func (iu *IndividualUpdate) SetPassportIssuedBy(s string) *IndividualUpdate {
	iu.mutation.SetPassportIssuedBy(s)
	return iu
}

// SetNillablePassportIssuedBy sets the "passport_issued_by" field if the given value is not nil.
func (iu *IndividualUpdate) SetNillablePassportIssuedBy(s *string) *IndividualUpdate {
	if s != nil {
		iu.SetPassportIssuedBy(*s)
	}
	return iu
}

// SetPassportIssuedDate sets the "passport_issued_date" field.
func (iu *IndividualUpdate) SetPassportIssuedDate(s string) *IndividualUpdate {
	iu.mutation.SetPassportIssuedDate(s)
	return iu
}

// SetNillablePassportIssuedDate sets the "passport_issued_date" field if the given value is not nil.
func (iu *IndividualUpdate) SetNillablePassportIssuedDate(s *string) *IndividualUpdate {
	if s != nil {
		iu.SetPassportIssuedDate(*s)
	}
	return iu
}

// SetPassportIssuedDepartmentCode sets the "passport_issued_department_code" field.
func (iu *IndividualUpdate) SetPassportIssuedDepartmentCode(s string) *IndividualUpdate {
	iu.mutation.SetPassportIssuedDepartmentCode(s)
	return iu
}

// SetNillablePassportIssuedDepartmentCode sets the "passport_issued_department_code" field if the given value is not nil.
func (iu *IndividualUpdate) SetNillablePassportIssuedDepartmentCode(s *string) *IndividualUpdate {
	if s != nil {
		iu.SetPassportIssuedDepartmentCode(*s)
	}
	return iu
}

// SetIsAuthorizedRepresentative sets the "is_authorized_representative" field.
func (iu *IndividualUpdate) SetIsAuthorizedRepresentative(b bool) *IndividualUpdate {
	iu.mutation.SetIsAuthorizedRepresentative(b)
	return iu
}

// SetNillableIsAuthorizedRepresentative sets the "is_authorized_representative" field if the given value is not nil.
func (iu *IndividualUpdate) SetNillableIsAuthorizedRepresentative(b *bool) *IndividualUpdate {
	if b != nil {
		iu.SetIsAuthorizedRepresentative(*b)
	}
	return iu
}

// SetCreatedAt sets the "created_at" field.
func (iu *IndividualUpdate) SetCreatedAt(t time.Time) *IndividualUpdate {
	iu.mutation.SetCreatedAt(t)
	return iu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (iu *IndividualUpdate) SetNillableCreatedAt(t *time.Time) *IndividualUpdate {
	if t != nil {
		iu.SetCreatedAt(*t)
	}
	return iu
}

// SetUpdatedAt sets the "updated_at" field.
func (iu *IndividualUpdate) SetUpdatedAt(t time.Time) *IndividualUpdate {
	iu.mutation.SetUpdatedAt(t)
	return iu
}

// Mutation returns the IndividualMutation object of the builder.
func (iu *IndividualUpdate) Mutation() *IndividualMutation {
	return iu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *IndividualUpdate) Save(ctx context.Context) (int, error) {
	iu.defaults()
	return withHooks(ctx, iu.sqlSave, iu.mutation, iu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *IndividualUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *IndividualUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *IndividualUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iu *IndividualUpdate) defaults() {
	if _, ok := iu.mutation.UpdatedAt(); !ok {
		v := individual.UpdateDefaultUpdatedAt()
		iu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iu *IndividualUpdate) check() error {
	if v, ok := iu.mutation.FirstName(); ok {
		if err := individual.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`ent: validator failed for field "Individual.first_name": %w`, err)}
		}
	}
	if v, ok := iu.mutation.LastName(); ok {
		if err := individual.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`ent: validator failed for field "Individual.last_name": %w`, err)}
		}
	}
	if v, ok := iu.mutation.Patronymic(); ok {
		if err := individual.PatronymicValidator(v); err != nil {
			return &ValidationError{Name: "patronymic", err: fmt.Errorf(`ent: validator failed for field "Individual.patronymic": %w`, err)}
		}
	}
	if v, ok := iu.mutation.RegistrationAddress(); ok {
		if err := individual.RegistrationAddressValidator(v); err != nil {
			return &ValidationError{Name: "registration_address", err: fmt.Errorf(`ent: validator failed for field "Individual.registration_address": %w`, err)}
		}
	}
	if v, ok := iu.mutation.PassportSeries(); ok {
		if err := individual.PassportSeriesValidator(v); err != nil {
			return &ValidationError{Name: "passport_series", err: fmt.Errorf(`ent: validator failed for field "Individual.passport_series": %w`, err)}
		}
	}
	if v, ok := iu.mutation.PassportNumber(); ok {
		if err := individual.PassportNumberValidator(v); err != nil {
			return &ValidationError{Name: "passport_number", err: fmt.Errorf(`ent: validator failed for field "Individual.passport_number": %w`, err)}
		}
	}
	if v, ok := iu.mutation.PassportIssuedBy(); ok {
		if err := individual.PassportIssuedByValidator(v); err != nil {
			return &ValidationError{Name: "passport_issued_by", err: fmt.Errorf(`ent: validator failed for field "Individual.passport_issued_by": %w`, err)}
		}
	}
	if v, ok := iu.mutation.PassportIssuedDate(); ok {
		if err := individual.PassportIssuedDateValidator(v); err != nil {
			return &ValidationError{Name: "passport_issued_date", err: fmt.Errorf(`ent: validator failed for field "Individual.passport_issued_date": %w`, err)}
		}
	}
	if v, ok := iu.mutation.PassportIssuedDepartmentCode(); ok {
		if err := individual.PassportIssuedDepartmentCodeValidator(v); err != nil {
			return &ValidationError{Name: "passport_issued_department_code", err: fmt.Errorf(`ent: validator failed for field "Individual.passport_issued_department_code": %w`, err)}
		}
	}
	return nil
}

func (iu *IndividualUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := iu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(individual.Table, individual.Columns, sqlgraph.NewFieldSpec(individual.FieldID, field.TypeInt64))
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.FirstName(); ok {
		_spec.SetField(individual.FieldFirstName, field.TypeString, value)
	}
	if value, ok := iu.mutation.LastName(); ok {
		_spec.SetField(individual.FieldLastName, field.TypeString, value)
	}
	if value, ok := iu.mutation.Patronymic(); ok {
		_spec.SetField(individual.FieldPatronymic, field.TypeString, value)
	}
	if iu.mutation.PatronymicCleared() {
		_spec.ClearField(individual.FieldPatronymic, field.TypeString)
	}
	if value, ok := iu.mutation.RegistrationAddress(); ok {
		_spec.SetField(individual.FieldRegistrationAddress, field.TypeString, value)
	}
	if value, ok := iu.mutation.PassportSeries(); ok {
		_spec.SetField(individual.FieldPassportSeries, field.TypeString, value)
	}
	if value, ok := iu.mutation.PassportNumber(); ok {
		_spec.SetField(individual.FieldPassportNumber, field.TypeString, value)
	}
	if value, ok := iu.mutation.PassportIssuedBy(); ok {
		_spec.SetField(individual.FieldPassportIssuedBy, field.TypeString, value)
	}
	if value, ok := iu.mutation.PassportIssuedDate(); ok {
		_spec.SetField(individual.FieldPassportIssuedDate, field.TypeString, value)
	}
	if value, ok := iu.mutation.PassportIssuedDepartmentCode(); ok {
		_spec.SetField(individual.FieldPassportIssuedDepartmentCode, field.TypeString, value)
	}
	if value, ok := iu.mutation.IsAuthorizedRepresentative(); ok {
		_spec.SetField(individual.FieldIsAuthorizedRepresentative, field.TypeBool, value)
	}
	if value, ok := iu.mutation.CreatedAt(); ok {
		_spec.SetField(individual.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := iu.mutation.UpdatedAt(); ok {
		_spec.SetField(individual.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{individual.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iu.mutation.done = true
	return n, nil
}

// IndividualUpdateOne is the builder for updating a single Individual entity.
type IndividualUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IndividualMutation
}

// SetFirstName sets the "first_name" field.
func (iuo *IndividualUpdateOne) SetFirstName(s string) *IndividualUpdateOne {
	iuo.mutation.SetFirstName(s)
	return iuo
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (iuo *IndividualUpdateOne) SetNillableFirstName(s *string) *IndividualUpdateOne {
	if s != nil {
		iuo.SetFirstName(*s)
	}
	return iuo
}

// SetLastName sets the "last_name" field.
func (iuo *IndividualUpdateOne) SetLastName(s string) *IndividualUpdateOne {
	iuo.mutation.SetLastName(s)
	return iuo
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (iuo *IndividualUpdateOne) SetNillableLastName(s *string) *IndividualUpdateOne {
	if s != nil {
		iuo.SetLastName(*s)
	}
	return iuo
}

// SetPatronymic sets the "patronymic" field.
func (iuo *IndividualUpdateOne) SetPatronymic(s string) *IndividualUpdateOne {
	iuo.mutation.SetPatronymic(s)
	return iuo
}

// SetNillablePatronymic sets the "patronymic" field if the given value is not nil.
func (iuo *IndividualUpdateOne) SetNillablePatronymic(s *string) *IndividualUpdateOne {
	if s != nil {
		iuo.SetPatronymic(*s)
	}
	return iuo
}

// ClearPatronymic clears the value of the "patronymic" field.
func (iuo *IndividualUpdateOne) ClearPatronymic() *IndividualUpdateOne {
	iuo.mutation.ClearPatronymic()
	return iuo
}

// SetRegistrationAddress sets the "registration_address" field.
func (iuo *IndividualUpdateOne) SetRegistrationAddress(s string) *IndividualUpdateOne {
	iuo.mutation.SetRegistrationAddress(s)
	return iuo
}

// SetNillableRegistrationAddress sets the "registration_address" field if the given value is not nil.
func (iuo *IndividualUpdateOne) SetNillableRegistrationAddress(s *string) *IndividualUpdateOne {
	if s != nil {
		iuo.SetRegistrationAddress(*s)
	}
	return iuo
}

// SetPassportSeries sets the "passport_series" field.
func (iuo *IndividualUpdateOne) SetPassportSeries(s string) *IndividualUpdateOne {
	iuo.mutation.SetPassportSeries(s)
	return iuo
}

// SetNillablePassportSeries sets the "passport_series" field if the given value is not nil.
func (iuo *IndividualUpdateOne) SetNillablePassportSeries(s *string) *IndividualUpdateOne {
	if s != nil {
		iuo.SetPassportSeries(*s)
	}
	return iuo
}

// SetPassportNumber sets the "passport_number" field.
func (iuo *IndividualUpdateOne) SetPassportNumber(s string) *IndividualUpdateOne {
	iuo.mutation.SetPassportNumber(s)
	return iuo
}

// SetNillablePassportNumber sets the "passport_number" field if the given value is not nil.
func (iuo *IndividualUpdateOne) SetNillablePassportNumber(s *string) *IndividualUpdateOne {
	if s != nil {
		iuo.SetPassportNumber(*s)
	}
	return iuo
}

// SetPassportIssuedBy sets the "passport_issued_by" field.
func (iuo *IndividualUpdateOne) SetPassportIssuedBy(s string) *IndividualUpdateOne {
	iuo.mutation.SetPassportIssuedBy(s)
	return iuo
}

// SetNillablePassportIssuedBy sets the "passport_issued_by" field if the given value is not nil.
func (iuo *IndividualUpdateOne) SetNillablePassportIssuedBy(s *string) *IndividualUpdateOne {
	if s != nil {
		iuo.SetPassportIssuedBy(*s)
	}
	return iuo
}

// SetPassportIssuedDate sets the "passport_issued_date" field.
func (iuo *IndividualUpdateOne) SetPassportIssuedDate(s string) *IndividualUpdateOne {
	iuo.mutation.SetPassportIssuedDate(s)
	return iuo
}

// SetNillablePassportIssuedDate sets the "passport_issued_date" field if the given value is not nil.
func (iuo *IndividualUpdateOne) SetNillablePassportIssuedDate(s *string) *IndividualUpdateOne {
	if s != nil {
		iuo.SetPassportIssuedDate(*s)
	}
	return iuo
}

// SetPassportIssuedDepartmentCode sets the "passport_issued_department_code" field.
func (iuo *IndividualUpdateOne) SetPassportIssuedDepartmentCode(s string) *IndividualUpdateOne {
	iuo.mutation.SetPassportIssuedDepartmentCode(s)
	return iuo
}

// SetNillablePassportIssuedDepartmentCode sets the "passport_issued_department_code" field if the given value is not nil.
func (iuo *IndividualUpdateOne) SetNillablePassportIssuedDepartmentCode(s *string) *IndividualUpdateOne {
	if s != nil {
		iuo.SetPassportIssuedDepartmentCode(*s)
	}
	return iuo
}

// SetIsAuthorizedRepresentative sets the "is_authorized_representative" field.
func (iuo *IndividualUpdateOne) SetIsAuthorizedRepresentative(b bool) *IndividualUpdateOne {
	iuo.mutation.SetIsAuthorizedRepresentative(b)
	return iuo
}

// SetNillableIsAuthorizedRepresentative sets the "is_authorized_representative" field if the given value is not nil.
func (iuo *IndividualUpdateOne) SetNillableIsAuthorizedRepresentative(b *bool) *IndividualUpdateOne {
	if b != nil {
		iuo.SetIsAuthorizedRepresentative(*b)
	}
	return iuo
}

// SetCreatedAt sets the "created_at" field.
func (iuo *IndividualUpdateOne) SetCreatedAt(t time.Time) *IndividualUpdateOne {
	iuo.mutation.SetCreatedAt(t)
	return iuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (iuo *IndividualUpdateOne) SetNillableCreatedAt(t *time.Time) *IndividualUpdateOne {
	if t != nil {
		iuo.SetCreatedAt(*t)
	}
	return iuo
}

// SetUpdatedAt sets the "updated_at" field.
func (iuo *IndividualUpdateOne) SetUpdatedAt(t time.Time) *IndividualUpdateOne {
	iuo.mutation.SetUpdatedAt(t)
	return iuo
}

// Mutation returns the IndividualMutation object of the builder.
func (iuo *IndividualUpdateOne) Mutation() *IndividualMutation {
	return iuo.mutation
}

// Where appends a list predicates to the IndividualUpdate builder.
func (iuo *IndividualUpdateOne) Where(ps ...predicate.Individual) *IndividualUpdateOne {
	iuo.mutation.Where(ps...)
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *IndividualUpdateOne) Select(field string, fields ...string) *IndividualUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Individual entity.
func (iuo *IndividualUpdateOne) Save(ctx context.Context) (*Individual, error) {
	iuo.defaults()
	return withHooks(ctx, iuo.sqlSave, iuo.mutation, iuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *IndividualUpdateOne) SaveX(ctx context.Context) *Individual {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *IndividualUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *IndividualUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iuo *IndividualUpdateOne) defaults() {
	if _, ok := iuo.mutation.UpdatedAt(); !ok {
		v := individual.UpdateDefaultUpdatedAt()
		iuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iuo *IndividualUpdateOne) check() error {
	if v, ok := iuo.mutation.FirstName(); ok {
		if err := individual.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`ent: validator failed for field "Individual.first_name": %w`, err)}
		}
	}
	if v, ok := iuo.mutation.LastName(); ok {
		if err := individual.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`ent: validator failed for field "Individual.last_name": %w`, err)}
		}
	}
	if v, ok := iuo.mutation.Patronymic(); ok {
		if err := individual.PatronymicValidator(v); err != nil {
			return &ValidationError{Name: "patronymic", err: fmt.Errorf(`ent: validator failed for field "Individual.patronymic": %w`, err)}
		}
	}
	if v, ok := iuo.mutation.RegistrationAddress(); ok {
		if err := individual.RegistrationAddressValidator(v); err != nil {
			return &ValidationError{Name: "registration_address", err: fmt.Errorf(`ent: validator failed for field "Individual.registration_address": %w`, err)}
		}
	}
	if v, ok := iuo.mutation.PassportSeries(); ok {
		if err := individual.PassportSeriesValidator(v); err != nil {
			return &ValidationError{Name: "passport_series", err: fmt.Errorf(`ent: validator failed for field "Individual.passport_series": %w`, err)}
		}
	}
	if v, ok := iuo.mutation.PassportNumber(); ok {
		if err := individual.PassportNumberValidator(v); err != nil {
			return &ValidationError{Name: "passport_number", err: fmt.Errorf(`ent: validator failed for field "Individual.passport_number": %w`, err)}
		}
	}
	if v, ok := iuo.mutation.PassportIssuedBy(); ok {
		if err := individual.PassportIssuedByValidator(v); err != nil {
			return &ValidationError{Name: "passport_issued_by", err: fmt.Errorf(`ent: validator failed for field "Individual.passport_issued_by": %w`, err)}
		}
	}
	if v, ok := iuo.mutation.PassportIssuedDate(); ok {
		if err := individual.PassportIssuedDateValidator(v); err != nil {
			return &ValidationError{Name: "passport_issued_date", err: fmt.Errorf(`ent: validator failed for field "Individual.passport_issued_date": %w`, err)}
		}
	}
	if v, ok := iuo.mutation.PassportIssuedDepartmentCode(); ok {
		if err := individual.PassportIssuedDepartmentCodeValidator(v); err != nil {
			return &ValidationError{Name: "passport_issued_department_code", err: fmt.Errorf(`ent: validator failed for field "Individual.passport_issued_department_code": %w`, err)}
		}
	}
	return nil
}

func (iuo *IndividualUpdateOne) sqlSave(ctx context.Context) (_node *Individual, err error) {
	if err := iuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(individual.Table, individual.Columns, sqlgraph.NewFieldSpec(individual.FieldID, field.TypeInt64))
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Individual.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, individual.FieldID)
		for _, f := range fields {
			if !individual.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != individual.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.FirstName(); ok {
		_spec.SetField(individual.FieldFirstName, field.TypeString, value)
	}
	if value, ok := iuo.mutation.LastName(); ok {
		_spec.SetField(individual.FieldLastName, field.TypeString, value)
	}
	if value, ok := iuo.mutation.Patronymic(); ok {
		_spec.SetField(individual.FieldPatronymic, field.TypeString, value)
	}
	if iuo.mutation.PatronymicCleared() {
		_spec.ClearField(individual.FieldPatronymic, field.TypeString)
	}
	if value, ok := iuo.mutation.RegistrationAddress(); ok {
		_spec.SetField(individual.FieldRegistrationAddress, field.TypeString, value)
	}
	if value, ok := iuo.mutation.PassportSeries(); ok {
		_spec.SetField(individual.FieldPassportSeries, field.TypeString, value)
	}
	if value, ok := iuo.mutation.PassportNumber(); ok {
		_spec.SetField(individual.FieldPassportNumber, field.TypeString, value)
	}
	if value, ok := iuo.mutation.PassportIssuedBy(); ok {
		_spec.SetField(individual.FieldPassportIssuedBy, field.TypeString, value)
	}
	if value, ok := iuo.mutation.PassportIssuedDate(); ok {
		_spec.SetField(individual.FieldPassportIssuedDate, field.TypeString, value)
	}
	if value, ok := iuo.mutation.PassportIssuedDepartmentCode(); ok {
		_spec.SetField(individual.FieldPassportIssuedDepartmentCode, field.TypeString, value)
	}
	if value, ok := iuo.mutation.IsAuthorizedRepresentative(); ok {
		_spec.SetField(individual.FieldIsAuthorizedRepresentative, field.TypeBool, value)
	}
	if value, ok := iuo.mutation.CreatedAt(); ok {
		_spec.SetField(individual.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := iuo.mutation.UpdatedAt(); ok {
		_spec.SetField(individual.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Individual{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{individual.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iuo.mutation.done = true
	return _node, nil
}
