// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/example/micro/individuals/ent/individual"
)

// IndividualCreate is the builder for creating a Individual entity.
type IndividualCreate struct {
	config
	mutation *IndividualMutation
	hooks    []Hook
}

// SetFirstName sets the "first_name" field.
func (ic *IndividualCreate) SetFirstName(s string) *IndividualCreate {
	ic.mutation.SetFirstName(s)
	return ic
}

// SetLastName sets the "last_name" field.
func (ic *IndividualCreate) SetLastName(s string) *IndividualCreate {
	ic.mutation.SetLastName(s)
	return ic
}

// SetPatronymic sets the "patronymic" field.
func (ic *IndividualCreate) SetPatronymic(s string) *IndividualCreate {
	ic.mutation.SetPatronymic(s)
	return ic
}

// SetNillablePatronymic sets the "patronymic" field if the given value is not nil.
func (ic *IndividualCreate) SetNillablePatronymic(s *string) *IndividualCreate {
	if s != nil {
		ic.SetPatronymic(*s)
	}
	return ic
}

// SetRegistrationAddress sets the "registration_address" field.
func (ic *IndividualCreate) SetRegistrationAddress(s string) *IndividualCreate {
	ic.mutation.SetRegistrationAddress(s)
	return ic
}

// SetPassportSeries sets the "passport_series" field.
func (ic *IndividualCreate) SetPassportSeries(s string) *IndividualCreate {
	ic.mutation.SetPassportSeries(s)
	return ic
}

// SetPassportNumber sets the "passport_number" field.
func (ic *IndividualCreate) SetPassportNumber(s string) *IndividualCreate {
	ic.mutation.SetPassportNumber(s)
	return ic
}

// SetPassportIssuedBy sets the "passport_issued_by" field.
func (ic *IndividualCreate) SetPassportIssuedBy(s string) *IndividualCreate {
	ic.mutation.SetPassportIssuedBy(s)
	return ic
}

// SetPassportIssuedDate sets the "passport_issued_date" field.
func (ic *IndividualCreate) SetPassportIssuedDate(s string) *IndividualCreate {
	ic.mutation.SetPassportIssuedDate(s)
	return ic
}

// SetPassportIssuedDepartmentCode sets the "passport_issued_department_code" field.
func (ic *IndividualCreate) SetPassportIssuedDepartmentCode(s string) *IndividualCreate {
	ic.mutation.SetPassportIssuedDepartmentCode(s)
	return ic
}

// SetIsAuthorizedRepresentative sets the "is_authorized_representative" field.
func (ic *IndividualCreate) SetIsAuthorizedRepresentative(b bool) *IndividualCreate {
	ic.mutation.SetIsAuthorizedRepresentative(b)
	return ic
}

// SetNillableIsAuthorizedRepresentative sets the "is_authorized_representative" field if the given value is not nil.
func (ic *IndividualCreate) SetNillableIsAuthorizedRepresentative(b *bool) *IndividualCreate {
	if b != nil {
		ic.SetIsAuthorizedRepresentative(*b)
	}
	return ic
}

// SetCreatedAt sets the "created_at" field.
func (ic *IndividualCreate) SetCreatedAt(t time.Time) *IndividualCreate {
	ic.mutation.SetCreatedAt(t)
	return ic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ic *IndividualCreate) SetNillableCreatedAt(t *time.Time) *IndividualCreate {
	if t != nil {
		ic.SetCreatedAt(*t)
	}
	return ic
}

// SetUpdatedAt sets the "updated_at" field.
func (ic *IndividualCreate) SetUpdatedAt(t time.Time) *IndividualCreate {
	ic.mutation.SetUpdatedAt(t)
	return ic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ic *IndividualCreate) SetNillableUpdatedAt(t *time.Time) *IndividualCreate {
	if t != nil {
		ic.SetUpdatedAt(*t)
	}
	return ic
}

// SetID sets the "id" field.
func (ic *IndividualCreate) SetID(i int64) *IndividualCreate {
	ic.mutation.SetID(i)
	return ic
}

// Mutation returns the IndividualMutation object of the builder.
func (ic *IndividualCreate) Mutation() *IndividualMutation {
	return ic.mutation
}

// Save creates the Individual in the database.
func (ic *IndividualCreate) Save(ctx context.Context) (*Individual, error) {
	ic.defaults()
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *IndividualCreate) SaveX(ctx context.Context) *Individual {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *IndividualCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *IndividualCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *IndividualCreate) defaults() {
	if _, ok := ic.mutation.IsAuthorizedRepresentative(); !ok {
		v := individual.DefaultIsAuthorizedRepresentative
		ic.mutation.SetIsAuthorizedRepresentative(v)
	}
	if _, ok := ic.mutation.CreatedAt(); !ok {
		v := individual.DefaultCreatedAt()
		ic.mutation.SetCreatedAt(v)
	}
	if _, ok := ic.mutation.UpdatedAt(); !ok {
		v := individual.DefaultUpdatedAt()
		ic.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *IndividualCreate) check() error {
	if _, ok := ic.mutation.FirstName(); !ok {
		return &ValidationError{Name: "first_name", err: errors.New(`ent: missing required field "Individual.first_name"`)}
	}
	if v, ok := ic.mutation.FirstName(); ok {
		if err := individual.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`ent: validator failed for field "Individual.first_name": %w`, err)}
		}
	}
	if _, ok := ic.mutation.LastName(); !ok {
		return &ValidationError{Name: "last_name", err: errors.New(`ent: missing required field "Individual.last_name"`)}
	}
	if v, ok := ic.mutation.LastName(); ok {
		if err := individual.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`ent: validator failed for field "Individual.last_name": %w`, err)}
		}
	}
	if v, ok := ic.mutation.Patronymic(); ok {
		if err := individual.PatronymicValidator(v); err != nil {
			return &ValidationError{Name: "patronymic", err: fmt.Errorf(`ent: validator failed for field "Individual.patronymic": %w`, err)}
		}
	}
	if _, ok := ic.mutation.RegistrationAddress(); !ok {
		return &ValidationError{Name: "registration_address", err: errors.New(`ent: missing required field "Individual.registration_address"`)}
	}
	if v, ok := ic.mutation.RegistrationAddress(); ok {
		if err := individual.RegistrationAddressValidator(v); err != nil {
			return &ValidationError{Name: "registration_address", err: fmt.Errorf(`ent: validator failed for field "Individual.registration_address": %w`, err)}
		}
	}
	if _, ok := ic.mutation.PassportSeries(); !ok {
		return &ValidationError{Name: "passport_series", err: errors.New(`ent: missing required field "Individual.passport_series"`)}
	}
	if v, ok := ic.mutation.PassportSeries(); ok {
		if err := individual.PassportSeriesValidator(v); err != nil {
			return &ValidationError{Name: "passport_series", err: fmt.Errorf(`ent: validator failed for field "Individual.passport_series": %w`, err)}
		}
	}
	if _, ok := ic.mutation.PassportNumber(); !ok {
		return &ValidationError{Name: "passport_number", err: errors.New(`ent: missing required field "Individual.passport_number"`)}
	}
	if v, ok := ic.mutation.PassportNumber(); ok {
		if err := individual.PassportNumberValidator(v); err != nil {
			return &ValidationError{Name: "passport_number", err: fmt.Errorf(`ent: validator failed for field "Individual.passport_number": %w`, err)}
		}
	}
	if _, ok := ic.mutation.PassportIssuedBy(); !ok {
		return &ValidationError{Name: "passport_issued_by", err: errors.New(`ent: missing required field "Individual.passport_issued_by"`)}
	}
	if v, ok := ic.mutation.PassportIssuedBy(); ok {
		if err := individual.PassportIssuedByValidator(v); err != nil {
			return &ValidationError{Name: "passport_issued_by", err: fmt.Errorf(`ent: validator failed for field "Individual.passport_issued_by": %w`, err)}
		}
	}
	if _, ok := ic.mutation.PassportIssuedDate(); !ok {
		return &ValidationError{Name: "passport_issued_date", err: errors.New(`ent: missing required field "Individual.passport_issued_date"`)}
	}
	if v, ok := ic.mutation.PassportIssuedDate(); ok {
		if err := individual.PassportIssuedDateValidator(v); err != nil {
			return &ValidationError{Name: "passport_issued_date", err: fmt.Errorf(`ent: validator failed for field "Individual.passport_issued_date": %w`, err)}
		}
	}
	if _, ok := ic.mutation.PassportIssuedDepartmentCode(); !ok {
		return &ValidationError{Name: "passport_issued_department_code", err: errors.New(`ent: missing required field "Individual.passport_issued_department_code"`)}
	}
	if v, ok := ic.mutation.PassportIssuedDepartmentCode(); ok {
		if err := individual.PassportIssuedDepartmentCodeValidator(v); err != nil {
			return &ValidationError{Name: "passport_issued_department_code", err: fmt.Errorf(`ent: validator failed for field "Individual.passport_issued_department_code": %w`, err)}
		}
	}
	if _, ok := ic.mutation.IsAuthorizedRepresentative(); !ok {
		return &ValidationError{Name: "is_authorized_representative", err: errors.New(`ent: missing required field "Individual.is_authorized_representative"`)}
	}
	if _, ok := ic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Individual.created_at"`)}
	}
	if _, ok := ic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Individual.updated_at"`)}
	}
	return nil
}

func (ic *IndividualCreate) sqlSave(ctx context.Context) (*Individual, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *IndividualCreate) createSpec() (*Individual, *sqlgraph.CreateSpec) {
	var (
		_node = &Individual{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(individual.Table, sqlgraph.NewFieldSpec(individual.FieldID, field.TypeInt64))
	)
	if id, ok := ic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ic.mutation.FirstName(); ok {
		_spec.SetField(individual.FieldFirstName, field.TypeString, value)
		_node.FirstName = value
	}
	if value, ok := ic.mutation.LastName(); ok {
		_spec.SetField(individual.FieldLastName, field.TypeString, value)
		_node.LastName = value
	}
	if value, ok := ic.mutation.Patronymic(); ok {
		_spec.SetField(individual.FieldPatronymic, field.TypeString, value)
		_node.Patronymic = &value
	}
	if value, ok := ic.mutation.RegistrationAddress(); ok {
		_spec.SetField(individual.FieldRegistrationAddress, field.TypeString, value)
		_node.RegistrationAddress = value
	}
	if value, ok := ic.mutation.PassportSeries(); ok {
		_spec.SetField(individual.FieldPassportSeries, field.TypeString, value)
		_node.PassportSeries = value
	}
	if value, ok := ic.mutation.PassportNumber(); ok {
		_spec.SetField(individual.FieldPassportNumber, field.TypeString, value)
		_node.PassportNumber = value
	}
	if value, ok := ic.mutation.PassportIssuedBy(); ok {
		_spec.SetField(individual.FieldPassportIssuedBy, field.TypeString, value)
		_node.PassportIssuedBy = value
	}
	if value, ok := ic.mutation.PassportIssuedDate(); ok {
		_spec.SetField(individual.FieldPassportIssuedDate, field.TypeString, value)
		_node.PassportIssuedDate = value
	}
	if value, ok := ic.mutation.PassportIssuedDepartmentCode(); ok {
		_spec.SetField(individual.FieldPassportIssuedDepartmentCode, field.TypeString, value)
		_node.PassportIssuedDepartmentCode = value
	}
	if value, ok := ic.mutation.IsAuthorizedRepresentative(); ok {
		_spec.SetField(individual.FieldIsAuthorizedRepresentative, field.TypeBool, value)
		_node.IsAuthorizedRepresentative = value
	}
	if value, ok := ic.mutation.CreatedAt(); ok {
		_spec.SetField(individual.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ic.mutation.UpdatedAt(); ok {
		_spec.SetField(individual.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// IndividualCreateBulk is the builder for creating many Individual entities in bulk.
type IndividualCreateBulk struct {
	config
	err      error
	builders []*IndividualCreate
}

// Save creates the Individual entities in the database.
func (icb *IndividualCreateBulk) Save(ctx context.Context) ([]*Individual, error) {
	if icb.err != nil {
		return nil, icb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Individual, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IndividualMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *IndividualCreateBulk) SaveX(ctx context.Context) []*Individual {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *IndividualCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *IndividualCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
