// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/example/micro/individuals/ent/individual"
)

// Individual is the model entity for the Individual schema.
type Individual struct {
	config `json:"-"`
	// ID of the ent.
	// matches BIGSERIAL
	ID int64 `json:"id,omitempty"`
	// FirstName holds the value of the "first_name" field.
	FirstName string `json:"first_name,omitempty"`
	// LastName holds the value of the "last_name" field.
	LastName string `json:"last_name,omitempty"`
	// Patronymic holds the value of the "patronymic" field.
	Patronymic *string `json:"patronymic,omitempty"`
	// RegistrationAddress holds the value of the "registration_address" field.
	RegistrationAddress string `json:"registration_address,omitempty"`
	// PassportSeries holds the value of the "passport_series" field.
	PassportSeries string `json:"passport_series,omitempty"`
	// PassportNumber holds the value of the "passport_number" field.
	PassportNumber string `json:"passport_number,omitempty"`
	// PassportIssuedBy holds the value of the "passport_issued_by" field.
	PassportIssuedBy string `json:"passport_issued_by,omitempty"`
	// PassportIssuedDate holds the value of the "passport_issued_date" field.
	PassportIssuedDate string `json:"passport_issued_date,omitempty"`
	// PassportIssuedDepartmentCode holds the value of the "passport_issued_department_code" field.
	PassportIssuedDepartmentCode string `json:"passport_issued_department_code,omitempty"`
	// IsAuthorizedRepresentative holds the value of the "is_authorized_representative" field.
	IsAuthorizedRepresentative bool `json:"is_authorized_representative,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Individual) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case individual.FieldIsAuthorizedRepresentative:
			values[i] = new(sql.NullBool)
		case individual.FieldID:
			values[i] = new(sql.NullInt64)
		case individual.FieldFirstName, individual.FieldLastName, individual.FieldPatronymic, individual.FieldRegistrationAddress, individual.FieldPassportSeries, individual.FieldPassportNumber, individual.FieldPassportIssuedBy, individual.FieldPassportIssuedDate, individual.FieldPassportIssuedDepartmentCode:
			values[i] = new(sql.NullString)
		case individual.FieldCreatedAt, individual.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Individual fields.
func (i *Individual) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case individual.FieldID:
			value, ok := values[j].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			i.ID = int64(value.Int64)
		case individual.FieldFirstName:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field first_name", values[j])
			} else if value.Valid {
				i.FirstName = value.String
			}
		case individual.FieldLastName:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_name", values[j])
			} else if value.Valid {
				i.LastName = value.String
			}
		case individual.FieldPatronymic:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field patronymic", values[j])
			} else if value.Valid {
				i.Patronymic = new(string)
				*i.Patronymic = value.String
			}
		case individual.FieldRegistrationAddress:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field registration_address", values[j])
			} else if value.Valid {
				i.RegistrationAddress = value.String
			}
		case individual.FieldPassportSeries:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field passport_series", values[j])
			} else if value.Valid {
				i.PassportSeries = value.String
			}
		case individual.FieldPassportNumber:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field passport_number", values[j])
			} else if value.Valid {
				i.PassportNumber = value.String
			}
		case individual.FieldPassportIssuedBy:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field passport_issued_by", values[j])
			} else if value.Valid {
				i.PassportIssuedBy = value.String
			}
		case individual.FieldPassportIssuedDate:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field passport_issued_date", values[j])
			} else if value.Valid {
				i.PassportIssuedDate = value.String
			}
		case individual.FieldPassportIssuedDepartmentCode:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field passport_issued_department_code", values[j])
			} else if value.Valid {
				i.PassportIssuedDepartmentCode = value.String
			}
		case individual.FieldIsAuthorizedRepresentative:
			if value, ok := values[j].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_authorized_representative", values[j])
			} else if value.Valid {
				i.IsAuthorizedRepresentative = value.Bool
			}
		case individual.FieldCreatedAt:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[j])
			} else if value.Valid {
				i.CreatedAt = value.Time
			}
		case individual.FieldUpdatedAt:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[j])
			} else if value.Valid {
				i.UpdatedAt = value.Time
			}
		default:
			i.selectValues.Set(columns[j], values[j])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Individual.
// This includes values selected through modifiers, order, etc.
func (i *Individual) Value(name string) (ent.Value, error) {
	return i.selectValues.Get(name)
}

// Update returns a builder for updating this Individual.
// Note that you need to call Individual.Unwrap() before calling this method if this Individual
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Individual) Update() *IndividualUpdateOne {
	return NewIndividualClient(i.config).UpdateOne(i)
}

// Unwrap unwraps the Individual entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *Individual) Unwrap() *Individual {
	_tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Individual is not a transactional entity")
	}
	i.config.driver = _tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Individual) String() string {
	var builder strings.Builder
	builder.WriteString("Individual(")
	builder.WriteString(fmt.Sprintf("id=%v, ", i.ID))
	builder.WriteString("first_name=")
	builder.WriteString(i.FirstName)
	builder.WriteString(", ")
	builder.WriteString("last_name=")
	builder.WriteString(i.LastName)
	builder.WriteString(", ")
	if v := i.Patronymic; v != nil {
		builder.WriteString("patronymic=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("registration_address=")
	builder.WriteString(i.RegistrationAddress)
	builder.WriteString(", ")
	builder.WriteString("passport_series=")
	builder.WriteString(i.PassportSeries)
	builder.WriteString(", ")
	builder.WriteString("passport_number=")
	builder.WriteString(i.PassportNumber)
	builder.WriteString(", ")
	builder.WriteString("passport_issued_by=")
	builder.WriteString(i.PassportIssuedBy)
	builder.WriteString(", ")
	builder.WriteString("passport_issued_date=")
	builder.WriteString(i.PassportIssuedDate)
	builder.WriteString(", ")
	builder.WriteString("passport_issued_department_code=")
	builder.WriteString(i.PassportIssuedDepartmentCode)
	builder.WriteString(", ")
	builder.WriteString("is_authorized_representative=")
	builder.WriteString(fmt.Sprintf("%v", i.IsAuthorizedRepresentative))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(i.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(i.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Individuals is a parsable slice of Individual.
type Individuals []*Individual
