// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EmploymentContract is the predicate function for employmentcontract builders.
type EmploymentContract func(*sql.Selector)
