// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// IndividualsColumns holds the columns for the "individuals" table.
	IndividualsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "first_name", Type: field.TypeString, Size: 50},
		{Name: "last_name", Type: field.TypeString, Size: 50},
		{Name: "patronymic", Type: field.TypeString, Nullable: true, Size: 54},
		{Name: "registration_address", Type: field.TypeString},
		{Name: "passport_series", Type: field.TypeString, Size: 4},
		{Name: "passport_number", Type: field.TypeString, Size: 6},
		{Name: "passport_issued_by", Type: field.TypeString},
		{Name: "passport_issued_date", Type: field.TypeString},
		{Name: "passport_issued_department_code", Type: field.TypeString, Size: 7},
		{Name: "is_authorized_representative", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// IndividualsTable holds the schema information for the "individuals" table.
	IndividualsTable = &schema.Table{
		Name:       "individuals",
		Columns:    IndividualsColumns,
		PrimaryKey: []*schema.Column{IndividualsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		IndividualsTable,
	}
)

func init() {
}
