// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EmploymentContractsColumns holds the columns for the "employment_contracts" table.
	EmploymentContractsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "number", Type: field.TypeString, Size: 6},
		{Name: "personnel_number", Type: field.TypeString},
		{Name: "conclusion_date", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "organization_id", Type: field.TypeInt64},
		{Name: "representative_id", Type: field.TypeInt64},
		{Name: "employee_id", Type: field.TypeInt64},
		{Name: "department_id", Type: field.TypeInt64},
		{Name: "position_id", Type: field.TypeInt64},
		{Name: "conditions_class", Type: field.TypeInt},
		{Name: "work_date_from", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "work_date_to", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "probation_months", Type: field.TypeInt, Nullable: true},
		{Name: "salary", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "real"}},
		{Name: "work_hours_from", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "time"}},
		{Name: "work_hours_to", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "time"}},
		{Name: "break_from", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "time"}},
		{Name: "break_to", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "time"}},
		{Name: "paid_leave_days", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// EmploymentContractsTable holds the schema information for the "employment_contracts" table.
	EmploymentContractsTable = &schema.Table{
		Name:       "employment_contracts",
		Columns:    EmploymentContractsColumns,
		PrimaryKey: []*schema.Column{EmploymentContractsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EmploymentContractsTable,
	}
)

func init() {
}
